/**
 * Catalog rows for BE-134 through BE-146.
 *
 * Registered through `registerBridge`. No right-hand-side AST: each row's
 * numeric body is the evaluator.
 *
 * @module bridges/condensed-r8-catalog
 */

/** Condensed-matter catalog rows, in id order. */
export const CONDENSED_R8_CATALOG_ROWS = [
  {
    id: 134,
    name: 'Bloch magnon deficit',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['condensed', 'quantum'] as [string, string],
    status: 'established' as const,
    context:
      'Quadratic magnons and one Bohr magneton per magnon give ΔM = μ_B ζ(3/2) (k_B T / (4 π D))^{3/2}. ζ(3/2) is the Bose integral and is not evaluated. g μ_B at g = 2 is not that moment. D = 2 J S a² and M(0) = μ_B S / a³ are the nested heisenberg_fraction object. Bloch law. Magnons',
    formula_latex: '\\Delta M = \\mu_B \\zeta(3/2) \\left(k_B T / (4 \\pi D)\\right)^{3/2}',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-134) — established textbook relation, PhysJS.BlochLaw.bloch_law',
    known_issues: [],
    references: [
      'The Bose integral is a hypothesis of PhysJS.BlochLaw.bloch_law, the same kind as π⁴/15 in be-90. ζ(3/2) is an input.',
    ],
    dependencies: [],
    dimensional_signature: '[L^-1 I]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateBlochLaw in src/bridges/condensed-r8.ts. The overlay formalRef is PhysJS.BlochLaw.bloch_law, kind bridge. heisenberg_fraction is nested and is not the formalRef. The catalog path passes the top-level theorem, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 135,
    name: 'Three-dimensional density of states',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['quantum', 'condensed'] as [string, string],
    status: 'established' as const,
    context:
      'Two spins, k³ = 3 π² n, and E = ℏ² k² / (2 m) give g(E) = (1/(2 π²)) (2 m / ℏ²)^{3/2} √E per volume per energy. One spin replaces 1/(2 π²) by 1/(4 π²). Not the Fermi wavevector of be-88. Density of states',
    formula_latex: 'g(E) = \\frac{1}{2\\pi^2}\\left(\\frac{2m}{\\hbar^2}\\right)^{3/2}\\sqrt{E}',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-135) — established textbook relation, PhysJS.DensityOfStates3D.dos_3d',
    known_issues: [],
    references: [
      'The two-spin count and the isotropic parabola are the hypotheses of PhysJS.DensityOfStates3D.dos_3d.',
    ],
    dependencies: [],
    dimensional_signature: '[L^-5 M^-1 T^2]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateDensityOfStates3D in src/bridges/condensed-r8.ts. The overlay formalRef is PhysJS.DensityOfStates3D.dos_3d, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 136,
    name: 'Two-dimensional density of states',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['condensed', 'quantum'] as [string, string],
    status: 'established' as const,
    context:
      'Two spins in the disk give g = m / (π ℏ²) per area, independent of energy. A valley factor other than 1 is not this density. Density of states',
    formula_latex: 'g = m / (\\pi \\hbar^2)',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-136) — established textbook relation, PhysJS.DensityOfStates2D.dos_2d',
    known_issues: [],
    references: [
      'The two-spin disk and the isotropic parabola are the hypotheses of PhysJS.DensityOfStates2D.dos_2d.',
    ],
    dependencies: [],
    dimensional_signature: '[L^-4 M^-1 T^2]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateDensityOfStates2D in src/bridges/condensed-r8.ts. The overlay formalRef is PhysJS.DensityOfStates2D.dos_2d, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 137,
    name: 'Thomas–Fermi wavevector squared',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['electromagnetic', 'condensed'] as [string, string],
    status: 'established' as const,
    context:
      'Poisson and δn = g(E_F) e φ give k_TF² = e² g(E_F) / ε0. For the parabolic gas g(E_F) = (3/2) n / E_F, so k_TF² = (e² / ε0) (3 n) / (2 E_F). e is the elementary charge. A flat density leaves the factor 1. Not the classical Debye length. Thomas–Fermi',
    formula_latex: 'k_{TF}^2 = (e^2 / \\varepsilon_0) (3 n) / (2 E_F)',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-137) — established textbook relation, PhysJS.ThomasFermi.thomas_fermi',
    known_issues: [],
    references: [
      'The screened exponential and the parabolic density of states are the hypotheses of PhysJS.ThomasFermi.thomas_fermi. g(E_F) = (3/2) n/E_F is PhysJS.FermiSea.dos_factor.',
    ],
    dependencies: [],
    dimensional_signature: '[L^-2]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateThomasFermi in src/bridges/condensed-r8.ts. The edge value is k_TF². The overlay formalRef is PhysJS.ThomasFermi.thomas_fermi, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 138,
    name: 'Built-in voltage',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['condensed', 'electromagnetic'] as [string, string],
    status: 'established' as const,
    context:
      'Complete ionization and Boltzmann tails give V_bi = (k_B T / e) ln(N_A N_D / n_i²). e is the elementary charge. The product n_p N_A = n_i² is the be-99 conclusion as an input. Not the ideal diode of be-82. Built-in voltage. p–n junction',
    formula_latex: 'V_{bi} = (k_B T / e) \\ln(N_A N_D / n_i^2)',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-138) — established textbook relation, PhysJS.BuiltinVoltage.builtin_voltage',
    known_issues: [],
    references: [
      'Complete ionization and the Boltzmann tails are the hypotheses of PhysJS.BuiltinVoltage.builtin_voltage. e is the elementary charge.',
    ],
    dependencies: [],
    dimensional_signature: '[L^2 M T^-3 I^-1]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateBuiltinVoltage in src/bridges/condensed-r8.ts. The overlay formalRef is PhysJS.BuiltinVoltage.builtin_voltage, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 139,
    name: 'Semiconductor Fermi offset',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['quantum', 'condensed'] as [string, string],
    status: 'established' as const,
    context:
      'n = p on Boltzmann tails gives E_F − (E_c + E_v)/2 = (3/4) k_B T ln(m_h* / m_e*). The 3/4 is half of 3/2. Complete ionization gives E_c − E_F = k_B T ln(N_c / N_D). Dropping the 3/2 leaves 1/2. Not a Fermi–Dirac integral. Fermi level',
    formula_latex:
      'E_F - (E_c + E_v)/2 = (3/4) k_B T \\ln(m_h^*/m_e^*),\\quad E_c - E_F = k_B T \\ln(N_c/N_D)',
    source_part: 'III' as const,
    source_section:
      'Condensed-matter catalog (be-139) — established textbook relation, PhysJS.SemiconductorFermi.fermi_level',
    known_issues: [],
    references: [
      'Both energies are the conclusion of PhysJS.SemiconductorFermi.fermi_level. The edge value is the intrinsic offset.',
    ],
    dependencies: [],
    dimensional_signature: '[energy]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateSemiconductorFermi in src/bridges/condensed-r8.ts. The edge value is the intrinsic offset. The extrinsic energy is on the same result and is not a second edge. The overlay formalRef is PhysJS.SemiconductorFermi.fermi_level, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 140,
    name: 'Onsager frequency',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['electromagnetic', 'condensed'] as [string, string],
    status: 'established' as const,
    context:
      'The orbit area steps by 1, so γ cancels and F = ℏ A / (2 π e), with Δ(1/B) = 1/F. e is the elementary charge. F has the dimension of a magnetic field. Dropping γ on one orbit is not a step of 1. Onsager. de Haas',
    formula_latex: 'F = \\hbar A / (2 \\pi e)',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-140) — established textbook relation, PhysJS.OnsagerFrequency.onsager_frequency',
    known_issues: [],
    references: [
      'The semiclassical area condition is the hypothesis of PhysJS.OnsagerFrequency.onsager_frequency. e is the elementary charge.',
    ],
    dependencies: [],
    dimensional_signature: '[M T^-2 I^-1]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateOnsagerFrequency in src/bridges/condensed-r8.ts. The overlay formalRef is PhysJS.OnsagerFrequency.onsager_frequency, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 141,
    name: 'Josephson inductance',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['condensed', 'electromagnetic'] as [string, string],
    status: 'established' as const,
    context:
      'I = I_c sin φ and V = (ℏ / (2 e)) dφ/dt. At φ = 0, cos φ = 1, so L_J = ℏ / (2 e I_c). Φ₀ = h / (2 e) and h = 2 π ℏ give L_J = Φ₀ / (2 π I_c). e is the elementary charge. A phase with cos φ ≠ 1 is not this inductance. Not the frequency of be-59. Josephson inductance',
    formula_latex: 'L_J = \\hbar / (2 e I_c)',
    source_part: 'III' as const,
    source_section:
      'Condensed-matter catalog (be-141) — established textbook relation, PhysJS.JosephsonInductance.inductance_eq',
    known_issues: [],
    references: [
      'The Josephson equations and φ = 0 are the hypotheses of PhysJS.JosephsonInductance.inductance_eq. e is the elementary charge.',
    ],
    dependencies: [],
    dimensional_signature: '[L^2 M T^-2 I^-2]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateJosephsonInductance in src/bridges/condensed-r8.ts. The overlay formalRef is PhysJS.JosephsonInductance.inductance_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 142,
    name: 'Lower critical field',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['electromagnetic', 'condensed'] as [string, string],
    status: 'established' as const,
    context:
      'The London line energy with the core cutoff ξ ≤ r ≤ λ gives B_c1 = (Φ₀ / (4 π λ²)) ln(λ/ξ), with Φ₀ = h / (2 e). e is the elementary charge. An additive constant under the logarithm changes the field and not the prefactor. Not be-96. Lower critical field',
    formula_latex: 'B_{c1} = (\\Phi_0 / (4 \\pi \\lambda^2)) \\ln(\\lambda / \\xi)',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-142) — established textbook relation, PhysJS.LowerCritical.lower_critical',
    known_issues: [],
    references: [
      'The core cutoff is the hypothesis of PhysJS.LowerCritical.lower_critical. Φ₀ = h/(2 e).',
    ],
    dependencies: [],
    dimensional_signature: '[M T^-2 I^-1]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateLowerCritical in src/bridges/condensed-r8.ts. The overlay formalRef is PhysJS.LowerCritical.lower_critical, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 143,
    name: 'AC Drude conductivity',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['condensed', 'electromagnetic'] as [string, string],
    status: 'established' as const,
    context:
      'The cosine transform of exp(−t/τ) gives Re σ = σ₀ / (1 + ω² τ²), with σ₀ = n e² τ / m. e is the elementary charge. Dropping the DC 1 is not this conductivity. Not be-123. Drude. AC conductivity',
    formula_latex: '\\mathrm{Re}\\,\\sigma = \\sigma_0 / (1 + \\omega^2 \\tau^2),\\quad \\sigma_0 = n e^2 \\tau / m',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-143) — established textbook relation, PhysJS.AcDrude.ac_drude',
    known_issues: [],
    references: [
      'The relaxation transform is the hypothesis of PhysJS.AcDrude.ac_drude. σ₀ = n e² τ / m is an input of that theorem and is evaluated here from n, m, and τ. e is the elementary charge.',
    ],
    dependencies: [],
    dimensional_signature: '[L^-3 M^-1 T^3 I^2]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateAcDrude in src/bridges/condensed-r8.ts. The edge value is Re σ. The overlay formalRef is PhysJS.AcDrude.ac_drude, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 144,
    name: 'Matthiessen lifetime',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['condensed', 'quantum'] as [string, string],
    status: 'established' as const,
    context:
      'Independent Poisson processes give 1/τ = 1/τ₁ + 1/τ₂. One Drude factor ρ_i = C / τ_i makes ρ = ρ₁ + ρ₂. One lifetime is not the parallel sum. Not a collision integral. Matthiessen',
    formula_latex: '1/\\tau = 1/\\tau_1 + 1/\\tau_2',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-144) — established textbook relation, PhysJS.Matthiessen.matthiessen',
    known_issues: [],
    references: [
      'Independence of the two Poisson processes is the hypothesis of PhysJS.Matthiessen.matthiessen. The edge value is τ.',
    ],
    dependencies: [],
    dimensional_signature: '[time]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateMatthiessen in src/bridges/condensed-r8.ts. The edge value is the parallel lifetime. The resistivity sum is on the same result and is not a second edge. The overlay formalRef is PhysJS.Matthiessen.matthiessen, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 145,
    name: 'Stoner susceptibility',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['quantum', 'condensed'] as [string, string],
    status: 'established' as const,
    context:
      'The geometric series of bubbles gives χ = χ_P / (1 − I g(E_F)) for |I g(E_F)| < 1. The pole 1 − I g(E_F) = 0 is the same formula as I g(E_F) = 1. χ_P is be-94 and is not re-proved. The first two bubbles are not the closed form. Stoner',
    formula_latex: '\\chi = \\chi_P / (1 - I g(E_F))',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-145) — established textbook relation, PhysJS.Stoner.stoner',
    known_issues: [],
    references: [
      'The geometric series for |I g(E_F)| < 1 is the hypothesis of PhysJS.Stoner.stoner. χ_P is be-94.',
    ],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateStoner in src/bridges/condensed-r8.ts. The overlay formalRef is PhysJS.Stoner.stoner, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
  {
    id: 146,
    name: 'Gorter–Casimir fraction',
    category: 'F',
    category_name: 'Condensed Matter - High Energy Bridges',
    bridges: ['condensed', 'electromagnetic'] as [string, string],
    status: 'established' as const,
    context:
      'The exponent 4 is a hypothesis. n_s/n = 1 − (T/T_c)^4, and the London depths of be-75, not re-proved, give λ(T) = λ(0) / √(1 − (T/T_c)^4). The exponent 2 is not 4 when the reduced temperature is neither 0 nor 1. Not a BCS gap and not a second proof of be-75. Gorter–Casimir. Two-fluid',
    formula_latex: 'n_s/n = 1 - (T/T_c)^4',
    source_part: 'III' as const,
    source_section: 'Condensed-matter catalog (be-146) — established textbook relation, PhysJS.GorterCasimir.gorter_casimir',
    known_issues: [],
    references: [
      'The exponent p = 4 is the hypothesis of PhysJS.GorterCasimir.gorter_casimir. The edge value is n_s/n.',
    ],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: 'Closed-form evaluator evaluateGorterCasimir in src/bridges/condensed-r8.ts. The edge value is n_s/n. λ(T) is on the same result and is not a second edge. The overlay formalRef is PhysJS.GorterCasimir.gorter_casimir, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.',
  },
];
