/**
 * Universal Physics Tensor — Bridge Equation Index
 *
 * Machine-readable catalog of all 40 bridge equations from the UPT specification
 * (Parts I-VI). Each entry preserves the spec's stated status, known issues,
 * references, and dependencies on other bridge equations.
 *
 * Generated by scripts/extract.py (~/.claude/playground/upt_bridge_extraction/);
 * see data/bridges/README.md for regen instructions.
 *
 * Source-of-truth files: docs/specification/Part-{I-VI}.md
 *
 * Honest-claude: fields not explicitly stated in the spec are null (not guessed).
 * - dimensional_signature is null for not-yet-encoded entries. Populated for
 *   hand-encoded equations (currently 11, 14, 18, 29, 47, 48) — see
 *   `src/bridges/equations/`. Populated values are exactly what
 *   `format()` produces for the inferred Dimension shape; never free-form prose.
 * - known_issues are extracted ONLY from explicit issue-markers in the spec
 *   ("**Known issue:**", "**Additional known issue:**", "**Bound violation:**",
 *   etc.). Equations whose Status text discusses problems narratively without
 *   such a marker have known_issues: [] — see status_text appended in `notes`.
 *
 * @module bridges
 */

export type BridgeEquationStatus =
  | 'established'
  | 'speculative'
  | 'highly-speculative'
  | 'invalid';

/**
 * Type predicate: an "active" status is one where the entry is part of
 * ongoing research (established / speculative / highly-speculative). The
 * 'invalid' status marks deprecated or self-refuting entries (BE-16
 * today) that should be excluded from active-research summaries,
 * tier-promotion candidate pools, and dimensional-encoding queues.
 *
 * Use as: `BRIDGE_EQUATIONS.filter((e) => isActiveStatus(e.status))`.
 *
 * Source: type-design-expert Critical-Hole on the 'invalid' arm.
 */
export function isActiveStatus(
  s: BridgeEquationStatus,
): s is Exclude<BridgeEquationStatus, 'invalid'> {
  return s !== 'invalid';
}

export type BridgeIssueSeverity =
  | 'self-refuting'
  | 'dimensional'
  | 'index-structure'
  | 'sign'
  | 'undefined-quantity'
  | 'phenomenological-ansatz'
  | 'other';

export type BridgeIssueFixable =
  | 'spec-edit'
  | 'reformulation'
  | 'unfixable-must-mark-invalid'
  | 'unknown';

export interface KnownIssue {
  severity: BridgeIssueSeverity;
  /** Verbatim issue text from the spec (may be paraphrased; cf. source). */
  description: string;
  fixable: BridgeIssueFixable;
}

export interface BridgeEquationEntry {
  /** Equation number, 11-50. */
  id: number;
  /** Verbatim heading text from the spec. */
  name: string;
  /** Category letter (A-O). */
  category: string;
  /** Category display name, e.g. "Quantum-Classical Bridges". */
  category_name: string;
  /** Two-element tuple naming the bridged regimes. */
  bridges: [string, string];
  status: BridgeEquationStatus;
  /** 1-2 sentence summary from the spec's Context bullet. */
  context: string;
  /** Primary equation as LaTeX, decoded from upmath SVG src. */
  formula_latex: string | null;
  source_part: 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI';
  source_section: string;
  known_issues: KnownIssue[];
  /** arXiv IDs and other identifiers as cited in the spec. */
  references: string[];
  /** IDs of other bridge equations explicitly referenced in this entry. */
  dependencies: number[];
  /** SI dimensional signature (null = not yet analyzed; Tier 4 work). */
  dimensional_signature: string | null;
  /** Free-form notes (origin Status text appended for traceability). */
  notes: string;
}

export const BRIDGE_EQUATIONS: BridgeEquationEntry[] = [
{
  id: 11,
  name: `Decoherence Master Equation`,
  category: `A`,
  category_name: `Quantum-Classical Bridges`,
  bridges: [`quantum`, `classical`] as [string, string],
  status: 'established',
  context: `Explains how quantum superpositions collapse to classical states via environmental interaction`,
  formula_latex: `\\frac{\\partial \\rho}{\\partial t} = -\\frac{i}{\\hbar}[H, \\rho] + \\sum_k \\gamma_k(\\lambda) \\left[ L_k \\rho L_k^\\dagger - \\frac{1}{2}\\{L_k^\\dagger L_k, \\rho\\} \\right], \\quad \\gamma_k(\\lambda) = \\gamma_0 \\left(\\frac{\\lambda}{\\lambda_0}\\right)^2`,
  source_part: 'I',
  source_section: `Part-I Category A`,
  known_issues: [],
  references: [
    `Lindblad 1976, Commun. Math. Phys. 48:119`,
    `Gorini-Kossakowski-Sudarshan 1976, J. Math. Phys. 17:821`,
    `Caldeira-Leggett 1983, Physica A 121, 587`,
    `Caldeira-Leggett 1985, Phys. Rev. A 31, 1059`,
    `Breuer & Petruccione 2002, The Theory of Open Quantum Systems (OUP), §3.6, §4.5`,
  ],
  dependencies: [],
  dimensional_signature: `[frequency]`,
  notes: `see source | status_text: Established (Lindblad form). Auxiliary coupling-dependent rate corrected 2026-05-04 (R0 audit, branch fix/be-11-decoherence-coupling) from the broken Arrhenius-in-coupling form γ_k(T,λ) = γ_0 exp(-λ/λ_thermal) — which was exponentially *decreasing* in coupling, physically backwards — to the Caldeira-Leggett weak-coupling form γ_k(λ) = γ_0 (λ/λ_0)². The Lindblad master equation itself is unchanged and remains established literature.`,
},
{
  id: 12,
  name: `Mesoscopic Coherence Length Equation`,
  category: `A`,
  category_name: `Quantum-Classical Bridges`,
  bridges: [`quantum`, `classical`] as [string, string],
  status: 'speculative',
  context: `Determines the scale at which quantum effects vanish`,
  formula_latex: `\\xi_{\\text{coh}}(T,N) = \\frac{\\xi_0}{\\sqrt{1 + \\frac{N}{N_c} + \\left(\\frac{T}{T_c}\\right)^\\nu}}`,
  source_part: 'I',
  source_section: `Part-I Category A`,
  known_issues: [
    {
      severity: 'undefined-quantity',
      // Re-tiered R1 -> R2 on 2026-05-01 (branch fix/r1-batch-spec-edits).
      // The audit's 'spec-edit' classification was optimistic: the cube
      // exponent N_c = (E_int/(k_B T))^3, the undefined ω_decoherence, and
      // the undefined ξ_0 cannot be repaired by transcription correction
      // alone -- there is no published interpolation formula of this form
      // (BE-12 is novel to this framework), so identifying ω_decoherence
      // with ω_c from BE-11 or with another scale, and motivating the cube,
      // requires inventing physics rather than citing literature.
      description: `[R1->R2 re-tier 2026-05-01] the critical particle number \`N_c = (E_int/(k_B T))^3\` uses a cube exponent that is not motivated by any specific decoherence model (Zurek, Caldeira-Leggett, or BEC variational). Treat the cube as a phenomenological ansatz. **Additional known issue:** \`T_c = hbar * omega_decoherence / k_B\` uses \`omega_decoherence\` as an undefined / self-referential quantity -- it is introduced here without independent definition, and it is unclear whether this equals the bath cutoff frequency \`omega_c\` from Bridge Equation 11 or a distinct scale. \`xi_0\` is also introduced without definition. A corrected formulation should identify these with previously-defined physical scales.`,
      fixable: 'reformulation',
    }
  ],
  references: [`Zurek 2003 Rev. Mod. Phys. 75:715 (decoherence overview)`, `Caldeira-Leggett 1983 Physica A 121:587 (system-bath coupling scales)`, `Pitaevskii-Stringari 2003 §6 (BEC coherence length)`],
  dependencies: [11],
  dimensional_signature: null,
  notes: `[R1->R2 re-tier 2026-05-01, branch fix/r1-batch-spec-edits] The R1 audit classified BE-12 as 'spec-edit' fixable, but on closer reading the issue requires inventing physics: the formula is novel to this framework (no literature interpolation of this form exists), so identifying ω_decoherence with ω_c (BE-11 dependency) or any other named scale, motivating the cube exponent, and defining ξ_0 are reformulation tasks, not transcription fixes. Per honest-claude, preserved as R2 candidate. status_text: Phenomenological / Novel conjecture. A coherence length interpolation formula of this form has not appeared in the literature; individual limits (small-N, low-T) match BEC-type coherence length scaling, but the combined N- and T-dependent form is original. | What would unblock a real fix (2026-05-04 R2 gap-spec): a domain expert in open-quantum-system / decoherence theory must (a) define ξ_0 in terms of a microscopic length scale (candidates: thermal de Broglie wavelength λ_th = h/√(2πmk_BT), BEC healing length ξ_h = ℏ/√(2mgn), or the Caldeira-Leggett coherence-length cutoff; each has a different temperature- and density-dependence), (b) decide whether ω_decoherence is the bath-cutoff frequency ω_c from BE-11 (yielding a derived-not-independent T_c) or an independent decoherence-onset scale, and (c) cite or derive the cube exponent in N_c (Zurek's einselection argument scales as a power of system-bath coupling, not necessarily cube). All three decisions require physics judgment, not transcription.`,
},
{
  id: 13,
  name: `Landauer-Wheeler Information-Geometry Equation`,
  category: `B`,
  category_name: `Information-Physical Bridges`,
  bridges: [`information`, `physical`] as [string, string],
  status: 'highly-speculative',
  context: `Proposes a conjectural link from information erasure to spacetime curvature`,
  formula_latex: `R_{\\mu\\nu} - \\frac{1}{2}Rg_{\\mu\\nu} = \\frac{8\\pi G}{c^4}\\left[T_{\\mu\\nu}^{\\text{matter}} + k_B T \\ln(2) I_{\\mu\\nu}\\right]`,
  source_part: 'I',
  source_section: `Part-I Category B`,
  known_issues: [
    {
      severity: 'dimensional',
      description: `The dimensional analysis of the information stress-energy tensor <img src="https://i.upmath.me/svg/I_%7B%5Cmu%5Cnu%7D" alt="I_{\\mu\\nu}" /> as currently defined does not close; a future revision should either redefine <img src="https://i.upmath.me/svg/I_%7B%5Cmu%5Cnu%7D" alt="I_{\\mu\\nu}" /> directly in stress-energy dimensions or adjust the pre-factors.`,
      fixable: 'reformulation',
    }
  ],
  references: [`Landauer 1961 IBM J. Res. Dev. 5:183`, `Bennett 1973 IBM J. Res. Dev. 17:525`, `Wheeler 1989 'Information, Physics, Quantum'`, `Verlinde 2011 JHEP 04:029 (arXiv:1001.0785)`, `Jacobson 1995 Phys. Rev. Lett. 75:1260 (arXiv:gr-qc/9504004)`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. The existence of an information-geometric back-reaction on spacetime at the level proposed here is not an established result. Landauer's original principle (<img src="https://i.upm... | What would unblock a real fix (2026-05-04 R2 gap-spec): the information stress-energy tensor I_μν as defined (∂²S_info/(∂g^μν ∂τ) · c⁴/(8πG)) does not close dimensionally — S_info has units depending on log-base convention (dimensionless for nats/bits or J/K when k_B is reabsorbed), ∂g^μν is dimensionless, ∂τ has units of time, and c⁴/(8πG) has units of force; the product does not yield stress-energy [J/m³]. Two competing literature reformulations are non-equivalent: (a) Jacobson's thermodynamic-derivation route (arXiv:gr-qc/9504004) derives Einstein's equations from δQ = T·dS applied to local Rindler horizons — no separate I_μν is postulated; (b) Verlinde's entropic-gravity route (arXiv:1001.0785) treats gravity as an entropic force from holographic screens — also dispenses with I_μν. A third path "redefine I_μν directly in stress-energy dimensions" requires inventing a new operational definition of information density; domain expert needed to select.`,
},
{
  id: 14,
  name: `Quantum Error Correction Holographic Mapping`,
  category: `B`,
  category_name: `Information-Physical Bridges`,
  bridges: [`information`, `physical`] as [string, string],
  status: 'established',
  context: `How bulk physics emerges from boundary quantum information`,
  formula_latex: `|\\psi_{\\text{bulk}}\\rangle = U_{\\text{HQECC}} \\sum_i \\alpha_i |\\text{code}_i\\rangle_{\\text{boundary}}`,
  source_part: 'I',
  source_section: `Part-I Category B`,
  known_issues: [],
  references: [`arXiv:hep-th/0603001`],
  dependencies: [],
  dimensional_signature: `[entropy]`,
  notes: `see source | status_text: Established (within AdS/CFT). The Ryu-Takayanagi formula S = Area(gamma)/(4 G_N hbar) is a well-established result in AdS/CFT holography (Ryu and Takayanagi 2006, arXiv:hep-th/0603001). Extensions to ...`,
},
{
  id: 15,
  name: `Universal Emergence Equation`,
  category: `C`,
  category_name: `Emergence and Complexity`,
  bridges: [`microscale`, `emergent`] as [string, string],
  status: 'speculative',
  context: `How macroscopic laws emerge from microscopic interactions`,
  formula_latex: `\\frac{\\partial O_{\\text{macro}}}{\\partial t} = \\mathcal{F}[\\{O_{\\text{micro}}\\}] + \\eta\\nabla^2 O_{\\text{macro}} + \\zeta\\left(\\frac{\\partial^2 S}{\\partial O^2}\\right)`,
  source_part: 'I',
  source_section: `Part-I Category C`,
  known_issues: [
    {
      severity: 'dimensional',
      description: `[R2 gap-spec 2026-05-04] (1) the RG beta function \`β(k)\` is dimensionless (logarithmic derivative of a coupling), making the functional \`F[{O_micro}]\` not directly comparable with \`∂O_macro/∂t\`; (2) the term \`ζ(∂²S/∂O²)\` has dimensions depending on the unit of O and on whether S is physical entropy (J/K) or information (bits/nats), with ζ then needing a specific unit assignment to make the equation dimensionally homogeneous. As written the equation is schematic, not operational. Reformulation requires choosing between (a) Hohenberg-Halperin model A/B/C dynamics (Rev. Mod. Phys. 49:435, 1977) where the functional is a free-energy gradient ∂O/∂t = -Γ δF/δO + noise; (b) Wetterich's exact RG flow (Phys. Lett. B 301:90, 1993; arXiv:1003.1366 review) which has the right structure but uses an effective average action Γ_k, not a coarse-grained observable O_macro; (c) Mori-Zwanzig projector-operator formalism (Mori 1965, Prog. Theor. Phys. 33:423) for explicit micro->macro coarse-graining. Each gives a different operational equation.`,
      fixable: 'reformulation',
    },
    {
      severity: 'phenomenological-ansatz',
      description: `[R2 gap-spec 2026-05-04] The combination of an RG-flow functional, diffusive Laplacian, and entropy-second-derivative term is not standard in any single literature framework; it is a phenomenological synthesis. To become operational, the framework must be selected (Hohenberg-Halperin / Wetterich / Mori-Zwanzig — see dimensional issue above), and the role of the entropy second derivative ζ(∂²S/∂O²) must be derived rather than postulated.`,
      fixable: 'reformulation',
    }
  ],
  references: [`Hohenberg-Halperin 1977 Rev. Mod. Phys. 49:435 (model A/B/C dynamics)`, `Wetterich 1993 Phys. Lett. B 301:90 (exact RG flow)`, `Berges-Tetradis-Wetterich 2002 Phys. Rep. 363:223 (arXiv:hep-ph/0005122)`, `Mori 1965 Prog. Theor. Phys. 33:423 (projector formalism)`, `Zwanzig 1960 J. Chem. Phys. 33:1338`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative / schematic. This is a conjectural emergence equation combining an RG flow functional, a diffusive term, and a second-derivative entropy term. | What would unblock a real fix (2026-05-04 R2 gap-spec): the equation has no analog in a single literature framework; it must be replaced by selecting one of three non-equivalent reformulations: (a) Hohenberg-Halperin model A/B/C dynamics (Rev. Mod. Phys. 49:435, 1977) — gradient flow ∂O/∂t = -Γ δF/δO + noise; (b) Wetterich exact RG flow (Phys. Lett. B 301:90, 1993; arXiv:hep-ph/0005122 review) — but this evolves an effective action Γ_k, not a coarse-grained observable; (c) Mori-Zwanzig projection — explicit micro->macro coarse-graining via projector operators. Each path produces a different operational equation. Domain expert in non-equilibrium statistical mechanics / functional RG must choose.`,
},
{
  id: 16,
  name: `Complexity-Entropy Production Relation`,
  category: `C`,
  category_name: `Emergence and Complexity`,
  bridges: [`microscale`, `emergent`] as [string, string],
  status: 'invalid',
  context: `Proposes a conjectural link from computational complexity to thermodynamic entropy production`,
  formula_latex: `\\frac{dS}{dt} = k_B \\cdot \\mathcal{C}(\\rho) \\cdot \\frac{\\partial I}{\\partial t}`,
  source_part: 'I',
  source_section: `Part-I Category C`,
  known_issues: [
    // Three distinct issues, previously stored with the same combined
    // description text (extractor artifact). De-duplicated 2026-05-04 per
    // comment-analyzer #3 — the description is now the per-severity slice
    // of the original combined text, and the spec's `**Known issues:**`
    // block continues to carry the full narrative for archival reference.
    {
      severity: 'undefined-quantity',
      description: `The circuit complexity C(rho) is not independently defined, making the equation effectively a definition of complexity in terms of the entropy-to-information ratio rather than a falsifiable physical relation. A substantive version would require an independent operational definition of C(rho) (e.g., gate count in a specific universal gate set) and a monotonicity constraint to avoid second-law violations.`,
      fixable: 'unfixable-must-mark-invalid',
    },
    {
      severity: 'sign',
      description: `The quantity labeled I below, defined as Tr(rho log rho), is the negative of the von Neumann entropy (which is -Tr(rho log rho)); the sign convention in the equation as written should be checked in a future revision.`,
      fixable: 'unfixable-must-mark-invalid',
    },
    {
      severity: 'self-refuting',
      description: `Second-Law problem: combining I = Tr(rho log rho) = -S_vN with dS/dt = k_B * C(rho) * dI/dt gives dS/dt = -k_B * C(rho) * dS_vN/dt. If S and S_vN are taken to be the same entropy, this forces dS/dt (1 + k_B C(rho)) = 0, i.e., dS/dt = 0 for any C(rho) > -1/k_B — the equation algebraically forbids entropy change, violating the Second Law. The formula is therefore not merely imprecise; it is self-refuting unless S and S_vN are distinct quantities (which must then be defined separately).`,
      fixable: 'unfixable-must-mark-invalid',
    }
  ],
  references: [`arXiv:1402.5674`, `arXiv:1509.07876`],
  dependencies: [],
  dimensional_signature: null,
  notes: `INVALID per disposition decision 2026-05-01 (Tier 3 audit, Bridge-Remediation-Plan.md R3): the equation is algebraically self-refuting (combining I = Tr(rho log rho) = -S_vN with the master relation forces dS/dt = 0 for any C(rho) > -1/k_B), and circuit complexity C(rho) is not independently defined. Marking invalid keeps the record visible, flags the problem, and preserves the option to reformulate later if a clean S vs. S_vN distinction emerges. | status_text (preserved): Speculative. This is loosely inspired by the black-hole complexity program — Susskind's "complexity = volume" conjecture (arXiv:1402.5674) and the later "complexity = action" conjecture by Brown, Robe...`,
},
{
  id: 17,
  name: `Electromagnetic-Gravitational Unification via Torsion`,
  category: `D`,
  category_name: `Field Unification Bridges`,
  bridges: [`field-A`, `field-B`] as [string, string],
  status: 'speculative',
  context: `Proposed Einstein-Cartan theory extension`,
  formula_latex: `R_{\\mu\\nu}^{\\lambda\\rho} = \\mathring{R}_{\\mu\\nu}^{\\lambda\\rho} + K_{\\mu\\nu}^{\\lambda\\rho} + \\alpha\\left(F_{\\mu\\nu} F^{\\lambda\\rho} - \\frac{1}{4} g_{\\mu\\nu} F_{\\alpha\\beta} F^{\\alpha\\beta}\\right)`,
  source_part: 'I',
  source_section: `Part-I Category D`,
  known_issues: [
    // Re-tiered R1 -> R2 on 2026-05-01 (branch fix/r1-batch-spec-edits).
    // The audit's 'spec-edit' classification was optimistic on three
    // interlocking issues that together require a from-scratch
    // reformulation of the EM-curvature coupling, not transcription:
    //  - The Maxwell-stress-energy term `(1/4) g_{μν} F²` has 2 free
    //    indices while the LHS Riemann tensor has 4; fixing this needs a
    //    new tensorial structure (e.g., antisymmetrized δ-products), not
    //    a typo correction.
    //  - `l_EM = sqrt(ℏc/e²)` is dimensionless in Gaussian units (sqrt of
    //    inverse fine-structure ≈ 11.7) and not-a-length in SI; choosing
    //    the 'classical electron radius' as a replacement is a research
    //    decision, not a transcription fix.
    //  - The standard Einstein-Cartan contorsion is rank-3 `K^ρ_{μν}`,
    //    antisymmetric in the lower indices from the torsion definition;
    //    rewriting the equation with the correct rank-3 contorsion changes
    //    the structure of the gravitational sector entirely.
    {
      severity: 'index-structure',
      description: `[R1->R2 re-tier 2026-05-01] The equation has an index-structure mismatch: the term '(1/4) g_{μν} F_{αβ} F^{αβ}' has only two free indices (μ,ν) while the LHS R_{μν}^{λρ} has four. The standard Maxwell stress-energy tensor T_{μν}^{(EM)} has 2 indices, so reproducing it on the RHS requires a different tensorial structure (e.g., antisymmetrized δ-products promoting it to rank-4). A correct formulation must invent or cite a specific 4-index structure, not patch the existing 2-index term -- this is reformulation, not transcription.`,
      fixable: 'reformulation',
    },
    {
      severity: 'dimensional',
      description: `[R1->R2 re-tier 2026-05-01] The coupling 'alpha = l_P^2 / l_{EM}^2' uses 'l_{EM} = sqrt(ℏc/e²)' which is not a length in SI (units J·m/C², whose square root is not meters). In Gaussian units the quantity is dimensionless (sqrt of inverse fine-structure ≈ 11.7). Choosing a replacement -- classical electron radius r_e, Compton wavelength, Bohr radius, or Planck length -- is a *physics decision* with different physical interpretations, not a transcription fix.`,
      fixable: 'reformulation',
    },
    {
      severity: 'undefined-quantity',
      description: `[R1->R2 re-tier 2026-05-01] The contorsion tensor is written 'K_{μν}^{λρ}' (rank-4) but the standard Einstein-Cartan contorsion is rank-3 'K^ρ_{μν}' (antisymmetric in the lower indices, from torsion T^ρ_{μν} = K^ρ_{μν} − K^ρ_{νμ}). Rewriting with the correct rank-3 K changes the structure of the gravitational sector and requires rederiving the EM-curvature coupling self-consistently -- a reformulation task.`,
      fixable: 'reformulation',
    }
  ],
  references: [`Hehl-vonderHeyde-Kerlick-Nester 1976 Rev. Mod. Phys. 48:393`, `Trautman 2006 in 'Encyclopedia of Math. Phys.' (Einstein-Cartan review)`, `Shapiro 2002 Phys. Rep. 357:113 (arXiv:hep-th/0103093, torsion in physics)`, `Cabral-Lobo 2017 Eur. Phys. J. C 77:237 (electromagnetic-torsion coupling)`],
  dependencies: [],
  dimensional_signature: null,
  notes: `[R1->R2 re-tier 2026-05-01, branch fix/r1-batch-spec-edits] The R1 audit classified BE-17 as 'spec-edit' fixable across three coupled issues. On closer reading, the issues require reformulation: (a) fixing the 4-vs-2-index mismatch needs a new tensorial structure (antisymmetrized δ-products or a different RHS), (b) replacing 'l_{EM}' with a physical length (classical electron radius vs. Compton wavelength vs. Planck length) is a physics decision, (c) rewriting the rank-4 contorsion as rank-3 changes the gravitational sector. Per honest-claude, preserved as R2 candidate. status_text: Speculative. Einstein-Cartan theory itself is well-established (Hehl et al., Rev. Mod. Phys. 48:393 (1976)), but the specific form of EM coupling to curvature proposed here is not standard. | What would unblock a real fix (2026-05-04 R2 gap-spec): an Einstein-Cartan-with-electromagnetism specialist must (1) pick the correct rank-4 RHS structure — canonical options are an antisymmetrized δ-product T^{(EM)}_{[μν][λρ]} ~ (g_μ^[λ T_{ν}^{ρ]} - trace) or a direct 4-Maxwell tensor F_{μν}F^{λρ} — these give different curvature-EM couplings; (2) select the EM length scale — classical electron radius r_e = e²/(4πε₀m_ec²) ≈ 2.82 fm (probes electron self-energy), Compton wavelength λ_C = ℏ/(m_ec) (probes pair-production), or Planck length l_P (probes quantum-gravity scale); each gives a different α with different physical interpretation; (3) rewrite the contorsion in canonical rank-3 form K^ρ_{μν} (antisymmetric in lower indices, derived from torsion T^ρ_{μν} = K^ρ_{μν} - K^ρ_{νμ}) and re-derive the EM-curvature coupling self-consistently. References: Trautman 2006 review, Shapiro 2002 Phys. Rep. 357:113 (arXiv:hep-th/0103093), Cabral-Lobo 2017 EPJ C 77:237.`,
},
{
  id: 18,
  name: `Non-Abelian Dark Matter Gauge Theory`,
  category: `D`,
  category_name: `Field Unification Bridges`,
  bridges: [`field-A`, `field-B`] as [string, string],
  // Status remains 'speculative' — the form correction (added |D_μ Φ|²
  // kinetic term, flipped V sign) is canonical Peskin-Schroeder §20.1
  // textbook physics, but the existence of this hidden non-Abelian sector is
  // the speculative content and remains unverified.
  status: 'speculative',
  context: `Dark matter as gauge bosons of hidden symmetry`,
  // 2026-05-01 (R1 audit): added missing |D_μ Φ|² kinetic term so Φ is
  // dynamical, and flipped V sign to standard L = T − V convention.
  formula_latex: `\\mathcal{L}_{\\text{dark}} = -\\frac{1}{4} G^a_{\\mu\\nu} G^{a\\mu\\nu} + |D_\\mu \\Phi|^2 + \\bar{\\psi}(i\\gamma^\\mu D_\\mu - m_\\psi)\\psi - V(|\\Phi|)`,
  source_part: 'I',
  source_section: `Part-I Category D`,
  // The R1 audit's "missing kinetic term" issue is resolved by the spec-edit.
  known_issues: [],
  references: [`arXiv:1311.0029`, `arXiv:2005.01515`, `Peskin-Schroeder 1995 §20.1`],
  dependencies: [],
  dimensional_signature: `[L^8 M^4 T^-8]`,
  notes: `see source | status_text: Speculative. Corrected 2026-05-01 (R1 audit, branch fix/r1-batch-spec-edits): added missing |D_μ Φ|² kinetic term and flipped V sign to standard L = T − V convention. Citation: Peskin-Schroeder 1995 §20.1 (canonical non-Abelian + complex-scalar SSB Lagrangian template). Status remains 'speculative' — the form is now canonical textbook, but the existence of this hidden non-Abelian dark sector is the speculative content.`,
},
{
  id: 19,
  name: `Quantum Bounce Equation`,
  category: `E`,
  category_name: `Cosmological-Quantum Bridges`,
  bridges: [`quantum`, `cosmological`] as [string, string],
  status: 'speculative',
  context: `Loop quantum cosmology prediction`,
  formula_latex: `H^2 = \\frac{8\\pi G}{3} \\rho\\left(1 - \\frac{\\rho}{\\rho_{\\text{crit}}}\\right) + \\frac{\\Lambda}{3}`,
  source_part: 'I',
  source_section: `Part-I Category E`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The critical density rho_crit = 3 c^2 / (8 pi G l_P^2) is a dimensional estimate that differs from the canonical Ashtekar-Singh LQC value rho_crit ~ 0.41 rho_Planck (arXiv:1108.0893) by a factor of ~3-4 because it omits the Barbero-Immirzi parameter gamma (~0.2375) whose cube enters the standard coefficient.`,
      fixable: 'spec-edit',
    }
  ],
  references: [`arXiv:1108.0893`],
  dependencies: [],
  dimensional_signature: `[T^-2]`,
  notes: `see source | status_text: Speculative (LQC-inspired). Loop Quantum Cosmology bounce equations (Ashtekar, Bojowald) modify the Friedmann equation via a rho/rho_crit term. The formula as written rho_crit = 3c^2/(8 pi G l_P^2) ap... | Tier-5 AST encoding landed 2026-05-04 (branch tier-5/wave-1, src/bridges/equations/be-19-quantum-bounce.ts) — RHS encoded as scalar Friedmann + bounce factor; LHS is H². dimensional_signature [T^-2] is exactly format(infer(rhs)). Encoding is dimensional only; it does NOT promote status from speculative, and the spec issue (rho_crit vs canonical Ashtekar-Singh value with Barbero-Immirzi factor) is preserved.`,
},
{
  id: 20,
  name: `Vacuum Fluctuation Dark Energy Coupling`,
  category: `E`,
  category_name: `Cosmological-Quantum Bridges`,
  bridges: [`quantum`, `cosmological`] as [string, string],
  status: 'speculative',
  context: `Zero-point energy contribution to cosmic acceleration`,
  formula_latex: `\\rho_{\\text{vac}} = \\rho_0 + \\int d^3k \\frac{\\hbar\\omega_k}{2} \\cdot \\zeta\\left(\\frac{k}{k_{\\text{UV}}}\\right)`,
  source_part: 'I',
  source_section: `Part-I Category E`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `Naive evaluation of this integral produces the cosmological-constant problem: the result is ~10^120 times the observed dark-energy density. The cutoff zeta(k/k_UV) phenomenologically regularizes this but does not solve the problem; the equation labels where the problem sits in the catalog rather than proposing a resolution.`,
      fixable: 'unknown',
    }
  ],
  references: [`arXiv:1402.5674`, `arXiv:1509.07876`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative / open problem. The integral of (hbar omega_k / 2) zeta(k/k_UV) of vacuum zero-point energy with a UV cutoff is **the standard expression whose naive evaluation produces the famous cosmolo...`,
},
{
  id: 21,
  name: `AdS/CMT Correspondence Equation`,
  category: `F`,
  category_name: `Condensed Matter - High Energy Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Holographic duality between strongly correlated electrons and gravitational systems`,
  formula_latex: `G_R(\\omega,k) = -i \\lim_{r \\to \\infty} r^{2\\Delta-d} \\left(\\frac{g^{rr}}{\\sqrt{g^{tt}}}\\right) \\frac{\\partial_r \\phi(r,\\omega,k)}{\\phi_0(\\omega,k)}`,
  source_part: 'II',
  source_section: `Part-II Category F`,
  known_issues: [],
  references: [
    `Son & Starinets 2002 *Phys. Rev. D* 65:104021 (arXiv:hep-th/0205051; Minkowski-space correlators in AdS/CFT — the canonical retarded-Green's-function recipe used in this BE)`,
    `Policastro, Son & Starinets 2002 *JHEP* 0209:043 (arXiv:hep-th/0205052; companion paper applying the recipe to AdS hydrodynamics — note this is three-author, not the two-author Son-Starinets paper above)`,
    `Iqbal & Liu 2008 *Fortsch. Phys.* 57:367 (arXiv:0903.2596; AdS/CMT review)`,
  ],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Established. The holographic dictionary for retarded Green's functions in AdS/CMT (anti-de Sitter / condensed matter correspondence) is a well-understood result (Son and Starinets 2002, arXiv:hep-th/0205051 — the formula in this BE is the retarded-Green's-function recipe from that paper, not the AdS-hydrodynamics application of the companion three-author Policastro-Son-Starinets paper hep-th/0205052; both papers contain the recipe but Son-Starinets is the canonical two-author reference).`,
},
{
  id: 22,
  name: `Topological Entanglement Entropy - Quantum Gravity Link`,
  category: `F`,
  category_name: `Condensed Matter - High Energy Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Connects topological phases to quantum error correction in gravity`,
  // Reformulated 2026-05-05 to the canonical Kitaev-Preskill / Levin-Wen
  // single-subsystem form S(R) = α L(R) − γ + O(L^-1). The originally-
  // stated three-term form (−γ + α log(ξ/a) + β(T/T_c)^ν log(A/ℓ_P²))
  // had area-law-doubled and finite-T extension issues and was not
  // derivable from any standard TEE construction; see notes below.
  formula_latex: `S(R) = \\alpha L(R) - \\gamma + \\mathcal{O}(L^{-1})`,
  source_part: 'II',
  source_section: `Part-II Category F`,
  known_issues: [
    {
      // Wave-G CR-F4 (2026-05-05): retagged 'phenomenological-ansatz' →
      // 'other'. The Kitaev-Preskill formula itself is canonical (not an
      // ansatz); the issue is FRAMING — applying TEE to quantum gravity
      // requires identifying which gravitational degree of freedom R
      // bounds, which is the speculative move. 'other' is the closest
      // correct fit from the existing BridgeIssueSeverity enum.
      severity: 'other',
      description: `[Reformulated 2026-05-05] The TEE formula S(R) = α L(R) − γ is the canonical Kitaev-Preskill / Levin-Wen single-subsystem form (PRL 96:110404, 110405; 2006); γ = log(D) where D is the total quantum dimension. The "QG link" framing is original to this catalog and not in either reference: applying TEE to quantum gravity requires identifying which gravitational degree of freedom the boundary R bounds, which has not been committed to in UPT scope. Encoding pins the math; the bridge to QG is the speculative content.`,
      fixable: 'reformulation',
    }
  ],
  references: [
    `Kitaev-Preskill 2006 Phys. Rev. Lett. 96:110404 (arXiv:hep-th/0510092)`,
    `Levin-Wen 2006 Phys. Rev. Lett. 96:110405 (arXiv:cond-mat/0510613)`,
  ],
  dependencies: [],
  dimensional_signature: `[1]`,
  notes: `[Reformulated 2026-05-05, R2 → R5-leaning] Replaced the originally-stated three-term form (which had area-law-doubled and finite-T extension issues) with the canonical Kitaev-Preskill / Levin-Wen single-subsystem form S(R) = α L(R) − γ. AST-encoded; round-trips to dimensional_signature \`[1]\`. Status remains speculative because the QG-link framing of this bridge — using TEE as a probe of gravitational entanglement — is original to this catalog and not in either Kitaev-Preskill or Levin-Wen, even though the formula itself is established.`,
},
{
  id: 23,
  name: `Strange Metal - Black Hole Duality`,
  category: `F`,
  category_name: `Condensed Matter - High Energy Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  // Downgraded 2026-05-01 from 'established' to 'speculative' (R0 audit fix).
  // Rationale: the third term of the spec formula is mathematically vacuous
  // under the standard τ_P = ℏ/(k_B T) substitution, and the audit-suggested
  // replacement form has the same defect. See known_issues[0] below and the
  // preserved Known Issue block in docs/specification/Part-II.md.
  status: 'speculative',
  context: `Linear resistivity in strange metals matches black hole dynamics`,
  formula_latex: `\\rho(T) = \\rho_0 + AT + B\\sqrt{\\frac{\\hbar}{k_B T \\tau_P}}`,
  source_part: 'II',
  source_section: `Part-II Category F`,
  known_issues: [
    {
      severity: 'self-refuting',
      description: `Substituting τ_P = ℏ/(k_B T) into √(ℏ/(k_B T τ_P)) yields √1 = 1 identically, collapsing the third term to the constant B. The Tier-3 audit (Bridge-Remediation-Plan.md) recommended replacing with √(k_B T · τ_P / ℏ), but that form ALSO reduces to √1 = 1 under the same substitution — algebraically inevitable, since τ_P · k_B T = ℏ constrains every product/quotient built from those two factors alone. A non-vacuous form requires introducing a second independent timescale or energy (e.g. τ_el, SYK J, E_F, or the MSS Lyapunov bound λ_L = 2π k_B T/ℏ). Marking 'reformulation' rather than 'spec-edit': selecting the right scale is a research/domain-expert decision, not a transcription fix. Status downgraded to 'speculative' on 2026-05-01 pending expert input.`,
      fixable: 'reformulation',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative (downgraded 2026-05-01 from "Established (but transcription issue)"; third-term form vacuous under τ_P substitution and audit-suggested fix is equally vacuous; needs reformulation by domain expert — Tier R2).`,
},
{
  id: 24,
  name: `Quantum Coherence in Photosynthesis Efficiency`,
  category: `G`,
  category_name: `Quantum Biology Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `How quantum effects enhance energy transfer in biological systems`,
  formula_latex: `\\eta_{\\text{transfer}} = \\eta_{\\text{classical}} \\left[1 + \\kappa \\exp\\left(-\\frac{t}{\\tau_{\\text{coh}}}\\right) |\\langle\\psi_{\\text{donor}}|\\psi_{\\text{acceptor}}\\rangle|^2\\right]`,
  source_part: 'II',
  source_section: `Part-II Category G`,
  known_issues: [
    {
      severity: 'other',
      description: `[R2 gap-spec 2026-05-04] With kappa in [0.1, 0.3] and eta_classical close to 1, the formula gives eta_transfer = eta_classical (1 + kappa exp(-t/tau_coh) |<psi_d|psi_a>|^2), which can exceed 1 (the stated bound eta in [0, 1] is violated by the equation as written). The literature does not contain an η-saturating "coherent enhancement" formula in this exact form, so reformulation requires picking from quantum-transport candidates: (1) Förster resonance energy transfer (FRET) rate k_FRET (Förster 1948 Annalen der Physik 437:55) — gives a dimensionless transfer-yield η_FRET = k_FRET/(k_FRET + k_other) ∈ [0,1] by construction, but is incoherent; (2) Redfield/HEOM (hierarchical equations of motion) with explicit dephasing — Ishizaki-Fleming 2009 JCP 130:234111 — gives time-dependent populations that are positivity-preserving and η ∈ [0,1] automatic; (3) Lindblad GKSL master equation with jump operators describing donor->acceptor transfer — also positivity-preserving. Coherence enhancement enters via the off-diagonal elements of ρ rather than as a multiplicative factor on η_classical. Domain expert needed.`,
      fixable: 'reformulation',
    }
  ],
  references: [`Engel et al. 2007 Nature 446:782 (original FMO experiment)`, `Duan et al. 2017 PNAS 114:8493 (vibrational reinterpretation)`, `Cao et al. 2020 Sci. Adv. 6:eaaz4888 (consensus update)`, `Förster 1948 Annalen der Physik 437:55 (FRET)`, `Ishizaki-Fleming 2009 J. Chem. Phys. 130:234111 (HEOM)`, `Mohseni-Rebentrost-Lloyd-Aspuru-Guzik 2008 J. Chem. Phys. 129:174106 (ENAQT)`, `Thyrhaug et al. 2018 Nat. Chem. 10:780 (FMO 2D-spectroscopy reinterpretation: vibrational vs. electronic coherence; reassigns long-lived FMO oscillations to vibrational origin)`, `Wilkins & Dattani 2015 J. Chem. Theory Comput. 11:3411 (HEOM benchmarking: pseudomode/numerically-exact comparisons that constrain claims about electronic-coherence lifetimes in light-harvesting complexes)`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Contested / superseded. The proposed quantum-coherent enhancement of photosynthetic energy transfer was based on Engel et al. 2007 FMO data (τ_coh ~ 100 fs). Subsequent work (Duan et al., PNAS 114, 84... | What would unblock a real fix (2026-05-04 R2 gap-spec): the multiplicative η = η_classical(1 + κ exp(...)|<ψ_d|ψ_a>|²) form admits η > 1 (bound violation) and is not in any cited literature. A correct formulation must replace it with a positivity-preserving quantum-transport equation: (a) Förster FRET rate k_FRET → η_FRET = k_FRET/(k_FRET + k_other) ∈ [0,1] by construction (Förster 1948); (b) Redfield/HEOM with explicit dephasing (Ishizaki-Fleming 2009 JCP 130:234111); (c) Lindblad master equation with donor->acceptor jump operators. Coherence enhancement should appear via ρ off-diagonals, not as a multiplicative correction. Mainstream consensus (Cao et al. 2020 Sci. Adv. 6:eaaz4888) is that observed long-lived oscillations in FMO are vibrational, not electronic; this should also inform the reformulation. Domain expert in open-quantum-system biology / ENAQT (environment-assisted quantum transport, Mohseni-Rebentrost-Lloyd-Aspuru-Guzik 2008) needed.`,
},
{
  id: 25,
  name: `Consciousness - Quantum Information Bridge`,
  category: `G`,
  category_name: `Quantum Biology Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Penrose-Hameroff orchestrated reduction theory`,
  formula_latex: `t_{\\text{OR}} = \\frac{\\hbar}{E_G} = \\frac{\\hbar}{\\Delta m c^2 \\Delta x / l_P}`,
  source_part: 'II',
  source_section: `Part-II Category G`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The formula E_G = Delta m c^2 Delta x / l_P contains a spurious factor of Delta x / l_P not present in Penrose's original gravitational self-energy proposal (canonical form: E_G ~ G (Delta m)^2 / Delta x). Use the Penrose form for any physical estimate; the form here is an ad-hoc modification original to earlier drafts.`,
      fixable: 'spec-edit',
    },
    {
      severity: 'other',
      description: `The Orch OR mechanism is contradicted by Tegmark (Phys. Rev. E 61, 4194 (2000); arXiv:quant-ph/9907009): decoherence times for microtubule-scale superpositions at biological temperatures are ~10^-13 s, vs. neural processing timescales of ~10^-3 s — a 10-order-of-magnitude gap that effectively rules out the proposed mechanism.`,
      fixable: 'unknown',
    }
  ],
  references: [
    `Penrose & Hameroff 1996 *Math. Comput. Simul.* 40:453 (Orchestrated objective reduction of quantum coherence in brain microtubules; original Orch-OR proposal)`,
    `Tegmark 2000 *Phys. Rev. E* 61:4194 (arXiv:quant-ph/9907009; decoherence-times-vs-cognition critique, ~10 orders of magnitude gap)`,
    `Reimers, McKemmish, McKenzie, Mark, Hush 2009 *PNAS* 106:4219 (Fröhlich-condensate weak/strong/coherent-regime critique of the proposed mechanism at biological temperature)`,
    `McKemmish, Reimers, McKenzie, Mark, Hush 2009 *Phys. Rev. E* 80:021912 (consolidated direct critique: Penrose-Hameroff Orch-OR is not biologically feasible)`,
  ],
  dependencies: [],
  dimensional_signature: `[time]`,
  notes: `see source | status_text: Highly speculative — contradicted by quantitative decoherence analyses. The Penrose-Hameroff orchestrated objective reduction (Orch OR) theory proposes that gravitationally-induced wavefunction collap... | Tier-5 AST encoding landed 2026-05-04 (branch tier-5/wave-1, src/bridges/equations/be-25-orch-or.ts) — RHS encoded as scalar identity ℏ ℓ_P / (Δm c² Δx). dimensional_signature [time] is exactly format(infer(rhs)). Encoding is dimensional only; it does NOT promote status from highly-speculative, and the documented spec issue (spurious Δx/ℓ_P factor vs. Penrose's E_G ~ G(Δm)²/Δx) is preserved.`,
},
{
  id: 26,
  name: `DNA Mutation - Quantum Tunneling Rate`,
  category: `G`,
  category_name: `Quantum Biology Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Proton tunneling in base pair tautomerization`,
  formula_latex: `\\Gamma_{\\text{mutation}} = \\nu_0 \\exp\\left(-\\frac{2}{\\hbar}\\int_{x_1}^{x_2}\\sqrt{2m(V(x)-E)} , dx\\right) \\cdot f(T,\\text{pH}, \\text{EM})`,
  source_part: 'II',
  source_section: `Part-II Category G`,
  known_issues: [],
  references: [
    `Gamow 1928 *Z. Phys.* 51:204 (alpha-decay tunneling; original WKB application)`,
    `Löwdin 1963 *Rev. Mod. Phys.* 35:724 (proton tunneling in DNA hydrogen bonds; canonical biological application)`,
    `Landau & Lifshitz, Quantum Mechanics §50 (WKB approximation, canonical reference)`,
    `Lujan, Williams & Kunkel 2016 *Cold Spring Harb. Perspect. Biol.* 8:a019745 (DNA replication-error fidelity: polymerase proofreading + mismatch repair; competing classical-error pathway)`,
  ],
  dependencies: [],
  dimensional_signature: `[frequency]`,
  notes: `see source | status_text: Established (WKB). The WKB tunneling rate formula is standard quantum mechanics (Gamow 1928; Landau-Lifshitz QM Section 50). The application to DNA base-pair tautomerization via proton tunneling is a ... | Tier-5 AST encoding landed 2026-05-04 (branch tier-5/wave-1, src/bridges/equations/be-26-dna-tunneling.ts) — RHS encoded as ν_0 · exp_factor · f_correction; the WKB exponent (2/ℏ)·∫√(2m(V−E))dx is exposed as DNA_TUNNELING_WKB_ARG and verified dimensionless via the AST's integral primitive with caret-0.5 for the square root. dimensional_signature [frequency] is exactly format(infer(rhs)). Bracket-check with proton mass / 0.4 eV barrier / 1 Å width gives Γ ~ 10 /s, in the textbook 10^-3 to 10^3 /s range for hydrogen-bond proton transfer.`,
},
{
  id: 27,
  name: `Fluctuation-Dissipation Violation in Active Matter`,
  category: `H`,
  category_name: `Non-Equilibrium Statistical Mechanics`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Living systems violate equilibrium relations`,
  formula_latex: `\\chi(\\omega) = \\frac{1}{k_B T_{\\text{eff}}(\\omega)} \\int dt , e^{i\\omega t} \\langle \\delta F(t) \\delta x(0) \\rangle + \\Sigma_{\\text{active}}(\\omega)`,
  source_part: 'II',
  source_section: `Part-II Category H`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `Frequency-dependent effective temperature is a standard concept (Cugliandolo 2011, J. Phys. A 44:483001) but the specific functional form T_eff(omega) = T + alpha v_0^2 / (omega^2 + gamma^2) used here is conjectural and not derived from a microscopic model.`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative extension. Frequency-dependent effective temperature is a standard concept in active-matter / non-equilibrium statistical mechanics (Cugliandolo 2011, J. Phys. A 44:483001). The specific f...`,
},
{
  id: 28,
  name: `Maximum Entropy Production Principle`,
  category: `H`,
  category_name: `Non-Equilibrium Statistical Mechanics`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Why nature chooses specific non-equilibrium steady states`,
  formula_latex: `\\delta \\int \\left(\\frac{dS}{dt} - \\lambda \\sum_i J_i X_i - \\mu(\\nabla \\cdot \\mathbf{v})\\right) dt = 0`,
  source_part: 'II',
  source_section: `Part-II Category H`,
  known_issues: [],
  references: [
    `Dewar 2003 *J. Phys. A* 36:631 (information-theoretic derivation of MEPP from MaxEnt; canonical proposal)`,
    `Dewar 2005 *J. Phys. A* 38:L371 (MEPP follow-up clarifying scope and assumptions)`,
    `Grinstein & Linsker 2007 *J. Phys. A* 40:9717 (MEPP rebuttal; counterexamples to Dewar's derivation)`,
    `Prigogine 1947 *Étude thermodynamique des phénomènes irréversibles* (minimum-entropy-production principle for near-equilibrium linear systems; the contrasting principle MEPP must reconcile with)`,
  ],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Contested principle. Maximum Entropy Production (MEPP) is a proposed but contested principle in non-equilibrium thermodynamics (Dewar 2005; rebutted by Grinstein and Linsker 2007). It conflicts with P...`,
},
{
  id: 29,
  name: `Jarzynski Equality Extension to Gravity`,
  category: `H`,
  category_name: `Non-Equilibrium Statistical Mechanics`,
  bridges: [`unknown`, `unknown`] as [string, string],
  // Status remains 'speculative' — the gravitational-work form is now
  // canonical GR (Hilbert action variation), but applying Jarzynski's
  // flat-spacetime equality to this curved-spacetime work is unverified.
  status: 'speculative',
  context: `Work fluctuations in gravitational fields`,
  // 2026-05-01 (R1 audit): replaced ill-defined `g_{μν} dT^{μν}` with the
  // canonical Hilbert action variation `T^{μν} δg_{μν} √(-g) d⁴x`. Factor
  // `1/(2c⁴)` from MTW §21.3 / Wald §E.1.
  formula_latex: `\\langle \\exp(-\\beta W) \\rangle = \\exp(-\\beta \\Delta F) \\cdot \\exp\\left(-\\frac{\\beta}{2c^4} \\int T^{\\mu\\nu} \\delta g_{\\mu\\nu} \\sqrt{-g} \\, d^4 x\\right)`,
  source_part: 'II',
  source_section: `Part-II Category H`,
  // The R1 audit's 'undefined integration measure' issue is resolved.
  known_issues: [],
  references: [`Jarzynski 1997 PRL 78:2690`, `MTW Gravitation §21.3`, `Wald General Relativity 1984 §E.1`],
  dependencies: [],
  dimensional_signature: `[energy]`,
  notes: `see source | status_text: Speculative extension. Corrected 2026-05-01 (R1 audit, branch fix/r1-batch-spec-edits): replaced ill-defined 'g_{μν} dT^{μν}' with the canonical Hilbert action variation 'T^{μν} δg_{μν} √(-g) d⁴x' (MTW §21.3 Eq. 21.51; Wald §E.1 Eq. E.1.14). Factor 1/(2c⁴) follows from the standard 'T^{μν} := (2/√(-g)) δ(√(-g) L_matter)/δg_{μν}' definition. Status remains 'speculative' — the form of the gravitational work is now standard GR, but applying Jarzynski's flat-spacetime equality to curved-spacetime is the conjectural extension.`,
},
{
  id: 30,
  name: `Entanglement - Geometry Equation (ER=EPR generalized)`,
  category: `I`,
  category_name: `Emergent Spacetime`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `How spacetime emerges from quantum entanglement`,
  formula_latex: `g_{\\mu\\nu}(x) = \\eta_{\\mu\\nu} + \\kappa \\sum_{ij} \\langle x| \\text{Tr}*j(\\rho*{ij} \\log \\rho_{ij}) |x\\rangle`,
  source_part: 'II',
  source_section: `Part-II Category I`,
  known_issues: [
    {
      severity: 'index-structure',
      description: `LHS is a rank-2 tensor with free indices mu,nu, but RHS is a scalar sum — index structure does not match. A properly-stated entanglement-geometry relation has a form like delta g_{mu nu}(x) ~ l_P^2 partial_mu partial_nu S_EE(x) (Van Raamsdonk).`,
      fixable: 'reformulation',
    },
    {
      severity: 'undefined-quantity',
      description: `Tr_j(rho_{ij} log rho_{ij}) is a scalar (negative entanglement entropy), not an operator, so <x|...|x> is undefined on it. Additionally |x> is a non-normalizable position eigenstate requiring regularization.`,
      fixable: 'reformulation',
    },
    {
      severity: 'dimensional',
      description: `kappa ~ l_P^2 has units [L]^2 and S is dimensionless, so kappa S has units [L]^2, but metric perturbations should be dimensionless. Treat the current formula as schematic.`,
      fixable: 'reformulation',
    }
  ],
  references: [`arXiv:1005.3035`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. Van Raamsdonk 2010 (arXiv:1005.3035) and Swingle 2012 showed that entanglement structure can encode geometric data in AdS/CFT, but the specific formula \`g_{mu nu}(x) = eta_{mu nu} ...`,
},
{
  id: 31,
  name: `Causal Set - Continuum Limit`,
  category: `I`,
  category_name: `Emergent Spacetime`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Discrete to continuous spacetime transition`,
  formula_latex: `R = \\frac{2}{\\sqrt{\\pi}} \\left(\\frac{N}{V^{2/4}} - k_1 - k_2(\\rho^2 l_P^4)^{1/4}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category I`,
  known_issues: [
    {
      severity: 'dimensional',
      // Re-tiered R1 -> R2 on 2026-05-01 (branch fix/r1-batch-spec-edits).
      // The audit's own description ends with 'should be replaced with
      // their published formula' -- which is by definition reformulation,
      // not spec-edit. While `V^{2/4} -> V^{1/2}` is a literal numerical
      // identity (a clean typo), the second part (dimensional mismatch in
      // the (ρ² ℓ_P⁴)^{1/4} Ricci correction term) cannot be repaired by
      // transcription -- the Benincasa-Dowker discrete-to-continuum
      // formula uses dimensionless N counts, not (ρ² ℓ_P⁴)^{1/4}, and
      // grafting their result onto this form requires a structural
      // rewrite. Per honest-claude: preserve.
      description: `[R1->R2 re-tier 2026-05-01] (1) the exponent V^{2/4} is either a typo for V^{1/2} or should be V^{(d-2)/d} with d substituted -- this part *is* a clean spec-edit but cannot be applied in isolation because (2) the (ρ² ℓ_P⁴)^{1/4} term does not match Ricci-scalar dimensions [L^-2], and the audit's recommended fix ('replace with Benincasa-Dowker's published formula') is by definition reformulation, not transcription. The Benincasa-Dowker (arXiv:1001.2725) result uses dimensionless count differences (e.g., N - 9 N_1 + 16 N_2 - 8 N_3 over V^{2/d}), not the (ρ² ℓ_P⁴)^{1/4} structure here, so a faithful correction is a structural rewrite.`,
      fixable: 'reformulation',
    }
  ],
  references: [`arXiv:1001.2725`, `Benincasa-Dowker 2010 Phys. Rev. Lett. 104:181301`, `Sorkin 2007 'Causal Sets' (arXiv:gr-qc/0309009)`, `Dowker 2005 in '100 Years of Relativity' (arXiv:gr-qc/0508109)`, `Glaser-Surya 2014 Class. Quantum Grav. 31:045007 (BD action numerics)`],
  dependencies: [],
  dimensional_signature: null,
  notes: `[R1->R2 re-tier 2026-05-01, branch fix/r1-batch-spec-edits] The R1 audit classified BE-31 as 'spec-edit' fixable, but its own description prescribes 'should be replaced with their published formula' -- reformulation by definition. The V^{2/4} -> V^{1/2} typo is a clean spec-edit on its own, but the second issue (dimensional mismatch in (ρ² ℓ_P⁴)^{1/4} vs. Ricci [L^-2]) cannot be repaired by transcription: the Benincasa-Dowker formula uses dimensionless count differences (N - 9N_1 + 16N_2 - 8N_3) / V^{2/d}, structurally different from the (ρ² ℓ_P⁴)^{1/4} written here. Applying only the typo half would leave the deeper dimensional issue, so per honest-claude: preserve as R2 candidate. status_text: Speculative. Benincasa-Dowker (arXiv:1001.2725) established discrete-to-continuum limits for causal set action and Ricci scalar. | What would unblock a real fix (2026-05-04 R2 gap-spec): replace the entire current expression with the published Benincasa-Dowker (BD) discretization. In d=4, the BD Ricci scalar uses an inclusion-exclusion-style count over causal-set inclusive intervals: R(p) = (4/√6) · ℓ_P^{-2} · [1 - (N_0(p) - 9 N_1(p) + 16 N_2(p) - 8 N_3(p))/⟨n(p)⟩], where N_k(p) counts inclusive intervals of cardinality k+2 below point p, and ⟨n(p)⟩ is the expected sprinkling density. This is structurally distinct from any expression in (ρ², ℓ_P⁴) and uses dimensionless counts, not a continuum density. Adopting BD (arXiv:1001.2725; numerical study Glaser-Surya 2014 Class. Quantum Grav. 31:045007) is the only literature-cited path; doing so requires a full rewrite, not patching. Domain expert in causal set theory needed to verify dimension-by-dimension constants.`,
},
{
  id: 32,
  name: `Quantum Reference Frame Transformation`,
  category: `I`,
  category_name: `Emergent Spacetime`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `How physics transforms between quantum reference frames`,
  formula_latex: `|\\psi\\rangle_B = \\int dg , U(g) |\\psi\\rangle_A \\otimes |g\\rangle_{\\text{frame}}`,
  source_part: 'II',
  source_section: `Part-II Category I`,
  known_issues: [],
  references: [`arXiv:1712.07207`, `arXiv:2004.14292`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Active research. Quantum Reference Frames (QRF) formalism -- where reference frames are themselves quantum systems that can be in superposition -- is a legitimate active research area (Giacomini, Cast...`,
},
{
  id: 33,
  name: `Quantum-Classical Critical Point Mapping`,
  category: `J`,
  category_name: `Phase Transitions and Criticality`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Relates <img src="https://i.upmath.me/svg/d" alt="d" />-dimensional quantum to <img src="https://i.upmath.me/svg/(d%2B1)" alt="(d+1)" />-dimensional classical transitions`,
  formula_latex: `\\xi_{\\text{quantum}}(T \\to 0) = \\frac{\\xi_{\\text{classical}}(T_{\\text{eff}} = \\hbar\\omega/k_B)}{\\sqrt{1 + (E_0/k_B T)^2}}`,
  source_part: 'II',
  source_section: `Part-II Category J`,
  known_issues: [
    {
      severity: 'sign',
      description: `[R2 gap-spec 2026-05-04] As T -> 0, (E_0/k_B T)^2 -> infinity, making xi_quantum -> 0 — but correlation lengths at a quantum critical point (QCP) must DIVERGE as T -> 0, not vanish. The canonical Hertz-Millis result is xi ~ T^(-nu/z) (Sondhi-Girvin-Carini-Shahar 1997 Rev. Mod. Phys. 69:315). The formula has the wrong T-dependence; reformulation requires replacing the (1 + (E_0/k_B T)^2)^{-1/2} structure with the canonical scaling form. Hertz 1976 PRB 14:1165 and Millis 1993 PRB 48:7183 give the original derivations.`,
      fixable: 'reformulation',
    },
    {
      severity: 'undefined-quantity',
      description: `[R2 gap-spec 2026-05-04] The dynamic exponent z appears in the where-clause but does not appear in the formula. The canonical scaling xi ~ T^(-nu/z) requires z explicitly. A corrected formulation must restore z (and the static exponent ν) into the main expression. The d → d+1 quantum-to-classical mapping (Hertz 1976) requires both ν and z; their absence makes the formula non-operational.`,
      fixable: 'reformulation',
    }
  ],
  references: [`Hertz 1976 Phys. Rev. B 14:1165 (Hertz-Millis theory)`, `Millis 1993 Phys. Rev. B 48:7183`, `Sondhi-Girvin-Carini-Shahar 1997 Rev. Mod. Phys. 69:315 (continuous QPTs review)`, `Sachdev 2011 'Quantum Phase Transitions' 2nd ed. (Cambridge)`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative extension. The dynamic critical exponent z is standard in quantum phase-transition theory (Sondhi-Girvin-Carini-Shahar 1997). | What would unblock a real fix (2026-05-04 R2 gap-spec): the formula has two coupled defects — (i) wrong T -> 0 limit (gives ξ -> 0 instead of canonical divergence ξ ~ T^{-ν/z}), and (ii) z absent from the main expression. Reformulation requires replacing with the standard Hertz-Millis quantum-critical scaling: ξ_quantum(T) ~ ξ_0 · (T/T_0)^{-ν/z}, where ν is the static correlation-length exponent and z the dynamic exponent (Hertz 1976 PRB 14:1165; Millis 1993 PRB 48:7183; review Sondhi et al. 1997 RMP 69:315; textbook Sachdev 'Quantum Phase Transitions' 2011 2nd ed.). The d-dimensional quantum to (d+z)-dimensional classical mapping is the underlying structural fact (NOT d to d+1, which is only correct for z=1). Domain expert in quantum-critical phenomena needed to (a) confirm whether the framework targets the z=1 or general-z case, (b) pick the universality class (3D Ising, XY, Heisenberg, ...), and (c) replace the formula entirely.`,
},
{
  id: 34,
  name: `Kibble-Zurek Mechanism in Curved Spacetime`,
  category: `J`,
  category_name: `Phase Transitions and Criticality`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Defect formation during cosmological phase transitions`,
  formula_latex: `n_{\\text{defect}} = \\left(\\frac{\\tau_Q}{\\tau_0}\\right)^{-\\frac{d\\nu}{1+z\\nu}} \\cdot \\exp\\left(-\\frac{m_{\\text{defect}} c^2}{k_B T_{\\text{reh}}}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category J`,
  known_issues: [
    {
      severity: 'dimensional',
      description: `LHS n_defect is encoded as DIMENSIONLESS to match the spec form, but the canonical Kibble-Zurek defect density has dim [L]^(-d) (defects per unit d-dimensional spatial volume; e.g. [L^-3] for d=3 point defects in 3D). The standard form is n ~ xi^(-d) where xi ~ (tau_Q/tau_0)^(nu/(1+z*nu)) is the freeze-out correlation length, so a microscopic length scale (e.g., lattice spacing a) must appear as a 1/a^d prefactor to restore the correct units. The spec writes the formula as a pure scaling ratio (Kibble 1976 J. Phys. A 9:1387; Zurek 1985 Nature 317:505), which is what is encoded here; promoting to the dimensional form requires editing the spec and adding the 1/a^d factor.`,
      fixable: 'reformulation',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: `[1]`,
  notes: `see source | status_text: Established extension. The Kibble-Zurek defect density n ~ (tau_Q/tau_0)^(-d nu / (1 + z nu)) is established (Kibble 1976; Zurek 1985). The added exp(-m_defect c^2 / (k_B T_reh)) suppression for curve... | Tier-5 AST encoding landed 2026-05-04 (branch tier-5/wave-1, src/bridges/equations/be-34-kibble-zurek.ts) — RHS encoded as (τ_Q/τ_0)^(-1/2) · exp_factor for the canonical (d=ν=z=1) case; the dimensional answer is independent of the chosen exponent. The exp argument m c² / (k_B T_reh) is exposed as KIBBLE_ZUREK_EXP_ARG and verified dimensionless. dimensional_signature [1] is exactly format(infer(rhs)). LHS n_defect is dimensionless (scaling ratio, no length scale in the formula).`,
},
{
  id: 35,
  name: `Conformal Bootstrap - Physical Operator Equation`,
  category: `J`,
  category_name: `Phase Transitions and Criticality`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Constrains possible conformal field theories`,
  formula_latex: `\\langle O_1(x_1) O_2(x_2) O_3(x_3) O_4(x_4) \\rangle = \\sum_{\\Delta,\\ell} C_{12}^O C_{34}^O g_{\\Delta,\\ell}(u,v)`,
  source_part: 'II',
  source_section: `Part-II Category J`,
  known_issues: [],
  references: [`arXiv:0807.0004`, `arXiv:1805.04405`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Established. The conformal bootstrap crossing-symmetry equation is well established in CFT and has produced rigorous bounds on critical exponents for the 3D Ising model and other theories (Rattazzi-Ry...`,
},
{
  id: 36,
  name: `MOND - Dark Matter Interpolation Function`,
  category: `K`,
  category_name: `Modified Theories and Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Smooth transition between MOND and dark matter regimes`,
  formula_latex: `\\mathbf{F} = \\mathbf{F}*N \\mu\\left(\\frac{a}{a_0}\\right) + \\mathbf{F}*{\\text{DM}}\\left(1 - \\mu\\left(\\frac{a}{a_0}\\right)\\right)`,
  source_part: 'II',
  source_section: `Part-II Category K`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The hybrid linear blend F = F_N mu(a/a_0) + F_DM (1 - mu(a/a_0)) is not a standard MOND formulation. Standard MOND (Milgrom 1983) uses mu(a/a_0)*a = a_Newtonian as an implicit relation on a single acceleration, not a linear blend of Newtonian and DM accelerations. The form here is a bespoke ansatz original to this framework.`,
      fixable: 'reformulation',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative / non-standard. The hybrid F = F_N μ(a/a_0) + F_DM (1 − μ(a/a_0)) form is **not a standard MOND formulation**. Standard MOND (Milgrom 1983) uses μ(a/a_0)·a = a_Newtonian as an implicit rel...`,
},
{
  id: 37,
  name: `Variable Speed of Light Cosmology`,
  category: `K`,
  category_name: `Modified Theories and Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'invalid',
  context: `Solving horizon problem without inflation`,
  formula_latex: `c(t) = c_0\\left[1 + \\epsilon\\left(\\frac{t}{t_P}\\right)^n \\exp\\left(-\\frac{t}{t_c}\\right)\\right]`,
  source_part: 'II',
  source_section: `Part-II Category K`,
  known_issues: [
    {
      severity: 'undefined-quantity',
      description: `[R3 disposition 2026-05-05] The c(t) ansatz is operationally undefined per Ellis-Uzan 2005 Am. J. Phys. 73:240 (arXiv:gr-qc/0305099): "varying c" has no operational content unless the formulation specifies which c is varying (phase, group, two-way, signal) AND which dimensionful constant ratio is actually changing (e.g., α = e²/ℏc, or ratios of m_e c² to m_p c²). Only dimensionless ratios of constants are physically measurable; a bare c(t) is gauge in the choice of units. The original ansatz c_0 [1 + ε (t/t_P)^n exp(-t/t_c)] specifies neither, and is therefore not a falsifiable claim about physics — it is a relabeling of the unit system over time.`,
      fixable: 'unfixable-must-mark-invalid',
    },
    {
      severity: 'phenomenological-ansatz',
      description: `[R3 disposition 2026-05-05] The form c_0 [1 + ε (t/t_P)^n exp(-t/t_c)] is original to this framework and is not derived from or matched to any of the three canonical VSL formulations: Albrecht-Magueijo 1999 (arXiv:astro-ph/9811018, non-covariant minimal-coupling VSL), Moffat 1993 (arXiv:gr-qc/9211020, diffeomorphism-violating VSL), or Barrow 1999 (arXiv:astro-ph/9811022, varying-c with energy conservation). Each canonical VSL formulation gives a DIFFERENT modified Friedmann equation; the three are not equivalent (cf. Magueijo 2003 review, arXiv:astro-ph/0305457). A reformulation cannot patch the present ansatz — it would have to replace it with one of the three, AND independently survive the Ellis-Uzan critique above (none cleanly does).`,
      fixable: 'unfixable-must-mark-invalid',
    }
  ],
  references: [`arXiv:astro-ph/9811018`, `Albrecht-Magueijo 1999 Phys. Rev. D 59:043516 (arXiv:astro-ph/9811018)`, `Moffat 1993 Int. J. Mod. Phys. D 2:351 (arXiv:gr-qc/9211020)`, `Barrow 1999 Phys. Rev. D 59:043515 (arXiv:astro-ph/9811022)`, `Magueijo 2003 Rep. Prog. Phys. 66:2025 (VSL review, arXiv:astro-ph/0305457)`, `Ellis-Uzan 2005 Am. J. Phys. 73:240 ('c is the speed of light, isn't it?', arXiv:gr-qc/0305099)`],
  dependencies: [],
  dimensional_signature: null,
  notes: `INVALID per disposition decision 2026-05-05 (R3 audit, see docs/planning/BE-37-VSL-Disposition-Brief.md). Marking invalid keeps the record visible, flags the operational-meaninglessness problem from Ellis-Uzan 2005 (arXiv:gr-qc/0305099), and preserves the option to introduce a fresh entry — covering one specific VSL formulation with explicit constant-ratio specification — if a domain expert later commits to one. The original c(t) ansatz here is preserved as historical record but is not a falsifiable physical claim. | Earlier disposition history: [R1->R2 re-tier 2026-05-01, branch fix/r1-batch-spec-edits] R1 classified spec-edit fixable; reclassified R2 because the fix was reformulation-by-definition. [R2->R3 disposition 2026-05-05, this commit] R2 reformulation path itself is blocked: the three canonical VSL formulations are non-equivalent and choosing one is a physics decision Daniel did not commit to, AND each must survive the Ellis-Uzan critique independently — which none cleanly does. Honest-claude: preserve gap rather than fabricate a "fix."`,
},
{
  id: 38,
  name: `Entropic Gravity Correction Term`,
  category: `K`,
  category_name: `Modified Theories and Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Verlinde’s emergent gravity with dark matter effects`,
  formula_latex: `\\mathbf{F} = \\mathbf{F}_N\\left[1 + \\alpha\\sqrt{\\frac{a_0}{a}} \\tanh\\left(\\sqrt{\\frac{a}{a_0}}\\right)\\right]`,
  source_part: 'II',
  source_section: `Part-II Category K`,
  known_issues: [
    {
      severity: 'other',
      description: `[R2 gap-spec 2026-05-04] The interpolation function F = F_N[1 + α√(a₀/a) tanh(√(a/a₀))] does NOT reproduce deep-MOND scaling F ∝ √(F_N a₀) in the a → 0 limit; instead it approaches F → F_N(1 + α), i.e., Newtonian scaling. Reformulation requires replacing with one of the canonical MOND interpolation functions: μ(x)=x/(1+x) (simple), μ(x)=x/√(1+x²) (standard), or the Verlinde 2016 emergent-gravity prediction (arXiv:1611.02269) which gives M_apparent = M_baryon · √(M_baryon a_0/(c² R)). All three are non-equivalent and have different empirical fit qualities (cf. Famaey-McGaugh 2012 Living Rev. Relativity 15:10 review). Domain expert needed.`,
      fixable: 'reformulation',
    }
  ],
  references: [`arXiv:1001.0785`, `Verlinde 2011 JHEP 04:029 (arXiv:1001.0785, original entropic gravity)`, `Verlinde 2016 SciPost Phys. 2:016 (arXiv:1611.02269, emergent gravity prediction)`, `Milgrom 1983 Astrophys. J. 270:365 (original MOND)`, `Famaey-McGaugh 2012 Living Rev. Relativity 15:10 (MOND review, arXiv:1112.3960)`, `Bekenstein 2004 Phys. Rev. D 70:083509 (TeVeS, relativistic MOND, arXiv:astro-ph/0403694)`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative. Based on Verlinde (arXiv:1001.0785). Contested; not accepted as mainstream physics. | What would unblock a real fix (2026-05-04 R2 gap-spec): the F_N[1 + α√(a_0/a) tanh(√(a/a_0))] form fails the deep-MOND limit (gives F → F_N(1+α) ~ Newtonian instead of F → √(F_N a_0)). Three candidate replacements: (a) canonical MOND interpolation μ(x) = x/√(1+x²) (Milgrom 1983 ApJ 270:365) recovers √(F_N a_0) by construction in the a << a_0 regime; (b) μ(x) = x/(1+x) "simple" form, also widely used; (c) Verlinde 2016 emergent-gravity prediction (arXiv:1611.02269) giving M_apparent = M_baryon · √(M_baryon a_0/(c²R)), which is conceptually closer to the entropic-gravity origin but is structurally different (mass-correction, not force-correction). Famaey-McGaugh 2012 review (Living Rev. Relativity 15:10, arXiv:1112.3960) catalogues fit qualities; Bekenstein 2004 TeVeS (Phys. Rev. D 70:083509, arXiv:astro-ph/0403694) is the relativistic completion. **Note:** BE-38 shares the MOND scale a_0 with BE-36; if either is reformulated, the other should be sanity-checked for consistency. Domain expert needed.`,
},
{
  id: 39,
  name: `Asymptotic Safety in Quantum Gravity`,
  category: `L`,
  category_name: `Quantum Field Theory Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `UV-complete theory via non-Gaussian fixed point`,
  formula_latex: `\\begin{align}
\\beta_g &= 2g + Ag^2 + Bg^3 - Cg^2\\lambda + \\mathcal{O}(g^4) \\\\
\\beta_\\lambda &= -2\\lambda + D\\lambda^2 - Eg\\lambda + \\mathcal{O}(\\lambda^3)
\\end{align}`,
  source_part: 'II',
  source_section: `Part-II Category L`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The functional renormalization group flow is given at the schematic level only; specific truncation choices (Einstein-Hilbert, f(R), etc.) are required for any concrete computation. The asymptotic safety program (Weinberg 1979; Reuter 1998) is active research, not experimentally confirmed.`,
      fixable: 'spec-edit',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative (active research). Asymptotic safety (Weinberg 1979; Reuter 1998) is an active research program proposing a UV-finite gravity. The functional renormalization group flow equation as written...`,
},
{
  id: 40,
  name: `Composite Higgs Potential`,
  category: `L`,
  category_name: `Quantum Field Theory Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Higgs as pseudo-Goldstone boson`,
  formula_latex: `V(h) = -\\alpha f^2 \\sin^2\\left(\\frac{h}{f}\\right) + \\beta f^4\\left[\\sin^4\\left(\\frac{h}{f}\\right) - \\sin^2\\left(\\frac{h}{f}\\right)\\cos^2\\left(\\frac{h}{f}\\right)\\right]`,
  source_part: 'II',
  source_section: `Part-II Category L`,
  known_issues: [],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Established form, but **dimensionally inhomogeneous as written**. Standard composite Higgs potentials (Kaplan-Georgi 1984; Contino-Grojean-Moretti-Piccinini-Rattazzi 2007) have the structure V(h) ∼ α ...`,
},
{
  id: 41,
  name: `Swampland Distance Conjecture Equation`,
  category: `L`,
  category_name: `Quantum Field Theory Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Constraints on effective field theories from quantum gravity`,
  formula_latex: `m(\\phi) = m_0 \\exp\\left(-\\alpha\\frac{|\\phi-\\phi_0|}{M_P}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category L`,
  known_issues: [],
  references: [`arXiv:hep-th/0509212`],
  dependencies: [],
  dimensional_signature: `[mass]`,
  notes: `see source | status_text: Speculative. Swampland conjecture from string theory (Vafa, arXiv:hep-th/0509212). Active research; not confirmed. | Tier-5 AST encoding landed 2026-05-04 (branch tier-5/wave-1, src/bridges/equations/be-41-swampland.ts) — RHS encoded as m_0 · exp_factor (dimensionless) since the AST has no exp primitive; the exp argument α(φ−φ₀)/M_P is exposed separately as SWAMPLAND_EXP_ARG and verified dimensionless. dimensional_signature [mass] is exactly format(infer(rhs)). Encoding is dimensional only; status remains speculative.`,
},
{
  id: 42,
  name: `Firewall Complement Principle`,
  category: `M`,
  category_name: `Information Paradox Resolutions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Black hole information without firewalls`,
  formula_latex: `|\\psi\\rangle_{\\text{total}} = \\alpha|\\text{smooth}\\rangle_{\\text{horizon}} + \\beta|\\text{firewall}\\rangle_{\\text{horizon}}`,
  source_part: 'II',
  source_section: `Part-II Category M`,
  known_issues: [
    {
      severity: 'undefined-quantity',
      description: `The decomposition |psi> = alpha|smooth> + beta|firewall> is a tautological superposition without physics content unless f(observer, protocol) — which determines |alpha|^2 — is independently specified. As written, the complement principle has no operational predictive content.`,
      fixable: 'spec-edit',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. Firewall paradox is unresolved. The specific "complement principle" formulation here is not a standard result; the decomposition |psi> = a|smooth> + b|firewall> is a tautological s...`,
},
{
  id: 43,
  name: `ER=EPR Wormhole Dynamics`,
  category: `M`,
  category_name: `Information Paradox Resolutions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Entanglement as traversable wormholes`,
  formula_latex: `\\frac{d\\ell_{\\text{wormhole}}}{dt} = -\\gamma S_{\\text{entanglement}} + \\delta \\int T_{\\mu\\nu} u^\\mu u^\\nu dV`,
  source_part: 'II',
  source_section: `Part-II Category M`,
  known_issues: [
    {
      severity: 'dimensional',
      description: `The equation mixes entropy S_entanglement (dimensionless) with a stress-energy integral (dimensionful), and the LHS has units of length per time. Requires careful dimensional analysis to identify the unit-bridging coefficients implied by gamma and delta.`,
      fixable: 'spec-edit',
    },
    {
      severity: 'sign',
      description: `As written, d(ell)/dt = -gamma S_ent + ... has wormhole length decreasing with entanglement, opposite to the standard ER=EPR (Maldacena-Susskind) heuristic where entanglement grows the wormhole. Either gamma < 0 is implicit, or the sign is backwards.`,
      fixable: 'spec-edit',
    }
  ],
  references: [`arXiv:1306.0533`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. ER=EPR (Maldacena-Susskind, arXiv:1306.0533) is a theoretical conjecture, not an established result. The specific wormhole-length dynamics equation here mixes entropy (dimensionles...`,
},
{
  id: 44,
  name: `Soft Hair on Black Holes`,
  category: `M`,
  category_name: `Information Paradox Resolutions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Infinite conservation laws on the horizon`,
  formula_latex: `Q_{\\text{soft}}^{\\pm} = \\int_{\\mathcal{I}^{\\pm}} \\frac{\\partial}{\\partial u} C_{z\\bar{z}} Y^z dz \\wedge d\\bar{z}`,
  source_part: 'II',
  source_section: `Part-II Category M`,
  known_issues: [],
  references: [`arXiv:1601.00921`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative. Soft-hair-on-black-holes proposals (Hawking-Perry-Strominger 2016, arXiv:1601.00921) suggest that BMS supertranslation charges can store information that would otherwise be lost. Influent...`,
},
{
  id: 45,
  name: `Trans-Planckian Censorship Constraint`,
  category: `N`,
  category_name: `Cosmological Puzzles`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Quantum gravity constraints on inflation`,
  formula_latex: `N_e < \\log\\left(\\frac{M_P}{H_{\\text{inf}}}\\right) - \\gamma \\log\\left(\\frac{r}{0.01}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category N`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The extra term -gamma log(r / 0.01) is an extension original to this framework, not part of the Bedroya-Vafa TCC (arXiv:1909.11063); the canonical bound is N_e < ln(M_P / H_inf) (natural log). The added term has no published derivation, and the log base is unspecified.`,
      fixable: 'spec-edit',
    }
  ],
  references: [`arXiv:1909.11063`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative / non-standard. The Trans-Planckian Censorship Conjecture (Bedroya-Vafa 2019, arXiv:1909.11063) bounds inflationary e-foldings via \`N_e < ln(M_P / H_inf)\`. The formula as written here adds...`,
},
{
  id: 46,
  name: `Multiverse Measure Problem`,
  category: `N`,
  category_name: `Cosmological Puzzles`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Probability distribution over universes`,
  formula_latex: `P[O] = \\int d\\mu[g,\\phi] , W[g,\\phi] , \\delta(O - O[g,\\phi])`,
  source_part: 'II',
  source_section: `Part-II Category N`,
  known_issues: [
    {
      severity: 'undefined-quantity',
      description: `The weighting factor W[g, phi] is the multiverse measure, which is itself the unsolved problem (the equation's own subject). Specific measure proposals (scale-factor cutoff, proper-time cutoff, etc.) are untestable without further theoretical development; without a determination of W, the equation has no operational predictive content.`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. The multiverse measure problem is an unsolved fundamental issue in cosmology. Specific measure proposals are untestable without further theoretical development.`,
},
{
  id: 47,
  name: `Big Bang Nucleosynthesis - Dark Sector Coupling`,
  category: `N`,
  category_name: `Cosmological Puzzles`,
  bridges: [`unknown`, `unknown`] as [string, string],
  // Status remains 'speculative'. The base Boltzmann equation (with Hubble
  // drag and species-correct rate) is now canonical Kolb-Turner / Pitrou
  // form, but the dark-sector coupling term is the unverified physics
  // extension that gives this entry its 'speculative' label.
  status: 'speculative',
  context: `Dark matter effects on light element abundances`,
  // 2026-05-01 (R1 audit): added Hubble drag '+3HY' and replaced 'n_b^2'
  // with 'n_p n_n' (species-correct product for the standard p+n→d+γ
  // two-body reaction). See Kolb & Turner §5.2 Eq. 5.13–5.14;
  // Pitrou-Coc-Uzan-Vangioni 2018 Phys. Rep. 754:1 Eq. 2.5.
  formula_latex: `\\frac{dY}{dt} + 3HY = \\langle\\sigma v\\rangle_{\\text{SM}} n_p n_n - \\langle\\sigma v\\rangle_{\\text{dark}} n_\\chi^2 \\epsilon_{\\text{transfer}}`,
  source_part: 'II',
  source_section: `Part-II Category N`,
  // Both R1 audit issues (missing Hubble drag, n_b^2 -> n_p n_n) are
  // resolved.
  known_issues: [],
  references: [
    `Wagoner-Fowler-Hoyle 1967 ApJ 148:3`,
    `Wagoner 1969 ApJS 18:247`,
    `Kolb-Turner The Early Universe 1990 §5.2`,
    `Steigman 2007 ARNPS 57:463`,
    `Pitrou-Coc-Uzan-Vangioni 2018 Phys. Rep. 754:1`,
  ],
  dependencies: [],
  dimensional_signature: `[L^-3 T^-1]`,
  notes: `see source | status_text: Speculative extension on established base. Corrected 2026-05-01 (R1 audit, branch fix/r1-batch-spec-edits): added Hubble dilution drag '+3HY' (Kolb & Turner §5.2 Eq. 5.13–5.14; Pitrou-Coc-Uzan-Vangioni 2018 Eq. 2.5) and replaced 'n_b^2' with 'n_p n_n' species-correct product for the canonical p+n→d+γ two-body reaction (Steigman 2007 ARNPS 57:463 Eq. 27). Status remains 'speculative' — the base equation is now canonical Kolb-Turner form, but the dark-sector coupling 'n_χ² ε_transfer' term is the unverified physics extension. | Tier-5 AST encoding landed 2026-05-04 (branch tier-5/wave-1, src/bridges/equations/be-47-bbn-dark-sector.ts) — full ODE encoded with each term (dY/dt, 3HY, SM source, dark sink) exposed as separate ExprNodes; per-term dim verified [L^-3 T^-1] and full LHS=RHS balance validated.`,
},
{
  id: 48,
  name: `Objective Collapse Equation (GRW extension)`,
  category: `O`,
  category_name: `Quantum Foundations`,
  bridges: [`unknown`, `unknown`] as [string, string],
  // Status remains 'established' — this is a typesetting/transcription
  // correction to a canonical formula (the 1986 GRW master equation), not a
  // reformulation. See the "Corrected on 2026-05-04 (R0 audit)" block in
  // docs/specification/Part-II.md.
  status: 'established',
  context: `Spontaneous wavefunction collapse`,
  // 2026-05-04 (R0 audit): added the missing (πσ²)^{-3/4} prefactor to L_x so
  // the localization operator is the canonical 3D Gaussian-resolved position
  // projector and the master equation closes dimensionally to [T^-1]. Also
  // escaped the anticommutator braces (\\{...\\}) that were unbalanced.
  formula_latex: `\\frac{d\\rho}{dt} = -\\frac{i}{\\hbar}[H,\\rho] + \\lambda \\int d^3x \\left[L_x \\rho L_x^\\dagger - \\frac{1}{2}\\{L_x^\\dagger L_x, \\rho\\}\\right], \\quad L_x = (\\pi\\sigma^2)^{-3/4}\\exp\\left[-\\frac{(\\hat{\\mathbf{r}}-\\mathbf{x})^2}{2\\sigma^2}\\right]`,
  source_part: 'II',
  source_section: `Part-II Category O`,
  // The "missing prefactor" R0 issue is resolved. No residual issues found
  // during the R0 audit pass: the sum-over-particles index is implicit (the
  // single-particle form shown is the standard convention; multi-particle
  // generalization Σ_n L_x^(n) per Bassi-Ghirardi 2003 §2.1 is notational),
  // and λ now carries unambiguous units [T^-1] once the d³x integral is
  // dimensionless.
  known_issues: [],
  references: [],
  dependencies: [],
  // The GRW master equation has rate-form dimension: dρ/dt has units [T^-1]
  // (ρ is dimensionless, t in seconds). Both terms on the RHS — the
  // (i/ℏ)[H,ρ] commutator and the λ ∫ d³x [...] localization term — reduce
  // to [T^-1] once the (πσ²)^{-3/4} prefactor makes ∫ d³x L_x† L_x
  // dimensionless and λ carries [T^-1]. Encoded as the canonical Lindblad
  // rate signature.
  dimensional_signature: `[frequency]`,
  notes: `see source | status_text: Established (within GRW class; corrected 2026-05-04 R0 audit — added canonical (πσ²)^{-3/4} prefactor to L_x and updated λ from 1e-17 to 1e-16 s^-1 to match the original 1986 GRW value). Citations: Ghirardi-Rimini-Weber 1986 Phys. Rev. D 34:470; Bassi-Ghirardi 2003 Phys. Rep. 379:257 review.`,
},
{
  id: 49,
  name: `Quantum Darwinism Redundancy`,
  category: `O`,
  category_name: `Quantum Foundations`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Classical reality from quantum substrate`,
  formula_latex: `I(S:F_k) = I(S:E) - \\mathcal{O}(k^{-\\alpha})`,
  source_part: 'II',
  source_section: `Part-II Category O`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The specific algebraic decay form I(S:F_k) = I(S:E) - O(k^-alpha) is a phenomenological ansatz not derived from the Zurek formalism (Quantum Darwinism, Nat. Phys. 5:181, 2009); the exponent alpha is a free parameter.`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative extension. Quantum Darwinism (Zurek 2009, Nat. Phys. 5:181) is established as an interpretational framework. The specific algebraic decay form \`I(S:F_k) = I(S:E) − O(k^{-α})\` is a phenomen...`,
},
{
  id: 50,
  name: `Retrocausal Quantum Field Theory`,
  category: `O`,
  category_name: `Quantum Foundations`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Time-symmetric formulation solving measurement problem`,
  formula_latex: `S = \\int d^4x \\left[\\mathcal{L}*{\\text{forward}}(\\phi*+) + \\mathcal{L}*{\\text{backward}}(\\phi*-) + \\lambda\\phi_+\\phi_-\\delta^4(x-x_m)\\right]`,
  source_part: 'II',
  source_section: `Part-II Category O`,
  known_issues: [
    {
      severity: 'other',
      description: `Attribution updated in Wave I.A C5 (2026-05-05): the Lagrangian form L_forward(φ_+) + L_backward(φ_-) is the action structure of Wheeler-Feynman absorber theory (Rev. Mod. Phys. 17:157, 1945), not Cramer's transactional interpretation (which is an interpretational framework over standard QM/QFT, not a different action) or the Aharonov-Vaidman two-state vector formalism (a retrodictive measurement formalism, distinct from a retrocausal QFT). Wheeler-Feynman is now the primary reference; Cramer 1986 is retained as a secondary modern reference because the prose lineage from Wheeler-Feynman → Cramer is the standard citation chain. Aharonov-Vaidman removed: it is a separate framework not load-bearing for the action above. The specific spacetime-point interaction term λ φ_+ φ_- δ^4(x - x_m) coupling forward and backward sectors at measurement events is original to this framework — equation remains marked as a novel proposal in the highly-speculative status.`,
      fixable: 'spec-edit',
    }
  ],
  references: [
    `Wheeler & Feynman 1945 *Rev. Mod. Phys.* 17:157 (Interaction with the Absorber as the Mechanism of Radiation; canonical time-symmetric absorber theory — primary reference for the L_forward/L_backward action structure)`,
    `Wheeler & Feynman 1949 *Rev. Mod. Phys.* 21:425 (Classical Electrodynamics in Terms of Direct Interparticle Action; companion paper)`,
    `Cramer 1986 *Rev. Mod. Phys.* 58:647 (Transactional interpretation of QM; modern lineage from Wheeler-Feynman — secondary reference)`,
  ],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. Attribution updated in Wave I.A C5 (2026-05-05): primary reference is Wheeler-Feynman 1945 absorber theory (the L_forward/L_backward action structure); Cramer 1986 retained as secondary modern reference; Aharonov-Vaidman removed (separate two-state retrodictive-measurement formalism, not load-bearing for this action). The λ φ_+ φ_- δ^4(x - x_m) coupling term is original to this framework.`,
}

];

export default BRIDGE_EQUATIONS;
