/**
 * Universal Physics Tensor — Bridge Equation Index
 *
 * Machine-readable catalog of all 40 bridge equations from the UPT specification
 * (Parts I-VI). Each entry preserves the spec's stated status, known issues,
 * references, and dependencies on other bridge equations.
 *
 * Generated by scripts/extract.py (~/.claude/playground/upt_bridge_extraction/);
 * see data/bridges/README.md for regen instructions.
 *
 * Source-of-truth files: docs/specification/Part-{I-VI}.md
 *
 * Honest-claude: fields not explicitly stated in the spec are null (not guessed).
 * - dimensional_signature is null for all entries (Tier 4 work — see README).
 * - known_issues are extracted ONLY from explicit issue-markers in the spec
 *   ("**Known issue:**", "**Additional known issue:**", "**Bound violation:**",
 *   etc.). Equations whose Status text discusses problems narratively without
 *   such a marker have known_issues: [] — see status_text appended in `notes`.
 *
 * @module bridges
 */

export type BridgeEquationStatus =
  | 'established'
  | 'speculative'
  | 'highly-speculative'
  | 'invalid';

export type BridgeIssueSeverity =
  | 'self-refuting'
  | 'dimensional'
  | 'index-structure'
  | 'sign'
  | 'undefined-quantity'
  | 'phenomenological-ansatz'
  | 'other';

export type BridgeIssueFixable =
  | 'spec-edit'
  | 'reformulation'
  | 'unfixable-must-mark-invalid'
  | 'unknown';

export interface KnownIssue {
  severity: BridgeIssueSeverity;
  /** Verbatim issue text from the spec (may be paraphrased; cf. source). */
  description: string;
  fixable: BridgeIssueFixable;
}

export interface BridgeEquationEntry {
  /** Equation number, 11-50. */
  id: number;
  /** Verbatim heading text from the spec. */
  name: string;
  /** Category letter (A-O). */
  category: string;
  /** Category display name, e.g. "Quantum-Classical Bridges". */
  category_name: string;
  /** Two-element tuple naming the bridged regimes. */
  bridges: [string, string];
  status: BridgeEquationStatus;
  /** 1-2 sentence summary from the spec's Context bullet. */
  context: string;
  /** Primary equation as LaTeX, decoded from upmath SVG src. */
  formula_latex: string | null;
  source_part: 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI';
  source_section: string;
  known_issues: KnownIssue[];
  /** arXiv IDs and other identifiers as cited in the spec. */
  references: string[];
  /** IDs of other bridge equations explicitly referenced in this entry. */
  dependencies: number[];
  /** SI dimensional signature (null = not yet analyzed; Tier 4 work). */
  dimensional_signature: string | null;
  /** Free-form notes (origin Status text appended for traceability). */
  notes: string;
}

export const BRIDGE_EQUATIONS: BridgeEquationEntry[] = [
{
  id: 11,
  name: `Decoherence Master Equation`,
  category: `A`,
  category_name: `Quantum-Classical Bridges`,
  bridges: [`quantum`, `classical`] as [string, string],
  status: 'established',
  context: `Explains how quantum superpositions collapse to classical states via environmental interaction`,
  formula_latex: `\\frac{\\partial \\rho}{\\partial t} = -\\frac{i}{\\hbar}[H, \\rho] + \\sum_k \\gamma_k(\\lambda) \\left[ L_k \\rho L_k^\\dagger - \\frac{1}{2}\\{L_k^\\dagger L_k, \\rho\\} \\right], \\quad \\gamma_k(\\lambda) = \\gamma_0 \\left(\\frac{\\lambda}{\\lambda_0}\\right)^2`,
  source_part: 'I',
  source_section: `Part-I Category A`,
  known_issues: [],
  references: [
    `Lindblad 1976, Commun. Math. Phys. 48:119`,
    `Gorini-Kossakowski-Sudarshan 1976, J. Math. Phys. 17:821`,
    `Caldeira-Leggett 1983, Physica A 121, 587`,
    `Caldeira-Leggett 1985, Phys. Rev. A 31, 1059`,
    `Breuer & Petruccione 2002, The Theory of Open Quantum Systems (OUP), §3.6, §4.5`,
  ],
  dependencies: [],
  dimensional_signature: `[frequency]`,
  notes: `see source | status_text: Established (Lindblad form). Auxiliary coupling-dependent rate corrected 2026-05-04 (R0 audit, branch fix/be-11-decoherence-coupling) from the broken Arrhenius-in-coupling form γ_k(T,λ) = γ_0 exp(-λ/λ_thermal) — which was exponentially *decreasing* in coupling, physically backwards — to the Caldeira-Leggett weak-coupling form γ_k(λ) = γ_0 (λ/λ_0)². The Lindblad master equation itself is unchanged and remains established literature.`,
},
{
  id: 12,
  name: `Mesoscopic Coherence Length Equation`,
  category: `A`,
  category_name: `Quantum-Classical Bridges`,
  bridges: [`quantum`, `classical`] as [string, string],
  status: 'speculative',
  context: `Determines the scale at which quantum effects vanish`,
  formula_latex: `\\xi_{\\text{coh}}(T,N) = \\frac{\\xi_0}{\\sqrt{1 + \\frac{N}{N_c} + \\left(\\frac{T}{T_c}\\right)^\\nu}}`,
  source_part: 'I',
  source_section: `Part-I Category A`,
  known_issues: [
    {
      severity: 'undefined-quantity',
      // Re-tiered R1 -> R2 on 2026-05-01 (branch fix/r1-batch-spec-edits).
      // The audit's 'spec-edit' classification was optimistic: the cube
      // exponent N_c = (E_int/(k_B T))^3, the undefined ω_decoherence, and
      // the undefined ξ_0 cannot be repaired by transcription correction
      // alone -- there is no published interpolation formula of this form
      // (BE-12 is novel to this framework), so identifying ω_decoherence
      // with ω_c from BE-11 or with another scale, and motivating the cube,
      // requires inventing physics rather than citing literature.
      description: `[R1->R2 re-tier 2026-05-01] the critical particle number \`N_c = (E_int/(k_B T))^3\` uses a cube exponent that is not motivated by any specific decoherence model (Zurek, Caldeira-Leggett, or BEC variational). Treat the cube as a phenomenological ansatz. **Additional known issue:** \`T_c = hbar * omega_decoherence / k_B\` uses \`omega_decoherence\` as an undefined / self-referential quantity -- it is introduced here without independent definition, and it is unclear whether this equals the bath cutoff frequency \`omega_c\` from Bridge Equation 11 or a distinct scale. \`xi_0\` is also introduced without definition. A corrected formulation should identify these with previously-defined physical scales.`,
      fixable: 'reformulation',
    }
  ],
  references: [],
  dependencies: [11],
  dimensional_signature: null,
  notes: `[R1->R2 re-tier 2026-05-01, branch fix/r1-batch-spec-edits] The R1 audit classified BE-12 as 'spec-edit' fixable, but on closer reading the issue requires inventing physics: the formula is novel to this framework (no literature interpolation of this form exists), so identifying ω_decoherence with ω_c (BE-11 dependency) or any other named scale, motivating the cube exponent, and defining ξ_0 are reformulation tasks, not transcription fixes. Per honest-claude, preserved as R2 candidate. status_text: Phenomenological / Novel conjecture. A coherence length interpolation formula of this form has not appeared in the literature; individual limits (small-N, low-T) match BEC-type coherence length scaling, but the combined N- and T-dependent form is original.`,
},
{
  id: 13,
  name: `Landauer-Wheeler Information-Geometry Equation`,
  category: `B`,
  category_name: `Information-Physical Bridges`,
  bridges: [`information`, `physical`] as [string, string],
  status: 'highly-speculative',
  context: `Proposes a conjectural link from information erasure to spacetime curvature`,
  formula_latex: `R_{\\mu\\nu} - \\frac{1}{2}Rg_{\\mu\\nu} = \\frac{8\\pi G}{c^4}\\left[T_{\\mu\\nu}^{\\text{matter}} + k_B T \\ln(2) I_{\\mu\\nu}\\right]`,
  source_part: 'I',
  source_section: `Part-I Category B`,
  known_issues: [
    {
      severity: 'dimensional',
      description: `The dimensional analysis of the information stress-energy tensor <img src="https://i.upmath.me/svg/I_%7B%5Cmu%5Cnu%7D" alt="I_{\\mu\\nu}" /> as currently defined does not close; a future revision should either redefine <img src="https://i.upmath.me/svg/I_%7B%5Cmu%5Cnu%7D" alt="I_{\\mu\\nu}" /> directly in stress-energy dimensions or adjust the pre-factors.`,
      fixable: 'reformulation',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. The existence of an information-geometric back-reaction on spacetime at the level proposed here is not an established result. Landauer's original principle (<img src="https://i.upm...`,
},
{
  id: 14,
  name: `Quantum Error Correction Holographic Mapping`,
  category: `B`,
  category_name: `Information-Physical Bridges`,
  bridges: [`information`, `physical`] as [string, string],
  status: 'established',
  context: `How bulk physics emerges from boundary quantum information`,
  formula_latex: `|\\psi_{\\text{bulk}}\\rangle = U_{\\text{HQECC}} \\sum_i \\alpha_i |\\text{code}_i\\rangle_{\\text{boundary}}`,
  source_part: 'I',
  source_section: `Part-I Category B`,
  known_issues: [],
  references: [`arXiv:hep-th/0603001`],
  dependencies: [],
  dimensional_signature: `[entropy]`,
  notes: `see source | status_text: Established (within AdS/CFT). The Ryu-Takayanagi formula S = Area(gamma)/(4 G_N hbar) is a well-established result in AdS/CFT holography (Ryu and Takayanagi 2006, arXiv:hep-th/0603001). Extensions to ...`,
},
{
  id: 15,
  name: `Universal Emergence Equation`,
  category: `C`,
  category_name: `Emergence and Complexity`,
  bridges: [`microscale`, `emergent`] as [string, string],
  status: 'speculative',
  context: `How macroscopic laws emerge from microscopic interactions`,
  formula_latex: `\\frac{\\partial O_{\\text{macro}}}{\\partial t} = \\mathcal{F}[\\{O_{\\text{micro}}\\}] + \\eta\\nabla^2 O_{\\text{macro}} + \\zeta\\left(\\frac{\\partial^2 S}{\\partial O^2}\\right)`,
  source_part: 'I',
  source_section: `Part-I Category C`,
  known_issues: [
    {
      severity: 'dimensional',
      description: `(1) the RG beta function \`β(k)\` is dimensionless (logarithmic derivative of a coupling), making the functional \`F[{O_micro}]\` not directly comparable with \`∂O_macro/∂t\`; (2) the term \`ζ(∂²S/∂O²)\` has dimensions depending on the unit of O and on whether S is physical entropy (J/K) or information (bits/nats), with ζ then needing a specific unit assignment to make the equation dimensionally homogeneous. As written the equation is schematic, not operational.`,
      fixable: 'unknown',
    },
    {
      severity: 'phenomenological-ansatz',
      description: `(1) the RG beta function \`β(k)\` is dimensionless (logarithmic derivative of a coupling), making the functional \`F[{O_micro}]\` not directly comparable with \`∂O_macro/∂t\`; (2) the term \`ζ(∂²S/∂O²)\` has dimensions depending on the unit of O and on whether S is physical entropy (J/K) or information (bits/nats), with ζ then needing a specific unit assignment to make the equation dimensionally homogeneous. As written the equation is schematic, not operational.`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative / schematic. This is a conjectural emergence equation combining an RG flow functional, a diffusive term, and a second-derivative entropy term. **Known issues:** (1) the RG beta function \`β...`,
},
{
  id: 16,
  name: `Complexity-Entropy Production Relation`,
  category: `C`,
  category_name: `Emergence and Complexity`,
  bridges: [`microscale`, `emergent`] as [string, string],
  status: 'invalid',
  context: `Proposes a conjectural link from computational complexity to thermodynamic entropy production`,
  formula_latex: `\\frac{dS}{dt} = k_B \\cdot \\mathcal{C}(\\rho) \\cdot \\frac{\\partial I}{\\partial t}`,
  source_part: 'I',
  source_section: `Part-I Category C`,
  known_issues: [
    {
      severity: 'self-refuting',
      description: `(1) The circuit complexity <img src="https://i.upmath.me/svg/%5Cmathcal%7BC%7D(%5Crho)" alt="\\mathcal{C}(\\rho)" /> is not independently defined, making the equation effectively a definition of complexity in terms of the entropy-to-information ratio rather than a falsifiable physical relation. A substantive version would require an independent operational definition of <img src="https://i.upmath.me/svg/%5Cmathcal%7BC%7D(%5Crho)" alt="\\mathcal{C}(\\rho)" /> (e.g., gate count in a specific universal gate set) and a monotonicity constraint to avoid second-law violations. (2) The quantity labeled <img src="https://i.upmath.me/svg/I" alt="I" /> below, defined as <img src="https://i.upmath.me/svg/%5Ctext%7BTr%7D(%5Crho%20%5Clog%20%5Crho)" alt="\\text{Tr}(\\rho \\log \\rho)" />, is the **negative** of the von Neumann entropy (which is <img src="https://i.upmath.me/svg/-%5Ctext%7BTr%7D(%5Crho%20%5Clog%20%5Crho)" alt="-\\text{Tr}(\\rho \\log \\rho)" />); the sign convention in the equation as written should be checked in a future revision. **Additional Second-Law problem:** combining I = Tr(rho log rho) = -S_vN with dS/dt = k_B * C(rho) * dI/dt gives dS/dt = -k_B * C(rho) * dS_vN/dt. If S and S_vN are taken to be the same entropy, this forces dS/dt (1 + k_B C(rho)) = 0, i.e., dS/dt = 0 for any C(rho) > -1/k_B -- the equation algebraically forbids entropy change, violating the Second Law. The formula is therefore not merely imprecise; it is self-refuting unless S and S_vN are distinct quantities...`,
      fixable: 'unfixable-must-mark-invalid',
    },
    {
      severity: 'sign',
      description: `(1) The circuit complexity <img src="https://i.upmath.me/svg/%5Cmathcal%7BC%7D(%5Crho)" alt="\\mathcal{C}(\\rho)" /> is not independently defined, making the equation effectively a definition of complexity in terms of the entropy-to-information ratio rather than a falsifiable physical relation. A substantive version would require an independent operational definition of <img src="https://i.upmath.me/svg/%5Cmathcal%7BC%7D(%5Crho)" alt="\\mathcal{C}(\\rho)" /> (e.g., gate count in a specific universal gate set) and a monotonicity constraint to avoid second-law violations. (2) The quantity labeled <img src="https://i.upmath.me/svg/I" alt="I" /> below, defined as <img src="https://i.upmath.me/svg/%5Ctext%7BTr%7D(%5Crho%20%5Clog%20%5Crho)" alt="\\text{Tr}(\\rho \\log \\rho)" />, is the **negative** of the von Neumann entropy (which is <img src="https://i.upmath.me/svg/-%5Ctext%7BTr%7D(%5Crho%20%5Clog%20%5Crho)" alt="-\\text{Tr}(\\rho \\log \\rho)" />); the sign convention in the equation as written should be checked in a future revision. **Additional Second-Law problem:** combining I = Tr(rho log rho) = -S_vN with dS/dt = k_B * C(rho) * dI/dt gives dS/dt = -k_B * C(rho) * dS_vN/dt. If S and S_vN are taken to be the same entropy, this forces dS/dt (1 + k_B C(rho)) = 0, i.e., dS/dt = 0 for any C(rho) > -1/k_B -- the equation algebraically forbids entropy change, violating the Second Law. The formula is therefore not merely imprecise; it is self-refuting unless S and S_vN are distinct quantities...`,
      fixable: 'unfixable-must-mark-invalid',
    },
    {
      severity: 'undefined-quantity',
      description: `(1) The circuit complexity <img src="https://i.upmath.me/svg/%5Cmathcal%7BC%7D(%5Crho)" alt="\\mathcal{C}(\\rho)" /> is not independently defined, making the equation effectively a definition of complexity in terms of the entropy-to-information ratio rather than a falsifiable physical relation. A substantive version would require an independent operational definition of <img src="https://i.upmath.me/svg/%5Cmathcal%7BC%7D(%5Crho)" alt="\\mathcal{C}(\\rho)" /> (e.g., gate count in a specific universal gate set) and a monotonicity constraint to avoid second-law violations. (2) The quantity labeled <img src="https://i.upmath.me/svg/I" alt="I" /> below, defined as <img src="https://i.upmath.me/svg/%5Ctext%7BTr%7D(%5Crho%20%5Clog%20%5Crho)" alt="\\text{Tr}(\\rho \\log \\rho)" />, is the **negative** of the von Neumann entropy (which is <img src="https://i.upmath.me/svg/-%5Ctext%7BTr%7D(%5Crho%20%5Clog%20%5Crho)" alt="-\\text{Tr}(\\rho \\log \\rho)" />); the sign convention in the equation as written should be checked in a future revision. **Additional Second-Law problem:** combining I = Tr(rho log rho) = -S_vN with dS/dt = k_B * C(rho) * dI/dt gives dS/dt = -k_B * C(rho) * dS_vN/dt. If S and S_vN are taken to be the same entropy, this forces dS/dt (1 + k_B C(rho)) = 0, i.e., dS/dt = 0 for any C(rho) > -1/k_B -- the equation algebraically forbids entropy change, violating the Second Law. The formula is therefore not merely imprecise; it is self-refuting unless S and S_vN are distinct quantities...`,
      fixable: 'unfixable-must-mark-invalid',
    }
  ],
  references: [`arXiv:1402.5674`, `arXiv:1509.07876`],
  dependencies: [],
  dimensional_signature: null,
  notes: `INVALID per disposition decision 2026-05-01 (Tier 3 audit, Bridge-Remediation-Plan.md R3): the equation is algebraically self-refuting (combining I = Tr(rho log rho) = -S_vN with the master relation forces dS/dt = 0 for any C(rho) > -1/k_B), and circuit complexity C(rho) is not independently defined. Marking invalid keeps the record visible, flags the problem, and preserves the option to reformulate later if a clean S vs. S_vN distinction emerges. | status_text (preserved): Speculative. This is loosely inspired by the black-hole complexity program — Susskind's "complexity = volume" conjecture (arXiv:1402.5674) and the later "complexity = action" conjecture by Brown, Robe...`,
},
{
  id: 17,
  name: `Electromagnetic-Gravitational Unification via Torsion`,
  category: `D`,
  category_name: `Field Unification Bridges`,
  bridges: [`field-A`, `field-B`] as [string, string],
  status: 'speculative',
  context: `Proposed Einstein-Cartan theory extension`,
  formula_latex: `R_{\\mu\\nu}^{\\lambda\\rho} = \\mathring{R}_{\\mu\\nu}^{\\lambda\\rho} + K_{\\mu\\nu}^{\\lambda\\rho} + \\alpha\\left(F_{\\mu\\nu} F^{\\lambda\\rho} - \\frac{1}{4} g_{\\mu\\nu} F_{\\alpha\\beta} F^{\\alpha\\beta}\\right)`,
  source_part: 'I',
  source_section: `Part-I Category D`,
  known_issues: [
    // Re-tiered R1 -> R2 on 2026-05-01 (branch fix/r1-batch-spec-edits).
    // The audit's 'spec-edit' classification was optimistic on three
    // interlocking issues that together require a from-scratch
    // reformulation of the EM-curvature coupling, not transcription:
    //  - The Maxwell-stress-energy term `(1/4) g_{μν} F²` has 2 free
    //    indices while the LHS Riemann tensor has 4; fixing this needs a
    //    new tensorial structure (e.g., antisymmetrized δ-products), not
    //    a typo correction.
    //  - `l_EM = sqrt(ℏc/e²)` is dimensionless in Gaussian units (sqrt of
    //    inverse fine-structure ≈ 11.7) and not-a-length in SI; choosing
    //    the 'classical electron radius' as a replacement is a research
    //    decision, not a transcription fix.
    //  - The standard Einstein-Cartan contorsion is rank-3 `K^ρ_{μν}`,
    //    antisymmetric in the lower indices from the torsion definition;
    //    rewriting the equation with the correct rank-3 contorsion changes
    //    the structure of the gravitational sector entirely.
    {
      severity: 'index-structure',
      description: `[R1->R2 re-tier 2026-05-01] The equation has an index-structure mismatch: the term '(1/4) g_{μν} F_{αβ} F^{αβ}' has only two free indices (μ,ν) while the LHS R_{μν}^{λρ} has four. The standard Maxwell stress-energy tensor T_{μν}^{(EM)} has 2 indices, so reproducing it on the RHS requires a different tensorial structure (e.g., antisymmetrized δ-products promoting it to rank-4). A correct formulation must invent or cite a specific 4-index structure, not patch the existing 2-index term -- this is reformulation, not transcription.`,
      fixable: 'reformulation',
    },
    {
      severity: 'dimensional',
      description: `[R1->R2 re-tier 2026-05-01] The coupling 'alpha = l_P^2 / l_{EM}^2' uses 'l_{EM} = sqrt(ℏc/e²)' which is not a length in SI (units J·m/C², whose square root is not meters). In Gaussian units the quantity is dimensionless (sqrt of inverse fine-structure ≈ 11.7). Choosing a replacement -- classical electron radius r_e, Compton wavelength, Bohr radius, or Planck length -- is a *physics decision* with different physical interpretations, not a transcription fix.`,
      fixable: 'reformulation',
    },
    {
      severity: 'undefined-quantity',
      description: `[R1->R2 re-tier 2026-05-01] The contorsion tensor is written 'K_{μν}^{λρ}' (rank-4) but the standard Einstein-Cartan contorsion is rank-3 'K^ρ_{μν}' (antisymmetric in the lower indices, from torsion T^ρ_{μν} = K^ρ_{μν} − K^ρ_{νμ}). Rewriting with the correct rank-3 K changes the structure of the gravitational sector and requires rederiving the EM-curvature coupling self-consistently -- a reformulation task.`,
      fixable: 'reformulation',
    }
  ],
  references: [`Hehl-vonderHeyde-Kerlick-Nester 1976 Rev. Mod. Phys. 48:393`],
  dependencies: [],
  dimensional_signature: null,
  notes: `[R1->R2 re-tier 2026-05-01, branch fix/r1-batch-spec-edits] The R1 audit classified BE-17 as 'spec-edit' fixable across three coupled issues. On closer reading, the issues require reformulation: (a) fixing the 4-vs-2-index mismatch needs a new tensorial structure (antisymmetrized δ-products or a different RHS), (b) replacing 'l_{EM}' with a physical length (classical electron radius vs. Compton wavelength vs. Planck length) is a physics decision, (c) rewriting the rank-4 contorsion as rank-3 changes the gravitational sector. Per honest-claude, preserved as R2 candidate. status_text: Speculative. Einstein-Cartan theory itself is well-established (Hehl et al., Rev. Mod. Phys. 48:393 (1976)), but the specific form of EM coupling to curvature proposed here is not standard.`,
},
{
  id: 18,
  name: `Non-Abelian Dark Matter Gauge Theory`,
  category: `D`,
  category_name: `Field Unification Bridges`,
  bridges: [`field-A`, `field-B`] as [string, string],
  // Status remains 'speculative' — the form correction (added |D_μ Φ|²
  // kinetic term, flipped V sign) is canonical Peskin-Schroeder §20.1
  // textbook physics, but the existence of this hidden non-Abelian sector is
  // the speculative content and remains unverified.
  status: 'speculative',
  context: `Dark matter as gauge bosons of hidden symmetry`,
  // 2026-05-01 (R1 audit): added missing |D_μ Φ|² kinetic term so Φ is
  // dynamical, and flipped V sign to standard L = T − V convention.
  formula_latex: `\\mathcal{L}_{\\text{dark}} = -\\frac{1}{4} G^a_{\\mu\\nu} G^{a\\mu\\nu} + |D_\\mu \\Phi|^2 + \\bar{\\psi}(i\\gamma^\\mu D_\\mu - m_\\psi)\\psi - V(|\\Phi|)`,
  source_part: 'I',
  source_section: `Part-I Category D`,
  // The R1 audit's "missing kinetic term" issue is resolved by the spec-edit.
  known_issues: [],
  references: [`arXiv:1311.0029`, `arXiv:2005.01515`, `Peskin-Schroeder 1995 §20.1`],
  dependencies: [],
  dimensional_signature: `[energy]^4`,
  notes: `see source | status_text: Speculative. Corrected 2026-05-01 (R1 audit, branch fix/r1-batch-spec-edits): added missing |D_μ Φ|² kinetic term and flipped V sign to standard L = T − V convention. Citation: Peskin-Schroeder 1995 §20.1 (canonical non-Abelian + complex-scalar SSB Lagrangian template). Status remains 'speculative' — the form is now canonical textbook, but the existence of this hidden non-Abelian dark sector is the speculative content.`,
},
{
  id: 19,
  name: `Quantum Bounce Equation`,
  category: `E`,
  category_name: `Cosmological-Quantum Bridges`,
  bridges: [`quantum`, `cosmological`] as [string, string],
  status: 'speculative',
  context: `Loop quantum cosmology prediction`,
  formula_latex: `H^2 = \\frac{8\\pi G}{3} \\rho\\left(1 - \\frac{\\rho}{\\rho_{\\text{crit}}}\\right) + \\frac{\\Lambda}{3}`,
  source_part: 'I',
  source_section: `Part-I Category E`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The critical density rho_crit = 3 c^2 / (8 pi G l_P^2) is a dimensional estimate that differs from the canonical Ashtekar-Singh LQC value rho_crit ~ 0.41 rho_Planck (arXiv:1108.0893) by a factor of ~3-4 because it omits the Barbero-Immirzi parameter gamma (~0.2375) whose cube enters the standard coefficient.`,
      fixable: 'spec-edit',
    }
  ],
  references: [`arXiv:1108.0893`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative (LQC-inspired). Loop Quantum Cosmology bounce equations (Ashtekar, Bojowald) modify the Friedmann equation via a rho/rho_crit term. The formula as written rho_crit = 3c^2/(8 pi G l_P^2) ap...`,
},
{
  id: 20,
  name: `Vacuum Fluctuation Dark Energy Coupling`,
  category: `E`,
  category_name: `Cosmological-Quantum Bridges`,
  bridges: [`quantum`, `cosmological`] as [string, string],
  status: 'speculative',
  context: `Zero-point energy contribution to cosmic acceleration`,
  formula_latex: `\\rho_{\\text{vac}} = \\rho_0 + \\int d^3k \\frac{\\hbar\\omega_k}{2} \\cdot \\zeta\\left(\\frac{k}{k_{\\text{UV}}}\\right)`,
  source_part: 'I',
  source_section: `Part-I Category E`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `Naive evaluation of this integral produces the cosmological-constant problem: the result is ~10^120 times the observed dark-energy density. The cutoff zeta(k/k_UV) phenomenologically regularizes this but does not solve the problem; the equation labels where the problem sits in the catalog rather than proposing a resolution.`,
      fixable: 'unknown',
    }
  ],
  references: [`arXiv:1402.5674`, `arXiv:1509.07876`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative / open problem. The integral of (hbar omega_k / 2) zeta(k/k_UV) of vacuum zero-point energy with a UV cutoff is **the standard expression whose naive evaluation produces the famous cosmolo...`,
},
{
  id: 21,
  name: `AdS/CMT Correspondence Equation`,
  category: `F`,
  category_name: `Condensed Matter - High Energy Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Holographic duality between strongly correlated electrons and gravitational systems`,
  formula_latex: `G_R(\\omega,k) = -i \\lim_{r \\to \\infty} r^{2\\Delta-d} \\left(\\frac{g^{rr}}{\\sqrt{g^{tt}}}\\right) \\frac{\\partial_r \\phi(r,\\omega,k)}{\\phi_0(\\omega,k)}`,
  source_part: 'II',
  source_section: `Part-II Category F`,
  known_issues: [],
  references: [`arXiv:hep-th/0205052`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Established. The holographic dictionary for retarded Green's functions in AdS/CMT (anti-de Sitter / condensed matter correspondence) is a well-understood result (Son and Starinets 2002, arXiv:hep-th/0...`,
},
{
  id: 22,
  name: `Topological Entanglement Entropy - Quantum Gravity Link`,
  category: `F`,
  category_name: `Condensed Matter - High Energy Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Connects topological phases to quantum error correction in gravity`,
  formula_latex: `S_{\\text{topo}} = -\\gamma + \\alpha \\log\\left(\\frac{\\xi}{a}\\right) + \\beta\\left(\\frac{T}{T_c}\\right)^\\nu \\log\\left(\\frac{A_{\\text{boundary}}}{l_P^2}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category F`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The finite-temperature correction term beta (T/T_c)^nu is phenomenological and lacks derivation; topological order (and hence gamma) is destroyed above the topological gap, so a finite-T extension needs justification.`,
      fixable: 'spec-edit',
    },
    {
      severity: 'index-structure',
      description: `The log(A_boundary / l_P^2) factor reintroduces area-law scaling into a quantity (-gamma) that is by definition the area-law-subtracted constant part. A physically correct finite-T extension would make gamma itself T-dependent, e.g., -gamma(T) = -gamma_0 - beta (T/T_c)^nu, without the log(A) factor.`,
      fixable: 'spec-edit',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative extension. The T=0 Kitaev-Preskill topological entanglement entropy is established; the finite-temperature and area-scaling terms added here are novel extensions not found in the literatur...`,
},
{
  id: 23,
  name: `Strange Metal - Black Hole Duality`,
  category: `F`,
  category_name: `Condensed Matter - High Energy Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  // Downgraded 2026-05-01 from 'established' to 'speculative' (R0 audit fix).
  // Rationale: the third term of the spec formula is mathematically vacuous
  // under the standard τ_P = ℏ/(k_B T) substitution, and the audit-suggested
  // replacement form has the same defect. See known_issues[0] below and the
  // preserved Known Issue block in docs/specification/Part-II.md.
  status: 'speculative',
  context: `Linear resistivity in strange metals matches black hole dynamics`,
  formula_latex: `\\rho(T) = \\rho_0 + AT + B\\sqrt{\\frac{\\hbar}{k_B T \\tau_P}}`,
  source_part: 'II',
  source_section: `Part-II Category F`,
  known_issues: [
    {
      severity: 'self-refuting',
      description: `Substituting τ_P = ℏ/(k_B T) into √(ℏ/(k_B T τ_P)) yields √1 = 1 identically, collapsing the third term to the constant B. The Tier-3 audit (Bridge-Remediation-Plan.md) recommended replacing with √(k_B T · τ_P / ℏ), but that form ALSO reduces to √1 = 1 under the same substitution — algebraically inevitable, since τ_P · k_B T = ℏ constrains every product/quotient built from those two factors alone. A non-vacuous form requires introducing a second independent timescale or energy (e.g. τ_el, SYK J, E_F, or the MSS Lyapunov bound λ_L = 2π k_B T/ℏ). Marking 'reformulation' rather than 'spec-edit': selecting the right scale is a research/domain-expert decision, not a transcription fix. Status downgraded to 'speculative' on 2026-05-01 pending expert input.`,
      fixable: 'reformulation',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative (downgraded 2026-05-01 from "Established (but transcription issue)"; third-term form vacuous under τ_P substitution and audit-suggested fix is equally vacuous; needs reformulation by domain expert — Tier R2).`,
},
{
  id: 24,
  name: `Quantum Coherence in Photosynthesis Efficiency`,
  category: `G`,
  category_name: `Quantum Biology Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `How quantum effects enhance energy transfer in biological systems`,
  formula_latex: `\\eta_{\\text{transfer}} = \\eta_{\\text{classical}} \\left[1 + \\kappa \\exp\\left(-\\frac{t}{\\tau_{\\text{coh}}}\\right) |\\langle\\psi_{\\text{donor}}|\\psi_{\\text{acceptor}}\\rangle|^2\\right]`,
  source_part: 'II',
  source_section: `Part-II Category G`,
  known_issues: [
    {
      severity: 'other',
      description: `With kappa in [0.1, 0.3] and eta_classical close to 1, the formula gives eta_transfer = eta_classical (1 + kappa exp(-t/tau_coh) |<psi_d|psi_a>|^2), which can exceed 1 (the stated bound eta in [0, 1] is violated by the equation as written). A physically correct formulation would saturate at 1 (e.g., eta = 1 - (1 - eta_classical) exp(-kappa ...)).`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Contested / superseded. The proposed quantum-coherent enhancement of photosynthetic energy transfer was based on Engel et al. 2007 FMO data (τ_coh ~ 100 fs). Subsequent work (Duan et al., PNAS 114, 84...`,
},
{
  id: 25,
  name: `Consciousness - Quantum Information Bridge`,
  category: `G`,
  category_name: `Quantum Biology Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Penrose-Hameroff orchestrated reduction theory`,
  formula_latex: `t_{\\text{OR}} = \\frac{\\hbar}{E_G} = \\frac{\\hbar}{\\Delta m c^2 \\Delta x / l_P}`,
  source_part: 'II',
  source_section: `Part-II Category G`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The formula E_G = Delta m c^2 Delta x / l_P contains a spurious factor of Delta x / l_P not present in Penrose's original gravitational self-energy proposal (canonical form: E_G ~ G (Delta m)^2 / Delta x). Use the Penrose form for any physical estimate; the form here is an ad-hoc modification original to earlier drafts.`,
      fixable: 'spec-edit',
    },
    {
      severity: 'other',
      description: `The Orch OR mechanism is contradicted by Tegmark (Phys. Rev. E 61, 4194 (2000); arXiv:quant-ph/9907009): decoherence times for microtubule-scale superpositions at biological temperatures are ~10^-13 s, vs. neural processing timescales of ~10^-3 s — a 10-order-of-magnitude gap that effectively rules out the proposed mechanism.`,
      fixable: 'unknown',
    }
  ],
  references: [`arXiv:quant-ph/9907009`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative — contradicted by quantitative decoherence analyses. The Penrose-Hameroff orchestrated objective reduction (Orch OR) theory proposes that gravitationally-induced wavefunction collap...`,
},
{
  id: 26,
  name: `DNA Mutation - Quantum Tunneling Rate`,
  category: `G`,
  category_name: `Quantum Biology Bridges`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Proton tunneling in base pair tautomerization`,
  formula_latex: `\\Gamma_{\\text{mutation}} = \\nu_0 \\exp\\left(-\\frac{2}{\\hbar}\\int_{x_1}^{x_2}\\sqrt{2m(V(x)-E)} , dx\\right) \\cdot f(T,\\text{pH}, \\text{EM})`,
  source_part: 'II',
  source_section: `Part-II Category G`,
  known_issues: [],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Established (WKB). The WKB tunneling rate formula is standard quantum mechanics (Gamow 1928; Landau-Lifshitz QM Section 50). The application to DNA base-pair tautomerization via proton tunneling is a ...`,
},
{
  id: 27,
  name: `Fluctuation-Dissipation Violation in Active Matter`,
  category: `H`,
  category_name: `Non-Equilibrium Statistical Mechanics`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Living systems violate equilibrium relations`,
  formula_latex: `\\chi(\\omega) = \\frac{1}{k_B T_{\\text{eff}}(\\omega)} \\int dt , e^{i\\omega t} \\langle \\delta F(t) \\delta x(0) \\rangle + \\Sigma_{\\text{active}}(\\omega)`,
  source_part: 'II',
  source_section: `Part-II Category H`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `Frequency-dependent effective temperature is a standard concept (Cugliandolo 2011, J. Phys. A 44:483001) but the specific functional form T_eff(omega) = T + alpha v_0^2 / (omega^2 + gamma^2) used here is conjectural and not derived from a microscopic model.`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative extension. Frequency-dependent effective temperature is a standard concept in active-matter / non-equilibrium statistical mechanics (Cugliandolo 2011, J. Phys. A 44:483001). The specific f...`,
},
{
  id: 28,
  name: `Maximum Entropy Production Principle`,
  category: `H`,
  category_name: `Non-Equilibrium Statistical Mechanics`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Why nature chooses specific non-equilibrium steady states`,
  formula_latex: `\\delta \\int \\left(\\frac{dS}{dt} - \\lambda \\sum_i J_i X_i - \\mu(\\nabla \\cdot \\mathbf{v})\\right) dt = 0`,
  source_part: 'II',
  source_section: `Part-II Category H`,
  known_issues: [],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Contested principle. Maximum Entropy Production (MEPP) is a proposed but contested principle in non-equilibrium thermodynamics (Dewar 2005; rebutted by Grinstein and Linsker 2007). It conflicts with P...`,
},
{
  id: 29,
  name: `Jarzynski Equality Extension to Gravity`,
  category: `H`,
  category_name: `Non-Equilibrium Statistical Mechanics`,
  bridges: [`unknown`, `unknown`] as [string, string],
  // Status remains 'speculative' — the gravitational-work form is now
  // canonical GR (Hilbert action variation), but applying Jarzynski's
  // flat-spacetime equality to this curved-spacetime work is unverified.
  status: 'speculative',
  context: `Work fluctuations in gravitational fields`,
  // 2026-05-01 (R1 audit): replaced ill-defined `g_{μν} dT^{μν}` with the
  // canonical Hilbert action variation `T^{μν} δg_{μν} √(-g) d⁴x`. Factor
  // `1/(2c⁴)` from MTW §21.3 / Wald §E.1.
  formula_latex: `\\langle \\exp(-\\beta W) \\rangle = \\exp(-\\beta \\Delta F) \\cdot \\exp\\left(-\\frac{\\beta}{2c^4} \\int T^{\\mu\\nu} \\delta g_{\\mu\\nu} \\sqrt{-g} \\, d^4 x\\right)`,
  source_part: 'II',
  source_section: `Part-II Category H`,
  // The R1 audit's 'undefined integration measure' issue is resolved.
  known_issues: [],
  references: [`Jarzynski 1997 PRL 78:2690`, `MTW Gravitation §21.3`, `Wald General Relativity 1984 §E.1`],
  dependencies: [],
  dimensional_signature: `[energy]`,
  notes: `see source | status_text: Speculative extension. Corrected 2026-05-01 (R1 audit, branch fix/r1-batch-spec-edits): replaced ill-defined 'g_{μν} dT^{μν}' with the canonical Hilbert action variation 'T^{μν} δg_{μν} √(-g) d⁴x' (MTW §21.3 Eq. 21.51; Wald §E.1 Eq. E.1.14). Factor 1/(2c⁴) follows from the standard 'T^{μν} := (2/√(-g)) δ(√(-g) L_matter)/δg_{μν}' definition. Status remains 'speculative' — the form of the gravitational work is now standard GR, but applying Jarzynski's flat-spacetime equality to curved-spacetime is the conjectural extension.`,
},
{
  id: 30,
  name: `Entanglement - Geometry Equation (ER=EPR generalized)`,
  category: `I`,
  category_name: `Emergent Spacetime`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `How spacetime emerges from quantum entanglement`,
  formula_latex: `g_{\\mu\\nu}(x) = \\eta_{\\mu\\nu} + \\kappa \\sum_{ij} \\langle x| \\text{Tr}*j(\\rho*{ij} \\log \\rho_{ij}) |x\\rangle`,
  source_part: 'II',
  source_section: `Part-II Category I`,
  known_issues: [
    {
      severity: 'index-structure',
      description: `LHS is a rank-2 tensor with free indices mu,nu, but RHS is a scalar sum — index structure does not match. A properly-stated entanglement-geometry relation has a form like delta g_{mu nu}(x) ~ l_P^2 partial_mu partial_nu S_EE(x) (Van Raamsdonk).`,
      fixable: 'reformulation',
    },
    {
      severity: 'undefined-quantity',
      description: `Tr_j(rho_{ij} log rho_{ij}) is a scalar (negative entanglement entropy), not an operator, so <x|...|x> is undefined on it. Additionally |x> is a non-normalizable position eigenstate requiring regularization.`,
      fixable: 'reformulation',
    },
    {
      severity: 'dimensional',
      description: `kappa ~ l_P^2 has units [L]^2 and S is dimensionless, so kappa S has units [L]^2, but metric perturbations should be dimensionless. Treat the current formula as schematic.`,
      fixable: 'reformulation',
    }
  ],
  references: [`arXiv:1005.3035`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. Van Raamsdonk 2010 (arXiv:1005.3035) and Swingle 2012 showed that entanglement structure can encode geometric data in AdS/CFT, but the specific formula \`g_{mu nu}(x) = eta_{mu nu} ...`,
},
{
  id: 31,
  name: `Causal Set - Continuum Limit`,
  category: `I`,
  category_name: `Emergent Spacetime`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Discrete to continuous spacetime transition`,
  formula_latex: `R = \\frac{2}{\\sqrt{\\pi}} \\left(\\frac{N}{V^{2/4}} - k_1 - k_2(\\rho^2 l_P^4)^{1/4}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category I`,
  known_issues: [
    {
      severity: 'dimensional',
      // Re-tiered R1 -> R2 on 2026-05-01 (branch fix/r1-batch-spec-edits).
      // The audit's own description ends with 'should be replaced with
      // their published formula' -- which is by definition reformulation,
      // not spec-edit. While `V^{2/4} -> V^{1/2}` is a literal numerical
      // identity (a clean typo), the second part (dimensional mismatch in
      // the (ρ² ℓ_P⁴)^{1/4} Ricci correction term) cannot be repaired by
      // transcription -- the Benincasa-Dowker discrete-to-continuum
      // formula uses dimensionless N counts, not (ρ² ℓ_P⁴)^{1/4}, and
      // grafting their result onto this form requires a structural
      // rewrite. Per honest-claude: preserve.
      description: `[R1->R2 re-tier 2026-05-01] (1) the exponent V^{2/4} is either a typo for V^{1/2} or should be V^{(d-2)/d} with d substituted -- this part *is* a clean spec-edit but cannot be applied in isolation because (2) the (ρ² ℓ_P⁴)^{1/4} term does not match Ricci-scalar dimensions [L^-2], and the audit's recommended fix ('replace with Benincasa-Dowker's published formula') is by definition reformulation, not transcription. The Benincasa-Dowker (arXiv:1001.2725) result uses dimensionless count differences (e.g., N - 9 N_1 + 16 N_2 - 8 N_3 over V^{2/d}), not the (ρ² ℓ_P⁴)^{1/4} structure here, so a faithful correction is a structural rewrite.`,
      fixable: 'reformulation',
    }
  ],
  references: [`arXiv:1001.2725`],
  dependencies: [],
  dimensional_signature: null,
  notes: `[R1->R2 re-tier 2026-05-01, branch fix/r1-batch-spec-edits] The R1 audit classified BE-31 as 'spec-edit' fixable, but its own description prescribes 'should be replaced with their published formula' -- reformulation by definition. The V^{2/4} -> V^{1/2} typo is a clean spec-edit on its own, but the second issue (dimensional mismatch in (ρ² ℓ_P⁴)^{1/4} vs. Ricci [L^-2]) cannot be repaired by transcription: the Benincasa-Dowker formula uses dimensionless count differences (N - 9N_1 + 16N_2 - 8N_3) / V^{2/d}, structurally different from the (ρ² ℓ_P⁴)^{1/4} written here. Applying only the typo half would leave the deeper dimensional issue, so per honest-claude: preserve as R2 candidate. status_text: Speculative. Benincasa-Dowker (arXiv:1001.2725) established discrete-to-continuum limits for causal set action and Ricci scalar.`,
},
{
  id: 32,
  name: `Quantum Reference Frame Transformation`,
  category: `I`,
  category_name: `Emergent Spacetime`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `How physics transforms between quantum reference frames`,
  formula_latex: `|\\psi\\rangle_B = \\int dg , U(g) |\\psi\\rangle_A \\otimes |g\\rangle_{\\text{frame}}`,
  source_part: 'II',
  source_section: `Part-II Category I`,
  known_issues: [],
  references: [`arXiv:1712.07207`, `arXiv:2004.14292`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Active research. Quantum Reference Frames (QRF) formalism -- where reference frames are themselves quantum systems that can be in superposition -- is a legitimate active research area (Giacomini, Cast...`,
},
{
  id: 33,
  name: `Quantum-Classical Critical Point Mapping`,
  category: `J`,
  category_name: `Phase Transitions and Criticality`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Relates <img src="https://i.upmath.me/svg/d" alt="d" />-dimensional quantum to <img src="https://i.upmath.me/svg/(d%2B1)" alt="(d+1)" />-dimensional classical transitions`,
  formula_latex: `\\xi_{\\text{quantum}}(T \\to 0) = \\frac{\\xi_{\\text{classical}}(T_{\\text{eff}} = \\hbar\\omega/k_B)}{\\sqrt{1 + (E_0/k_B T)^2}}`,
  source_part: 'II',
  source_section: `Part-II Category J`,
  known_issues: [
    {
      severity: 'other',
      description: `(a) the exponent z appears in the where-clause description but not in the main formula; (b) as T -> 0 the formula gives (E_0 / k_B T)^2 -> infinity, making xi_quantum -> 0, but correlation lengths at a QCP should **diverge** (not vanish) as T -> 0. The canonical relation near a QCP is xi_quantum ~ T^(-nu/z), which diverges; the formula as written has a sign or structure error. Treat as non-operational pending correction.`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative extension. The dynamic critical exponent z is standard in quantum phase-transition theory (Sondhi-Girvin-Carini-Shahar 1997). **Known issue:** (a) the exponent z appears in the where-claus...`,
},
{
  id: 34,
  name: `Kibble-Zurek Mechanism in Curved Spacetime`,
  category: `J`,
  category_name: `Phase Transitions and Criticality`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Defect formation during cosmological phase transitions`,
  formula_latex: `n_{\\text{defect}} = \\left(\\frac{\\tau_Q}{\\tau_0}\\right)^{-\\frac{d\\nu}{1+z\\nu}} \\cdot \\exp\\left(-\\frac{m_{\\text{defect}} c^2}{k_B T_{\\text{reh}}}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category J`,
  known_issues: [],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Established extension. The Kibble-Zurek defect density n ~ (tau_Q/tau_0)^(-d nu / (1 + z nu)) is established (Kibble 1976; Zurek 1985). The added exp(-m_defect c^2 / (k_B T_reh)) suppression for curve...`,
},
{
  id: 35,
  name: `Conformal Bootstrap - Physical Operator Equation`,
  category: `J`,
  category_name: `Phase Transitions and Criticality`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Constrains possible conformal field theories`,
  formula_latex: `\\langle O_1(x_1) O_2(x_2) O_3(x_3) O_4(x_4) \\rangle = \\sum_{\\Delta,\\ell} C_{12}^O C_{34}^O g_{\\Delta,\\ell}(u,v)`,
  source_part: 'II',
  source_section: `Part-II Category J`,
  known_issues: [],
  references: [`arXiv:0807.0004`, `arXiv:1805.04405`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Established. The conformal bootstrap crossing-symmetry equation is well established in CFT and has produced rigorous bounds on critical exponents for the 3D Ising model and other theories (Rattazzi-Ry...`,
},
{
  id: 36,
  name: `MOND - Dark Matter Interpolation Function`,
  category: `K`,
  category_name: `Modified Theories and Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Smooth transition between MOND and dark matter regimes`,
  formula_latex: `\\mathbf{F} = \\mathbf{F}*N \\mu\\left(\\frac{a}{a_0}\\right) + \\mathbf{F}*{\\text{DM}}\\left(1 - \\mu\\left(\\frac{a}{a_0}\\right)\\right)`,
  source_part: 'II',
  source_section: `Part-II Category K`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The hybrid linear blend F = F_N mu(a/a_0) + F_DM (1 - mu(a/a_0)) is not a standard MOND formulation. Standard MOND (Milgrom 1983) uses mu(a/a_0)*a = a_Newtonian as an implicit relation on a single acceleration, not a linear blend of Newtonian and DM accelerations. The form here is a bespoke ansatz original to this framework.`,
      fixable: 'reformulation',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative / non-standard. The hybrid F = F_N μ(a/a_0) + F_DM (1 − μ(a/a_0)) form is **not a standard MOND formulation**. Standard MOND (Milgrom 1983) uses μ(a/a_0)·a = a_Newtonian as an implicit rel...`,
},
{
  id: 37,
  name: `Variable Speed of Light Cosmology`,
  category: `K`,
  category_name: `Modified Theories and Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Solving horizon problem without inflation`,
  formula_latex: `c(t) = c_0\\left[1 + \\epsilon\\left(\\frac{t}{t_P}\\right)^n \\exp\\left(-\\frac{t}{t_c}\\right)\\right]`,
  source_part: 'II',
  source_section: `Part-II Category K`,
  known_issues: [
    {
      severity: 'other',
      // Re-tiered R1 -> R2 on 2026-05-01 (branch fix/r1-batch-spec-edits).
      // The audit's own description -- 'a corrected formulation should
      // cite a specific VSL paper and reproduce its equations' -- is
      // reformulation by definition. Picking among Albrecht-Magueijo
      // (arXiv:astro-ph/9811018), Moffat 1993, or Barrow VSL formulations
      // is a physics decision (each gives different modified Friedmann
      // equations), not a transcription fix. The c(t) ansatz form here
      // (c_0 [1 + ε (t/t_P)^n exp(-t/t_c)]) is original to this framework
      // and not in any cited VSL paper, so 'reproducing their equations'
      // would replace, not patch, the entry.
      description: `[R1->R2 re-tier 2026-05-01] The modified Friedmann equation as written does not match the standard Magueijo-Moffat covariant VSL formulations (Albrecht-Magueijo arXiv:astro-ph/9811018; Moffat 1993). The c(t) ansatz form 'c_0 [1 + ε (t/t_P)^n exp(-t/t_c)]' is original to this framework rather than derived from any cited VSL paper; the audit's recommendation 'should cite a specific VSL paper and reproduce its equations' is reformulation by definition (replace, not patch). Picking among VSL formulations is also a physics decision -- they are not equivalent.`,
      fixable: 'reformulation',
    }
  ],
  references: [`arXiv:astro-ph/9811018`, `Moffat 1993`],
  dependencies: [],
  dimensional_signature: null,
  notes: `[R1->R2 re-tier 2026-05-01, branch fix/r1-batch-spec-edits] The R1 audit classified BE-37 as 'spec-edit' fixable, but its own description requires 'cite a specific VSL paper and reproduce its equations' -- replacement, not transcription. Available VSL formulations (Albrecht-Magueijo, Moffat 1993, Barrow) give different modified Friedmann equations; choosing among them is a physics decision. The c(t) ansatz here is original to this framework. Per honest-claude: preserved as R2 candidate. status_text: Speculative. A minority alternative to inflation (Moffat, Magueijo). Not mainstream cosmology.`,
},
{
  id: 38,
  name: `Entropic Gravity Correction Term`,
  category: `K`,
  category_name: `Modified Theories and Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Verlinde’s emergent gravity with dark matter effects`,
  formula_latex: `\\mathbf{F} = \\mathbf{F}_N\\left[1 + \\alpha\\sqrt{\\frac{a_0}{a}} \\tanh\\left(\\sqrt{\\frac{a}{a_0}}\\right)\\right]`,
  source_part: 'II',
  source_section: `Part-II Category K`,
  known_issues: [
    {
      severity: 'other',
      description: `The interpolation function F = F_N[1 + α√(a₀/a) tanh(√(a/a₀))] as written does **not** reproduce the deep-MOND scaling F ∝ √(F_N a₀) in the a → 0 limit; instead it approaches F → F_N(1 + α), i.e., Newtonian scaling. A working MOND interpolation function should be substituted.`,
      fixable: 'unknown',
    }
  ],
  references: [`arXiv:1001.0785`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative. Based on Verlinde (arXiv:1001.0785). Contested; not accepted as mainstream physics. **Known issue:** The interpolation function F = F_N[1 + α√(a₀/a) tanh(√(a/a₀))] as written does **not**...`,
},
{
  id: 39,
  name: `Asymptotic Safety in Quantum Gravity`,
  category: `L`,
  category_name: `Quantum Field Theory Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `UV-complete theory via non-Gaussian fixed point`,
  formula_latex: `\\begin{align}
\\beta_g &= 2g + Ag^2 + Bg^3 - Cg^2\\lambda + \\mathcal{O}(g^4) \\
\\beta_\\lambda &= -2\\lambda + D\\lambda^2 - Eg\\lambda + \\mathcal{O}(\\lambda^3)
\\end{align}`,
  source_part: 'II',
  source_section: `Part-II Category L`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The functional renormalization group flow is given at the schematic level only; specific truncation choices (Einstein-Hilbert, f(R), etc.) are required for any concrete computation. The asymptotic safety program (Weinberg 1979; Reuter 1998) is active research, not experimentally confirmed.`,
      fixable: 'spec-edit',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative (active research). Asymptotic safety (Weinberg 1979; Reuter 1998) is an active research program proposing a UV-finite gravity. The functional renormalization group flow equation as written...`,
},
{
  id: 40,
  name: `Composite Higgs Potential`,
  category: `L`,
  category_name: `Quantum Field Theory Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'established',
  context: `Higgs as pseudo-Goldstone boson`,
  formula_latex: `V(h) = -\\alpha f^2 \\sin^2\\left(\\frac{h}{f}\\right) + \\beta f^4\\left[\\sin^4\\left(\\frac{h}{f}\\right) - \\sin^2\\left(\\frac{h}{f}\\right)\\cos^2\\left(\\frac{h}{f}\\right)\\right]`,
  source_part: 'II',
  source_section: `Part-II Category L`,
  known_issues: [],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Established form, but **dimensionally inhomogeneous as written**. Standard composite Higgs potentials (Kaplan-Georgi 1984; Contino-Grojean-Moretti-Piccinini-Rattazzi 2007) have the structure V(h) ∼ α ...`,
},
{
  id: 41,
  name: `Swampland Distance Conjecture Equation`,
  category: `L`,
  category_name: `Quantum Field Theory Extensions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Constraints on effective field theories from quantum gravity`,
  formula_latex: `m(\\phi) = m_0 \\exp\\left(-\\alpha\\frac{|\\phi-\\phi_0|}{M_P}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category L`,
  known_issues: [],
  references: [`arXiv:hep-th/0509212`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative. Swampland conjecture from string theory (Vafa, arXiv:hep-th/0509212). Active research; not confirmed.`,
},
{
  id: 42,
  name: `Firewall Complement Principle`,
  category: `M`,
  category_name: `Information Paradox Resolutions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Black hole information without firewalls`,
  formula_latex: `|\\psi\\rangle_{\\text{total}} = \\alpha|\\text{smooth}\\rangle_{\\text{horizon}} + \\beta|\\text{firewall}\\rangle_{\\text{horizon}}`,
  source_part: 'II',
  source_section: `Part-II Category M`,
  known_issues: [
    {
      severity: 'undefined-quantity',
      description: `The decomposition |psi> = alpha|smooth> + beta|firewall> is a tautological superposition without physics content unless f(observer, protocol) — which determines |alpha|^2 — is independently specified. As written, the complement principle has no operational predictive content.`,
      fixable: 'spec-edit',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. Firewall paradox is unresolved. The specific "complement principle" formulation here is not a standard result; the decomposition |psi> = a|smooth> + b|firewall> is a tautological s...`,
},
{
  id: 43,
  name: `ER=EPR Wormhole Dynamics`,
  category: `M`,
  category_name: `Information Paradox Resolutions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Entanglement as traversable wormholes`,
  formula_latex: `\\frac{d\\ell_{\\text{wormhole}}}{dt} = -\\gamma S_{\\text{entanglement}} + \\delta \\int T_{\\mu\\nu} u^\\mu u^\\nu dV`,
  source_part: 'II',
  source_section: `Part-II Category M`,
  known_issues: [
    {
      severity: 'dimensional',
      description: `The equation mixes entropy S_entanglement (dimensionless) with a stress-energy integral (dimensionful), and the LHS has units of length per time. Requires careful dimensional analysis to identify the unit-bridging coefficients implied by gamma and delta.`,
      fixable: 'spec-edit',
    },
    {
      severity: 'sign',
      description: `As written, d(ell)/dt = -gamma S_ent + ... has wormhole length decreasing with entanglement, opposite to the standard ER=EPR (Maldacena-Susskind) heuristic where entanglement grows the wormhole. Either gamma < 0 is implicit, or the sign is backwards.`,
      fixable: 'spec-edit',
    }
  ],
  references: [`arXiv:1306.0533`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. ER=EPR (Maldacena-Susskind, arXiv:1306.0533) is a theoretical conjecture, not an established result. The specific wormhole-length dynamics equation here mixes entropy (dimensionles...`,
},
{
  id: 44,
  name: `Soft Hair on Black Holes`,
  category: `M`,
  category_name: `Information Paradox Resolutions`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Infinite conservation laws on the horizon`,
  formula_latex: `Q_{\\text{soft}}^{\\pm} = \\int_{\\mathcal{I}^{\\pm}} \\frac{\\partial}{\\partial u} C_{z\\bar{z}} Y^z dz \\wedge d\\bar{z}`,
  source_part: 'II',
  source_section: `Part-II Category M`,
  known_issues: [],
  references: [`arXiv:1601.00921`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative. Soft-hair-on-black-holes proposals (Hawking-Perry-Strominger 2016, arXiv:1601.00921) suggest that BMS supertranslation charges can store information that would otherwise be lost. Influent...`,
},
{
  id: 45,
  name: `Trans-Planckian Censorship Constraint`,
  category: `N`,
  category_name: `Cosmological Puzzles`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Quantum gravity constraints on inflation`,
  formula_latex: `N_e < \\log\\left(\\frac{M_P}{H_{\\text{inf}}}\\right) - \\gamma \\log\\left(\\frac{r}{0.01}\\right)`,
  source_part: 'II',
  source_section: `Part-II Category N`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The extra term -gamma log(r / 0.01) is an extension original to this framework, not part of the Bedroya-Vafa TCC (arXiv:1909.11063); the canonical bound is N_e < ln(M_P / H_inf) (natural log). The added term has no published derivation, and the log base is unspecified.`,
      fixable: 'spec-edit',
    }
  ],
  references: [`arXiv:1909.11063`],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative / non-standard. The Trans-Planckian Censorship Conjecture (Bedroya-Vafa 2019, arXiv:1909.11063) bounds inflationary e-foldings via \`N_e < ln(M_P / H_inf)\`. The formula as written here adds...`,
},
{
  id: 46,
  name: `Multiverse Measure Problem`,
  category: `N`,
  category_name: `Cosmological Puzzles`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Probability distribution over universes`,
  formula_latex: `P[O] = \\int d\\mu[g,\\phi] , W[g,\\phi] , \\delta(O - O[g,\\phi])`,
  source_part: 'II',
  source_section: `Part-II Category N`,
  known_issues: [
    {
      severity: 'undefined-quantity',
      description: `The weighting factor W[g, phi] is the multiverse measure, which is itself the unsolved problem (the equation's own subject). Specific measure proposals (scale-factor cutoff, proper-time cutoff, etc.) are untestable without further theoretical development; without a determination of W, the equation has no operational predictive content.`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. The multiverse measure problem is an unsolved fundamental issue in cosmology. Specific measure proposals are untestable without further theoretical development.`,
},
{
  id: 47,
  name: `Big Bang Nucleosynthesis - Dark Sector Coupling`,
  category: `N`,
  category_name: `Cosmological Puzzles`,
  bridges: [`unknown`, `unknown`] as [string, string],
  // Status remains 'speculative'. The base Boltzmann equation (with Hubble
  // drag and species-correct rate) is now canonical Kolb-Turner / Pitrou
  // form, but the dark-sector coupling term is the unverified physics
  // extension that gives this entry its 'speculative' label.
  status: 'speculative',
  context: `Dark matter effects on light element abundances`,
  // 2026-05-01 (R1 audit): added Hubble drag '+3HY' and replaced 'n_b^2'
  // with 'n_p n_n' (species-correct product for the standard p+n→d+γ
  // two-body reaction). See Kolb & Turner §5.2 Eq. 5.13–5.14;
  // Pitrou-Coc-Uzan-Vangioni 2018 Phys. Rep. 754:1 Eq. 2.5.
  formula_latex: `\\frac{dY}{dt} + 3HY = \\langle\\sigma v\\rangle_{\\text{SM}} n_p n_n - \\langle\\sigma v\\rangle_{\\text{dark}} n_\\chi^2 \\epsilon_{\\text{transfer}}`,
  source_part: 'II',
  source_section: `Part-II Category N`,
  // Both R1 audit issues (missing Hubble drag, n_b^2 -> n_p n_n) are
  // resolved.
  known_issues: [],
  references: [
    `Wagoner-Fowler-Hoyle 1967 ApJ 148:3`,
    `Wagoner 1969 ApJS 18:247`,
    `Kolb-Turner The Early Universe 1990 §5.2`,
    `Steigman 2007 ARNPS 57:463`,
    `Pitrou-Coc-Uzan-Vangioni 2018 Phys. Rep. 754:1`,
  ],
  dependencies: [],
  dimensional_signature: `[number-density][time]^-1`,
  notes: `see source | status_text: Speculative extension on established base. Corrected 2026-05-01 (R1 audit, branch fix/r1-batch-spec-edits): added Hubble dilution drag '+3HY' (Kolb & Turner §5.2 Eq. 5.13–5.14; Pitrou-Coc-Uzan-Vangioni 2018 Eq. 2.5) and replaced 'n_b^2' with 'n_p n_n' species-correct product for the canonical p+n→d+γ two-body reaction (Steigman 2007 ARNPS 57:463 Eq. 27). Status remains 'speculative' — the base equation is now canonical Kolb-Turner form, but the dark-sector coupling 'n_χ² ε_transfer' term is the unverified physics extension.`,
},
{
  id: 48,
  name: `Objective Collapse Equation (GRW extension)`,
  category: `O`,
  category_name: `Quantum Foundations`,
  bridges: [`unknown`, `unknown`] as [string, string],
  // Status remains 'established' — this is a typesetting/transcription
  // correction to a canonical formula (the 1986 GRW master equation), not a
  // reformulation. See the "Corrected on 2026-05-04 (R0 audit)" block in
  // docs/specification/Part-II.md.
  status: 'established',
  context: `Spontaneous wavefunction collapse`,
  // 2026-05-04 (R0 audit): added the missing (πσ²)^{-3/4} prefactor to L_x so
  // the localization operator is the canonical 3D Gaussian-resolved position
  // projector and the master equation closes dimensionally to [T^-1]. Also
  // escaped the anticommutator braces (\\{...\\}) that were unbalanced.
  formula_latex: `\\frac{d\\rho}{dt} = -\\frac{i}{\\hbar}[H,\\rho] + \\lambda \\int d^3x \\left[L_x \\rho L_x^\\dagger - \\frac{1}{2}\\{L_x^\\dagger L_x, \\rho\\}\\right], \\quad L_x = (\\pi\\sigma^2)^{-3/4}\\exp\\left[-\\frac{(\\hat{\\mathbf{r}}-\\mathbf{x})^2}{2\\sigma^2}\\right]`,
  source_part: 'II',
  source_section: `Part-II Category O`,
  // The "missing prefactor" R0 issue is resolved. No residual issues found
  // during the R0 audit pass: the sum-over-particles index is implicit (the
  // single-particle form shown is the standard convention; multi-particle
  // generalization Σ_n L_x^(n) per Bassi-Ghirardi 2003 §2.1 is notational),
  // and λ now carries unambiguous units [T^-1] once the d³x integral is
  // dimensionless.
  known_issues: [],
  references: [],
  dependencies: [],
  // The GRW master equation has rate-form dimension: dρ/dt has units [T^-1]
  // (ρ is dimensionless, t in seconds). Both terms on the RHS — the
  // (i/ℏ)[H,ρ] commutator and the λ ∫ d³x [...] localization term — reduce
  // to [T^-1] once the (πσ²)^{-3/4} prefactor makes ∫ d³x L_x† L_x
  // dimensionless and λ carries [T^-1]. Encoded as the canonical Lindblad
  // rate signature.
  dimensional_signature: `[time^-1]`,
  notes: `see source | status_text: Established (within GRW class; corrected 2026-05-04 R0 audit — added canonical (πσ²)^{-3/4} prefactor to L_x and updated λ from 1e-17 to 1e-16 s^-1 to match the original 1986 GRW value). Citations: Ghirardi-Rimini-Weber 1986 Phys. Rev. D 34:470; Bassi-Ghirardi 2003 Phys. Rep. 379:257 review.`,
},
{
  id: 49,
  name: `Quantum Darwinism Redundancy`,
  category: `O`,
  category_name: `Quantum Foundations`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'speculative',
  context: `Classical reality from quantum substrate`,
  formula_latex: `I(S:F_k) = I(S:E) - \\mathcal{O}(k^{-\\alpha})`,
  source_part: 'II',
  source_section: `Part-II Category O`,
  known_issues: [
    {
      severity: 'phenomenological-ansatz',
      description: `The specific algebraic decay form I(S:F_k) = I(S:E) - O(k^-alpha) is a phenomenological ansatz not derived from the Zurek formalism (Quantum Darwinism, Nat. Phys. 5:181, 2009); the exponent alpha is a free parameter.`,
      fixable: 'unknown',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Speculative extension. Quantum Darwinism (Zurek 2009, Nat. Phys. 5:181) is established as an interpretational framework. The specific algebraic decay form \`I(S:F_k) = I(S:E) − O(k^{-α})\` is a phenomen...`,
},
{
  id: 50,
  name: `Retrocausal Quantum Field Theory`,
  category: `O`,
  category_name: `Quantum Foundations`,
  bridges: [`unknown`, `unknown`] as [string, string],
  status: 'highly-speculative',
  context: `Time-symmetric formulation solving measurement problem`,
  formula_latex: `S = \\int d^4x \\left[\\mathcal{L}*{\\text{forward}}(\\phi*+) + \\mathcal{L}*{\\text{backward}}(\\phi*-) + \\lambda\\phi_+\\phi_-\\delta^4(x-x_m)\\right]`,
  source_part: 'II',
  source_section: `Part-II Category O`,
  known_issues: [
    {
      severity: 'other',
      description: `Citation attribution issue: Cramer's transactional interpretation and the Aharonov-Vaidman two-state vector formalism are interpretational frameworks for standard QM/QFT, not retrocausal QFTs with the action written here. The Lagrangian form is closer to Wheeler-Feynman absorber theory but is original to this framework. The equation should be marked as a novel proposal rather than attributed to the cited authors.`,
      fixable: 'spec-edit',
    }
  ],
  references: [],
  dependencies: [],
  dimensional_signature: null,
  notes: `see source | status_text: Highly speculative. **Known issue with citations:** Cramer's transactional interpretation and the Aharonov-Vaidman two-state vector formalism are *interpretational* frameworks for standard QM/QFT — ne...`,
}

];

export default BRIDGE_EQUATIONS;
