/**
 * Catalog rows for BE-103 through BE-125.
 *
 * Registered through `registerBridge`. This module does not import
 * `src/bridges/index.ts`. No right-hand side is added: the installed
 * MathTS packages do not export a scalar builder.
 *
 * @module bridges/plasma-catalog
 */

/** Plasma and space catalog rows, in id order. */
export const PLASMA_CATALOG_ROWS = [
{
  id: 103,
  name: "Bohm sheath threshold",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "cold ions, with n_i(φ) = n0 / sqrt(1 − 2 e φ/(m u0²)) and Boltzmann electrons, have edge slopes whose ratio is at least 1 only when u0² ≥ k_B T_e / m_i. The sound-speed root is the non-negative one. γ_i = 3, from p ∝ n³, is the nested warmSound object and is not γ_i = 5/3. Not a kinetic sheath",
  formula_latex: "u_0 = \\sqrt{k_B T_e / m_i}",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-103) — established textbook relation, PhysJS.BohmSheath.cold_bohm_threshold",
  known_issues: [],
  references: ["cold ions, with n_i(φ) = n0 / sqrt(1 − 2 e φ/(m u0²)) and Boltzmann electrons, have edge slopes whose ratio is at least 1 only when u0² ≥ k_B T_e / m_i. The sound-speed root is the non-negative one. γ_i = 3, from p ∝ n³, is the nested warmSound object and is not γ_i = 5/3. Not a kinetic sheath"],
  dependencies: [],
  dimensional_signature: "[velocity]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateBohmSheath in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.BohmSheath.cold_bohm_threshold, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 104,
  name: "Ion-acoustic dispersion",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "cold ions, continuity, ion momentum, and Poisson with Boltzmann electrons inside Poisson give ω² = k² c_s² / (1 + k² λ_De²), with c_s² = k_B T_e / m_i and λ_De² = ε0 k_B T_e / (n0 e²), for k ≠ 0. Warm ions and a kinetic dispersion are not this row",
  formula_latex: "\\omega^2 = k^2 c_s^2 / (1 + k^2 \\lambda_{De}^2)",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-104) — established textbook relation, PhysJS.IonAcoustic.dispersion_eq",
  known_issues: [],
  references: ["cold ions, continuity, ion momentum, and Poisson with Boltzmann electrons inside Poisson give ω² = k² c_s² / (1 + k² λ_De²), with c_s² = k_B T_e / m_i and λ_De² = ε0 k_B T_e / (n0 e²), for k ≠ 0. Warm ions and a kinetic dispersion are not this row"],
  dependencies: [],
  dimensional_signature: "[frequency]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateIonAcoustic in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.IonAcoustic.dispersion_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 105,
  name: "Upper-hybrid frequency",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "cold electrons, B along z, and the ansatz Ex = E0 cos(ω t), vx = vx0 sin(ω t), vy = vy0 cos(ω t), with charge −e and ∂Ex/∂t = n e vx / ε0, give ω² = n e²/(ε0 m) + (e B/m)². Not a cyclotron monomial and not ω_pe alone",
  formula_latex: "\\omega^2 = n e^2/(\\varepsilon_0 m) + (e B/m)^2",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-105) — established textbook relation, PhysJS.UpperHybrid.upper_hybrid_eq",
  known_issues: [],
  references: ["cold electrons, B along z, and the ansatz Ex = E0 cos(ω t), vx = vx0 sin(ω t), vy = vy0 cos(ω t), with charge −e and ∂Ex/∂t = n e vx / ε0, give ω² = n e²/(ε0 m) + (e B/m)². Not a cyclotron monomial and not ω_pe alone"],
  dependencies: [],
  dimensional_signature: "[frequency]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateUpperHybrid in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.UpperHybrid.upper_hybrid_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 106,
  name: "R-wave cutoff",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "the cold Stix index n_R² = 1 − ω_p²/(ω(ω − ω_c)) is a hypothesis. Vanishing n is ω(ω − ω_c) = ω_p². For ω_c ≥ 0 the nonnegative root is ω_R = (ω_c + sqrt(ω_c² + 4 ω_p²))/2. The L root and the whistler limit are nested. The Stix dielectric is not re-derived",
  formula_latex: "\\omega_R = (\\omega_c + \\sqrt{\\omega_c^2 + 4 \\omega_p^2})/2",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-106) — established textbook relation, PhysJS.ColdPlasmaCutoff.cutoff_R",
  known_issues: [],
  references: ["the cold Stix index n_R² = 1 − ω_p²/(ω(ω − ω_c)) is a hypothesis. Vanishing n is ω(ω − ω_c) = ω_p². For ω_c ≥ 0 the nonnegative root is ω_R = (ω_c + sqrt(ω_c² + 4 ω_p²))/2. The L root and the whistler limit are nested. The Stix dielectric is not re-derived"],
  dependencies: [],
  dimensional_signature: "[frequency]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateColdPlasmaCutoff in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.ColdPlasmaCutoff.cutoff_R, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation. The cold Stix index is a hypothesis of the proof, not a derived dielectric.",
},
{
  id: 107,
  name: "Lower-hybrid frequency",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "cold singly charged fluids satisfy ω_pe²/ω_ce² = ω_pi²/(ω_ci ω_ce). The ordered balance 1 + ω_pi²/(ω_ci ω_ce) = ω_pi²/ω² is a hypothesis and gives ω² = 1/(1/ω_pi² + 1/(ω_ci ω_ce)). Dropping the leading 1 is a separate hypothesis and leaves ω² = ω_ci ω_ce. Not a cyclotron monomial",
  formula_latex: "\\omega^2 = 1/(1/\\omega_{pi}^2 + 1/(\\omega_{ci} \\omega_{ce}))",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-107) — established textbook relation, PhysJS.LowerHybrid.lower_hybrid_eq",
  known_issues: [],
  references: ["cold singly charged fluids satisfy ω_pe²/ω_ce² = ω_pi²/(ω_ci ω_ce). The ordered balance 1 + ω_pi²/(ω_ci ω_ce) = ω_pi²/ω² is a hypothesis and gives ω² = 1/(1/ω_pi² + 1/(ω_ci ω_ce)). Dropping the leading 1 is a separate hypothesis and leaves ω² = ω_ci ω_ce. Not a cyclotron monomial"],
  dependencies: [],
  dimensional_signature: "[frequency]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateLowerHybrid in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.LowerHybrid.lower_hybrid_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 108,
  name: "Oblique fast magnetosonic speed",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "the be-69 quartic with k_∥ = k cos θ is a hypothesis. The phase-speed squares are ½[c_s² + v_A² ± sqrt((c_s² + v_A²)² − 4 c_s² v_A² cos²θ)] for c_s², v_A² ≥ 0. At θ = π/2 the fast root is c_s² + v_A² and the slow root is 0, the perpendicular values and not a second proof of that polarization. At θ = 0 the roots are the larger and smaller of c_s² and v_A²",
  formula_latex: "v_+^2 = \\tfrac{1}{2}\\left[c_s^2 + v_A^2 + \\sqrt{(c_s^2 + v_A^2)^2 - 4 c_s^2 v_A^2 \\cos^2\\theta}\\right]",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-108) — established textbook relation, PhysJS.ObliqueMagnetosonic.phase_speed_eq",
  known_issues: [],
  references: ["the be-69 quartic with k_∥ = k cos θ is a hypothesis. The phase-speed squares are ½[c_s² + v_A² ± sqrt((c_s² + v_A²)² − 4 c_s² v_A² cos²θ)] for c_s², v_A² ≥ 0. At θ = π/2 the fast root is c_s² + v_A² and the slow root is 0, the perpendicular values and not a second proof of that polarization. At θ = 0 the roots are the larger and smaller of c_s² and v_A²"],
  dependencies: [],
  dimensional_signature: "[velocity]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateObliqueMagnetosonic in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.ObliqueMagnetosonic.phase_speed_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 109,
  name: "Bennett pinch (equal temperature)",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "a steady z-pinch with B = μ0 I/(2 π r), dI/dr = 2 π r j, and dp/dr = −j B cancels off the axis in d/dr[π r² p + μ0 I²/(8 π)]. Differentiability through the axis is a hypothesis. With I(0) = 0 and p(R) = 0 the fundamental theorem gives μ0 I(R)²/(8 π) = ∫₀^R 2 π r p dr. Equal temperatures are the nested equalTemperature object. The single-population current uses ∫ p dA = N k_B T and is not that hydrogenic current",
  formula_latex: "I = \\sqrt{16 \\pi N k_B T / \\mu_0}",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-109) — established textbook relation, PhysJS.BennettPinch.bennett_eq",
  known_issues: [],
  references: ["a steady z-pinch with B = μ0 I/(2 π r), dI/dr = 2 π r j, and dp/dr = −j B cancels off the axis in d/dr[π r² p + μ0 I²/(8 π)]. Differentiability through the axis is a hypothesis. With I(0) = 0 and p(R) = 0 the fundamental theorem gives μ0 I(R)²/(8 π) = ∫₀^R 2 π r p dr. Equal temperatures are the nested equalTemperature object. The single-population current uses ∫ p dA = N k_B T and is not that hydrogenic current"],
  dependencies: [],
  dimensional_signature: "[I]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateBennettPinch in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.BennettPinch.bennett_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation. The equal-temperature current is sqrt(16 π N k_B T / μ0). The factor 8 is the single-population current and is not this value. N is particles per unit length.",
},
{
  id: 110,
  name: "Loss-cone pitch",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "μ = m v_⊥²/(2 B) and the kinetic energy are constant along a field line. Parallel speed vanishes at the mirror, so sin² θ_lc = B0/Bm = 1/R_m with R_m = Bm/B0. Pitch-angle scattering is not this statement",
  formula_latex: "\\sin^2\\theta_{lc} = B_0/B_m",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-110) — established textbook relation, PhysJS.LossCone.loss_cone_eq",
  known_issues: [],
  references: ["μ = m v_⊥²/(2 B) and the kinetic energy are constant along a field line. Parallel speed vanishes at the mirror, so sin² θ_lc = B0/Bm = 1/R_m with R_m = Bm/B0. Pitch-angle scattering is not this statement"],
  dependencies: [],
  dimensional_signature: "[1]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateLossCone in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.LossCone.loss_cone_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 111,
  name: "Grad-B drift magnitude",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "μ = m v_⊥²/(2 B) and the grad-B speed μ |∇B|/(q B) give m v_⊥² |∇B|/(2 q B²). Vacuum low-β curvature uses κ = |∇B|/B, so the curvature speed is m v_∥² |∇B|/(q B²) and the sum is m (v_∥² + v_⊥²/2) |∇B|/(q B²). High-β curvature, where κ ≠ |∇B|/B, is a different vector for m ≠ 0. q is the signed charge",
  formula_latex: "v = m v_\\perp^2 |\\nabla B| / (2 q B^2)",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-111) — established textbook relation, PhysJS.GradBDrift.drift_magnitude",
  known_issues: [],
  references: ["μ = m v_⊥²/(2 B) and the grad-B speed μ |∇B|/(q B) give m v_⊥² |∇B|/(2 q B²). Vacuum low-β curvature uses κ = |∇B|/B, so the curvature speed is m v_∥² |∇B|/(q B²) and the sum is m (v_∥² + v_⊥²/2) |∇B|/(q B²). High-β curvature, where κ ≠ |∇B|/B, is a different vector for m ≠ 0. q is the signed charge"],
  dependencies: [],
  dimensional_signature: "[velocity]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateGradBDrift in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.GradBDrift.drift_magnitude, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 112,
  name: "E×B drift speed",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "steady q E + q v × B = 0 with B along z gives v_x = E_y/B and v_y = −E_x/B for q ≠ 0 and B ≠ 0. The opposite charge has the same solution. Not a finite-Larmor-radius drift",
  formula_latex: "v = |E_\\perp| / |B|",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-112) — established textbook relation, PhysJS.ExBDrift.drift_eq",
  known_issues: [],
  references: ["steady q E + q v × B = 0 with B along z gives v_x = E_y/B and v_y = −E_x/B for q ≠ 0 and B ≠ 0. The opposite charge has the same solution. Not a finite-Larmor-radius drift"],
  dependencies: [],
  dimensional_signature: "[velocity]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateExBDrift in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.ExBDrift.drift_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 113,
  name: "Landau damping rate",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "the Maxwellian f = n/(v_t sqrt(2π)) exp(−v²/(2 v_t²)) has slope −(v/v_t²) f. The residue formula γ = (π ω³/(2 n k²)) (∂f/∂v)|_{ω/k} is a hypothesis, not a contour integral, and gives γ = −sqrt(π/8) ω (ω/(k v_t))³ exp(−ω²/(2 k² v_t²)). Bohm–Gross is the nested bohmGross object and does not replace ω by ω_p in this prefactor",
  formula_latex: "\\gamma = -\\sqrt{\\pi/8}\\,\\omega\\,(\\omega/(k v_t))^3 \\exp(-\\omega^2/(2 k^2 v_t^2))",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-113) — established textbook relation, PhysJS.LandauDamping.damping_eq",
  known_issues: [],
  references: ["the Maxwellian f = n/(v_t sqrt(2π)) exp(−v²/(2 v_t²)) has slope −(v/v_t²) f. The residue formula γ = (π ω³/(2 n k²)) (∂f/∂v)|_{ω/k} is a hypothesis, not a contour integral, and gives γ = −sqrt(π/8) ω (ω/(k v_t))³ exp(−ω²/(2 k² v_t²)). Bohm–Gross is the nested bohmGross object and does not replace ω by ω_p in this prefactor"],
  dependencies: [],
  dimensional_signature: "[frequency]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateLandauDamping in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.LandauDamping.damping_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation. The residue formula is a hypothesis, not a contour integral.",
},
{
  id: 114,
  name: "Debye-sphere Coulomb argument",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "N_D = (4π/3) n λ_D³. The Rutherford b_90 = e²/(4π ε0 μ v_rel²), at (1/2) μ v_rel² = (3/2) k_B T, is e²/(12 π ε0 k_B T). Then Λ = λ_D/b_90 = 12 π n λ_D³ = 9 N_D. The one-species Debye length is an input. The angular integral and ln Λ are not evaluated",
  formula_latex: "\\Lambda = 9 N_D",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-114) — established textbook relation, PhysJS.DebyeSphere.coulomb_argument",
  known_issues: [],
  references: ["N_D = (4π/3) n λ_D³. The Rutherford b_90 = e²/(4π ε0 μ v_rel²), at (1/2) μ v_rel² = (3/2) k_B T, is e²/(12 π ε0 k_B T). Then Λ = λ_D/b_90 = 12 π n λ_D³ = 9 N_D. The one-species Debye length is an input. The angular integral and ln Λ are not evaluated"],
  dependencies: [],
  dimensional_signature: "[1]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateDebyeSphere in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.DebyeSphere.coulomb_argument, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 115,
  name: "Two-species Debye length",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "two linearized Boltzmann responses and Poisson give 1/λ_D² = 1/λ₁² + 1/λ₂², with λ_s² = ε0 k_B T_s/(n_s q_s²). Dropping a responding species leaves a different length. The one-species length is not restated",
  formula_latex: "1/\\lambda_D^2 = 1/\\lambda_1^2 + 1/\\lambda_2^2",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-115) — established textbook relation, PhysJS.MultiDebye.debye_two",
  known_issues: [],
  references: ["two linearized Boltzmann responses and Poisson give 1/λ_D² = 1/λ₁² + 1/λ₂², with λ_s² = ε0 k_B T_s/(n_s q_s²). Dropping a responding species leaves a different length. The one-species length is not restated"],
  dependencies: [],
  dimensional_signature: "[length]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateMultiDebye in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.MultiDebye.debye_two, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 116,
  name: "Lorentz resistivity (kinetic)",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "σ_tr = 4π b0² ln Λ is a hypothesis, with b0 = Z e²/(4π ε0 m v²). At v_T² = 2 k_B T/m, ν(v_T) = n_i Z² e⁴ ln Λ √2 / (16 π ε0² √m (k_B T √(k_B T))). The conductivity moment σ = (8/√π) n_e e²/(m ν(v_T)) is a hypothesis, not the Gaussian integral. With n_e = Z n_i it gives η = (π √(2π)/8) Z e² √m ln Λ / ((4π ε0)² (k_B T √(k_B T))). The typed reference closure is nested. The Spitzer–Härm factor 0.51 is not this row",
  formula_latex: "\\eta = (\\pi \\sqrt{2\\pi}/8)\\, Z e^2 \\sqrt{m} \\ln\\Lambda / ((4\\pi\\varepsilon_0)^2 (k_B T)^{3/2})",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-116) — established textbook relation, PhysJS.LorentzResistivity.resistivity_eq",
  known_issues: [],
  references: ["σ_tr = 4π b0² ln Λ is a hypothesis, with b0 = Z e²/(4π ε0 m v²). At v_T² = 2 k_B T/m, ν(v_T) = n_i Z² e⁴ ln Λ √2 / (16 π ε0² √m (k_B T √(k_B T))). The conductivity moment σ = (8/√π) n_e e²/(m ν(v_T)) is a hypothesis, not the Gaussian integral. With n_e = Z n_i it gives η = (π √(2π)/8) Z e² √m ln Λ / ((4π ε0)² (k_B T √(k_B T))). The typed reference closure is nested. The Spitzer–Härm factor 0.51 is not this row"],
  dependencies: [],
  dimensional_signature: "[L^3 M T^-3 I^-2]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateLorentzResistivity in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.LorentzResistivity.resistivity_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation. The catalog value is the kinetic closure. σ_tr and the conductivity moment are hypotheses. The reference closure η_ref = (32/(3π)) η is nested and is not this value.",
},
{
  id: 117,
  name: "Resistive-slab decay time",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "η_m = 1/(μ0 σ) and ∂B/∂t = η_m ∂²B/∂x² are hypotheses. The slab mode B0 sin(π x/L) exp(−t/τ) decays at τ = μ0 σ L²/π². A denominator 4π is not π². Rm and the Lundquist number are the nested lundquist object. Not the Reynolds analogy",
  formula_latex: "\\tau = \\mu_0 \\sigma L^2 / \\pi^2",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-117) — established textbook relation, PhysJS.ResistiveSlab.decay_time",
  known_issues: [],
  references: ["η_m = 1/(μ0 σ) and ∂B/∂t = η_m ∂²B/∂x² are hypotheses. The slab mode B0 sin(π x/L) exp(−t/τ) decays at τ = μ0 σ L²/π². A denominator 4π is not π². Rm and the Lundquist number are the nested lundquist object. Not the Reynolds analogy"],
  dependencies: [],
  dimensional_signature: "[time]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateResistiveSlab in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.ResistiveSlab.decay_time, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 118,
  name: "Parker critical radius",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "an isothermal spherical wind factors as (v − c_s²/v) dv = (2 c_s²/r − G M/r²) dr. The critical point is both factors vanishing: v² = c_s² and r_c = G M/(2 c_s²). The 2 is spherical divergence. A vanishing coefficient alone does not force the geometric side to vanish",
  formula_latex: "r_c = G M / (2 c_s^2)",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-118) — established textbook relation, PhysJS.ParkerCritical.critical_radius",
  known_issues: [],
  references: ["an isothermal spherical wind factors as (v − c_s²/v) dv = (2 c_s²/r − G M/r²) dr. The critical point is both factors vanishing: v² = c_s² and r_c = G M/(2 c_s²). The 2 is spherical divergence. A vanishing coefficient alone does not force the geometric side to vanish"],
  dependencies: [],
  dimensional_signature: "[length]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateParkerCritical in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.ParkerCritical.critical_radius, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 119,
  name: "Parker spiral ratio",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "B_φ/B_r = r sinθ dφ/dr and the frozen-in angle dφ/dr = −Ω/v_r give B_φ/B_r = −Ω r sinθ/v_r. sinθ is a real parameter. Dropping the sign is a different spiral",
  formula_latex: "B_\\phi/B_r = -\\Omega r \\sin\\theta / v_r",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-119) — established textbook relation, PhysJS.ParkerSpiral.spiral_ratio",
  known_issues: [],
  references: ["B_φ/B_r = r sinθ dφ/dr and the frozen-in angle dφ/dr = −Ω/v_r give B_φ/B_r = −Ω r sinθ/v_r. sinθ is a real parameter. Dropping the sign is a different spiral"],
  dependencies: [],
  dimensional_signature: "[1]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateParkerSpiral in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.ParkerSpiral.spiral_ratio, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 120,
  name: "Chapman–Ferraro standoff",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "a doubled dipole B_mp = 2 B_E (R_E/r)³ is a hypothesis. Ram balance ρ v² = B_mp²/(2 μ0) at K = 1 gives (R/R_E)⁶ = 2 B_E²/(μ0 ρ v²). Specular 2 ρ v² replaces the numerator 2 by 1. Magnetic pressure is an input, not a proof of be-74",
  formula_latex: "(R/R_E)^6 = 2 B_E^2 / (\\mu_0 \\rho v^2)",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-120) — established textbook relation, PhysJS.ChapmanFerraro.standoff_eq",
  known_issues: [],
  references: ["a doubled dipole B_mp = 2 B_E (R_E/r)³ is a hypothesis. Ram balance ρ v² = B_mp²/(2 μ0) at K = 1 gives (R/R_E)⁶ = 2 B_E²/(μ0 ρ v²). Specular 2 ρ v² replaces the numerator 2 by 1. Magnetic pressure is an input, not a proof of be-74"],
  dependencies: [],
  dimensional_signature: "[1]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateChapmanFerraro in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.ChapmanFerraro.standoff_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 121,
  name: "Lawson breakeven product",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "a 50–50 Maxwellian DT mix, with bremsstrahlung neglected, has fusion power (n² ⟨σv⟩/4) E and thermal power 3 n k_B T/τ. Breakeven gives n τ = 12 k_B T/(⟨σv⟩ E). The 12 is 4 × 3, not either factor alone. The Maxwellian average is not computed, and this is not an evaluated triple product",
  formula_latex: "n \\tau = 12 k_B T / (\\langle\\sigma v\\rangle E)",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-121) — established textbook relation, PhysJS.LawsonBreakeven.breakeven_eq",
  known_issues: [],
  references: ["a 50–50 Maxwellian DT mix, with bremsstrahlung neglected, has fusion power (n² ⟨σv⟩/4) E and thermal power 3 n k_B T/τ. Breakeven gives n τ = 12 k_B T/(⟨σv⟩ E). The 12 is 4 × 3, not either factor alone. The Maxwellian average is not computed, and this is not an evaluated triple product"],
  dependencies: [],
  dimensional_signature: "[L^-3 T]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateLawsonBreakeven in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.LawsonBreakeven.breakeven_eq, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 122,
  name: "Langmuir floating potential",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "Γ_e = n0 exp(e Φ/(k_B T)) sqrt(k_B T/(2 π m_e)). Equating it to the Bohm ion flux gives e Φ/(k_B T) = (1/2) ln(2 π m_e/m_i) − 1/2. The ion flux is the nested bohmFlux object. Not Child–Langmuir",
  formula_latex: "e\\Phi/(k_B T) = \\tfrac{1}{2}\\ln(2\\pi m_e/m_i) - \\tfrac{1}{2}",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-122) — established textbook relation, PhysJS.LangmuirProbe.floating_potential",
  known_issues: [],
  references: ["Γ_e = n0 exp(e Φ/(k_B T)) sqrt(k_B T/(2 π m_e)). Equating it to the Bohm ion flux gives e Φ/(k_B T) = (1/2) ln(2 π m_e/m_i) − 1/2. The ion flux is the nested bohmFlux object. Not Child–Langmuir"],
  dependencies: [],
  dimensional_signature: "[1]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateLangmuirProbe in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.LangmuirProbe.floating_potential, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 123,
  name: "Cross-field diffusion ratio",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "q E + q v × B − m v/τ = 0, with μ = q τ/m and α = μ B, solves to v_x = μ (E_x + α E_y)/(1+α²) and v_y = μ (E_y − α E_x)/(1+α²). Einstein's relation D = μ k_B T/q on μ and on μ/(1+α²), the same relation as be-70 and not re-proved here, gives D_⊥/D_∥ = 1/(1+ω_c² τ²) for E along x. The ratio is even in the sign of ω_c. Bohm's 1/16 equals this ratio only when α² = 15",
  formula_latex: "D_\\perp/D_\\parallel = 1/(1+\\alpha^2)",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-123) — established textbook relation, PhysJS.CrossFieldDiffusion.diffusion_ratio",
  known_issues: [],
  references: ["q E + q v × B − m v/τ = 0, with μ = q τ/m and α = μ B, solves to v_x = μ (E_x + α E_y)/(1+α²) and v_y = μ (E_y − α E_x)/(1+α²). Einstein's relation D = μ k_B T/q on μ and on μ/(1+α²), the same relation as be-70 and not re-proved here, gives D_⊥/D_∥ = 1/(1+ω_c² τ²) for E along x. The ratio is even in the sign of ω_c. Bohm's 1/16 equals this ratio only when α² = 15"],
  dependencies: [],
  dimensional_signature: "[1]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateCrossFieldDiffusion in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.CrossFieldDiffusion.diffusion_ratio, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 124,
  name: "Firehose margin",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "the CGL root ω² = (k_∥²/ρ) (B²/μ0 + p_⊥ − p_∥) is a hypothesis. It is negative iff p_∥ − p_⊥ > B²/μ0. With β = 2 μ0 p/B², the be-76 definition and not the solenoid hypotheses of beta_eq, the threshold is β_∥ − β_⊥ > 2. The CGL closure is not derived. be-76 does not prove this inequality",
  formula_latex: "\\beta_\\parallel - \\beta_\\perp",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-124) — established textbook relation, PhysJS.Firehose.firehose_threshold",
  known_issues: [],
  references: ["the CGL root ω² = (k_∥²/ρ) (B²/μ0 + p_⊥ − p_∥) is a hypothesis. It is negative iff p_∥ − p_⊥ > B²/μ0. With β = 2 μ0 p/B², the be-76 definition and not the solenoid hypotheses of beta_eq, the threshold is β_∥ − β_⊥ > 2. The CGL closure is not derived. be-76 does not prove this inequality"],
  dependencies: [],
  dimensional_signature: "[1]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateFirehose in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.Firehose.firehose_threshold, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.",
},
{
  id: 125,
  name: "Mirror margin",
  category: 'D',
  category_name: 'Field Unification Bridges',
  bridges: ['fluid', 'plasma'] as [string, string],
  status: 'established' as const,
  context: "the mirror threshold β_⊥ (T_⊥/T_∥ − 1) > 1 is a hypothesis, equivalent to T_⊥/T_∥ − 1 > 1/β_⊥, with β = 2 μ0 p/B². A beta that omits the 2 replaces 1/β by 2/β. The temperature ratio is not the temperature difference. The kinetic integral is not evaluated. Not the loss cone and not a proof of be-76",
  formula_latex: "\\beta_\\perp (T_\\perp/T_\\parallel - 1)",
  source_part: 'III' as const,
  source_section: "Plasma and space catalog (be-125) — established textbook relation, PhysJS.MirrorInstability.mirror_threshold",
  known_issues: [],
  references: ["the mirror threshold β_⊥ (T_⊥/T_∥ − 1) > 1 is a hypothesis, equivalent to T_⊥/T_∥ − 1 > 1/β_⊥, with β = 2 μ0 p/B². A beta that omits the 2 replaces 1/β by 2/β. The temperature ratio is not the temperature difference. The kinetic integral is not evaluated. Not the loss cone and not a proof of be-76"],
  dependencies: [],
  dimensional_signature: "[1]",
  tractability_class: 'closed-form' as const,
  notes: "Closed-form evaluator evaluateMirrorInstability in src/bridges/plasma-space.ts. The overlay formalRef is PhysJS.MirrorInstability.mirror_threshold, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation. The threshold is a hypothesis. The kinetic integral is not evaluated.",
},
];
