/**
 * Catalog rows for BE-147 through BE-170.
 *
 * Registered through `registerBridge`. No right-hand-side AST: each row's
 * numeric body is the evaluator. There is no type field. Standard and
 * cross-domain are sentences in `notes`.
 *
 * @module bridges/thermal-r9-catalog
 */

const proved = (evaluator: string, theorem: string): string =>
  `Closed-form evaluator ${evaluator} in src/bridges/thermal-r9.ts. The overlay formalRef is ${theorem}, kind bridge. The catalog path passes it, so catalog evidence and edge evidence are formally-proved. The edge confidence stays established. No confrontation.`;

/** Thermal and chemical catalog rows, in id order. */
export const THERMAL_R9_CATALOG_ROWS = [
  {
    id: 147,
    name: 'Arrhenius rate',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['chemical', 'thermal'] as [string, string],
    status: 'established' as const,
    context:
      'k = A exp(−Ea/(R T)) with R = N_A k_B is the molecular factor exp(−ε/(k_B T)) at ε = Ea/N_A. The prefactor A is temperature-independent. Not the Eyring identification of A. Arrhenius. Rate constant',
    formula_latex: 'k = A \\exp(-E_a/(R T)),\\quad R = N_A k_B',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-147) — established textbook relation, PhysJS.Arrhenius.arrhenius_eq',
    known_issues: [],
    references: ['The temperature-independent prefactor is the hypothesis of PhysJS.Arrhenius.arrhenius_eq.'],
    dependencies: [],
    dimensional_signature: '[frequency]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateArrhenius', 'PhysJS.Arrhenius.arrhenius_eq')} Type standard. The Eyring identification of A is not this row.`,
  },
  {
    id: 148,
    name: 'Eyring rate',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermal', 'chemical'] as [string, string],
    status: 'established' as const,
    context:
      'k = (k_B T/h) exp(−ΔG‡/(k_B T)). The molar form calls Arrhenius at R = N_A k_B. The logarithmic derivative is Ea = ΔH‡ + R T, and that Ea is not the constant in k = A exp(−Ea/(R T)) at A = (k_B T/h) exp(ΔS‡/R): those substitutions differ by exp(−1). The transmission coefficient is 1. Eyring. Transition state',
    formula_latex: 'k = (k_B T/h) \\exp(-\\Delta G^\\ddagger/(k_B T))',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-148) — established textbook relation, PhysJS.Eyring.eyring_eq',
    known_issues: [],
    references: ['The molar form calls PhysJS.Arrhenius.arrhenius_eq. It is not a second proof of be-147.'],
    dependencies: [],
    dimensional_signature: '[frequency]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateEyring', 'PhysJS.Eyring.eyring_eq')} Type standard. Derived from be-147 for the molar form. The substitutions Ea = ΔH‡ + R T and A = (k_B T/h) exp(ΔS‡/R) differ from this rate by exp(−1). The transmission coefficient is 1.`,
  },
  {
    id: 149,
    name: "van 't Hoff slope",
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['chemical', 'thermodynamic'] as [string, string],
    status: 'established' as const,
    context:
      "equilibrium_log is the Gibbs isotherm, so ln K = −ΔG°/(R T). At ΔG° = ΔH° − T ΔS° with both constant, d ln K/dT = ΔH°/(R T²). Not a second proof of be-150 and not a van 't Hoff plot. van 't Hoff",
    formula_latex: '\\frac{d \\ln K}{dT} = \\frac{\\Delta H^\\circ}{R T^2}',
    source_part: 'III' as const,
    source_section: "Thermal catalog (be-149) — established textbook relation, PhysJS.VanTHoff.vant_hoff",
    known_issues: [],
    references: ['equilibrium_log is PhysJS.GibbsIsotherm.gibbs_eq. ΔH° and ΔS° are constant.'],
    dependencies: [],
    dimensional_signature: '[Theta^-1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateVanTHoff', 'PhysJS.VanTHoff.vant_hoff')} Type standard. Derived from be-150. ΔH° and ΔS° are constant. Not a plot and not a second proof of be-150.`,
  },
  {
    id: 150,
    name: 'Gibbs isotherm',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermodynamic', 'chemical'] as [string, string],
    status: 'established' as const,
    context:
      'Σ ν_i μ_i = 0 with μ_i = μ_i° + R T ln a_i gives ΔG° = −R T ln K for K > 0 and T ≠ 0. Not an activity model. Gibbs. Equilibrium',
    formula_latex: '\\Delta G^\\circ = -R T \\ln K',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-150) — established textbook relation, PhysJS.GibbsIsotherm.gibbs_eq',
    known_issues: [],
    references: ['The chemical-potential sum is the hypothesis of PhysJS.GibbsIsotherm.gibbs_eq.'],
    dependencies: [],
    dimensional_signature: '[L^2 M T^-2 N^-1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateGibbsIsotherm', 'PhysJS.GibbsIsotherm.gibbs_eq')} Type standard. K > 0 and T ≠ 0. Not an activity model.`,
  },
  {
    id: 151,
    name: 'Nernst voltage',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['electrochemical', 'thermodynamic'] as [string, string],
    status: 'established' as const,
    context:
      'The cell standard state is the Gibbs isotherm, and ΔG = −n F E with F = N_A e gives E = E° − (R T/(n F)) ln Q. e is the elementary charge. The same voltage is E° − (k_B T/(n e)) ln Q. Not a second proof of be-150. Nernst',
    formula_latex: 'E = E^\\circ - (R T/(n F)) \\ln Q,\\quad F = N_A e',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-151) — established textbook relation, PhysJS.NernstGibbs.nernst_eq',
    known_issues: [],
    references: ['The standard state is PhysJS.GibbsIsotherm.gibbs_eq. ΔG = −n F E is on the same result.'],
    dependencies: [],
    dimensional_signature: '[L^2 M T^-3 I^-1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateNernstGibbs', 'PhysJS.NernstGibbs.nernst_eq')} Type standard. Derived from be-150. The edge value is E. ΔG = −n F E is the other field. e is the elementary charge. Not a second proof of be-150.`,
  },
  {
    id: 152,
    name: 'Integrated Clausius–Clapeyron',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermal', 'phase'] as [string, string],
    status: 'established' as const,
    context:
      'ideal_vapor_slope calls the Clapeyron slope, be-71, and substitutes Δv = R T/P. Constant latent heat integrates to ln(P2/P1) = −(ΔH/R)(1/T2 − 1/T1). Both temperatures are positive. Not a second proof of be-71. A separate liquid volume is not this row. Clausius–Clapeyron',
    formula_latex: '\\ln(P_2/P_1) = -(\\Delta H/R)(1/T_2 - 1/T_1)',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-152) — established textbook relation, PhysJS.ClausiusClapeyron.integrated_eq',
    known_issues: [],
    references: ['ideal_vapor_slope calls PhysJS.Clapeyron.slope_eq, be-71.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateClausiusClapeyron', 'PhysJS.ClausiusClapeyron.integrated_eq')} Type standard. Derived from be-71. Both temperatures are positive. A separate liquid volume is not this row. Not a second proof of be-71.`,
  },
  {
    id: 153,
    name: 'Raoult partial pressure',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['chemical', 'phase'] as [string, string],
    status: 'established' as const,
    context:
      'The Gibbs isotherm on the ideal mixture and on the pure liquid gives P = x P*. The liquid activity is the mole fraction and the vapor activity is P/P°. Not a second proof of be-150. A nonideal activity is not this row. Raoult',
    formula_latex: 'P = x P^*',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-153) — established textbook relation, PhysJS.Raoult.raoult_eq',
    known_issues: [],
    references: ['Both activities are PhysJS.GibbsIsotherm.gibbs_eq. P° > 0.'],
    dependencies: [],
    dimensional_signature: '[L^-1 M T^-2]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateRaoult', 'PhysJS.Raoult.raoult_eq')} Type standard. Derived from be-150 twice, once for the mixture and once for the pure liquid. A nonideal activity is not this row. Not a second proof of be-150.`,
  },
  {
    id: 154,
    name: 'Prandtl number',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermal', 'fluid'] as [string, string],
    status: 'established' as const,
    context:
      'The ratio identity Pr = ν/α with ν = μ/ρ and α = k/(ρ c_p) is the product Pr k = μ c_p. Not a heat-transfer correlation and not the Reynolds analogy of be-86. Prandtl',
    formula_latex: '\\mathrm{Pr} = \\mu c_p / k',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-154) — established textbook relation, PhysJS.Prandtl.prandtl_eq',
    known_issues: [],
    references: ['The kinematic viscosity and the thermal diffusivity are the hypotheses of PhysJS.Prandtl.prandtl_eq.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluatePrandtl', 'PhysJS.Prandtl.prandtl_eq')} Type standard. Not a correlation and not be-86.`,
  },
  {
    id: 155,
    name: 'Reynolds number',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['fluid', 'inertial'] as [string, string],
    status: 'established' as const,
    context:
      'Inertial flux over viscous flux is Re = (ρ v²)/(μ v/L) = v L/ν with ν = μ/ρ, so Re μ = ρ v L. Not a friction correlation and not the pipe factor of be-77. Reynolds number',
    formula_latex: '\\mathrm{Re} = \\rho v L / \\mu',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-155) — established textbook relation, PhysJS.ReynoldsNumber.reynolds_eq',
    known_issues: [],
    references: ['The flux ratio is the hypothesis of PhysJS.ReynoldsNumber.reynolds_eq.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateReynoldsNumber', 'PhysJS.ReynoldsNumber.reynolds_eq')} Type standard. Not a friction correlation and not the pipe factor of be-77.`,
  },
  {
    id: 156,
    name: 'Biot number',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermal', 'conduction'] as [string, string],
    status: 'established' as const,
    context:
      'With L_c = V/A, Bi = (L_c/k)/(1/h) = h V/(k A), so Bi k = h L_c. Not a lumped-capacitance criterion. Biot',
    formula_latex: '\\mathrm{Bi} = h L_c / k',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-156) — established textbook relation, PhysJS.Biot.biot_eq',
    known_issues: [],
    references: ['L_c = V/A is the hypothesis of PhysJS.Biot.biot_eq. The volume form is the same number.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateBiot', 'PhysJS.Biot.biot_eq')} Type standard. The edge value is Bi = h L_c/k. Bi = h V/(k A) when L_c = V/A is the same statement. Not a lumped-capacitance criterion.`,
  },
  {
    id: 157,
    name: 'Nusselt number',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermal', 'convection'] as [string, string],
    status: 'established' as const,
    context:
      'h = k (∂T/∂n)/ΔT makes Nu = h L/k equal to L (∂T/∂n)/ΔT, so Nu k = h L. Not a correlation for Nu. Nusselt',
    formula_latex: '\\mathrm{Nu} = h L / k',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-157) — established textbook relation, PhysJS.Nusselt.nusselt_eq',
    known_issues: [],
    references: ['The wall gradient is the hypothesis of PhysJS.Nusselt.nusselt_eq.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateNusselt', 'PhysJS.Nusselt.nusselt_eq')} Type standard. Not a correlation.`,
  },
  {
    id: 158,
    name: 'Schmidt number',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['fluid', 'diffusion'] as [string, string],
    status: 'established' as const,
    context:
      'Sc = ν/D with ν = μ/ρ is Sc ρ D = μ, and Le = α/D = Sc/Pr once Pr = ν/α. Not a mass-transfer correlation. Schmidt. Lewis',
    formula_latex: '\\mathrm{Sc} = \\mu/(\\rho D)',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-158) — established textbook relation, PhysJS.Schmidt.schmidt_eq',
    known_issues: [],
    references: ['Le = Sc/Pr is the second conjunct of PhysJS.Schmidt.schmidt_eq and is not a second edge.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateSchmidt', 'PhysJS.Schmidt.schmidt_eq')} Type standard. The edge value is Sc. Le = Sc/Pr is the second conjunct and is not a second edge. Not a mass-transfer correlation.`,
  },
  {
    id: 159,
    name: 'Sherwood number',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['diffusion', 'convection'] as [string, string],
    status: 'established' as const,
    context:
      'k_m = D (∂c/∂n)/Δc makes Sh = k_m L/D equal to L (∂c/∂n)/Δc, so Sh D = k_m L. Not a correlation for Sh. Sherwood',
    formula_latex: '\\mathrm{Sh} = k_m L / D',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-159) — established textbook relation, PhysJS.Sherwood.sherwood_eq',
    known_issues: [],
    references: ['The wall gradient of concentration is the hypothesis of PhysJS.Sherwood.sherwood_eq.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateSherwood', 'PhysJS.Sherwood.sherwood_eq')} Type standard. Not a correlation.`,
  },
  {
    id: 160,
    name: 'Fourier slab flux',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['conduction', 'thermal'] as [string, string],
    status: 'established' as const,
    context:
      'A constant flux q = −k dT/dx integrates to q L = −k (T(L) − T(0)). A temperature-dependent conductivity is not this row. Fourier. Conduction',
    formula_latex: 'q L = -k (T(L) - T(0))',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-160) — established textbook relation, PhysJS.FourierConduction.fourier_eq',
    known_issues: [],
    references: ['Constant conductivity and constant flux are the hypotheses of PhysJS.FourierConduction.fourier_eq.'],
    dependencies: [],
    dimensional_signature: '[M T^-3]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateFourierConduction', 'PhysJS.FourierConduction.fourier_eq')} Type standard. The proved statement is the integrated slab, sign included. The differential q = −k dT/dx is the hypothesis. A temperature-dependent conductivity is not this row.`,
  },
  {
    id: 161,
    name: 'Newton cooling',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['convection', 'thermal'] as [string, string],
    status: 'established' as const,
    context:
      'ρ c V dθ/dt = −h A θ integrates to θ(t) = θ(0) exp(−t/τ) with τ = ρ c V/(h A). Radiation in T^4 is not this row. Newton. Lumped cooling',
    formula_latex: '\\theta(t) = \\theta(0) \\exp(-t/\\tau),\\quad \\tau = \\rho c V/(h A)',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-161) — established textbook relation, PhysJS.NewtonCooling.newton_eq',
    known_issues: [],
    references: ['The linear flux law is the ODE hypothesis of PhysJS.NewtonCooling.newton_eq.'],
    dependencies: [],
    dimensional_signature: '[temperature]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateNewtonCooling', 'PhysJS.NewtonCooling.newton_eq')} Type standard. The edge value is θ(t). τ is the other field. θ(0) is an excess: the evaluator key theta_difference_K is an interval. The bare flux q = h A θ is a power and is not this temperature. Radiation in T^4 is not this row.`,
  },
  {
    id: 162,
    name: 'Otto efficiency',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermodynamic', 'mechanical'] as [string, string],
    status: 'established' as const,
    context:
      'The cold-air isentropic cycle at constant γ > 1 gives η = 1 − r^(1−γ). A temperature-dependent heat capacity is not this row. Otto',
    formula_latex: '\\eta = 1 - r^{1-\\gamma}',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-162) — established textbook relation, PhysJS.Otto.otto_eq',
    known_issues: [],
    references: ['Constant γ > 1 is the hypothesis of PhysJS.Otto.otto_eq. The exponent γ−1 is not 1−γ.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateOtto', 'PhysJS.Otto.otto_eq')} Type standard. Cold-air standard, constant γ > 1. A temperature-dependent heat capacity is not this row. r^(γ−1) is not r^(1−γ).`,
  },
  {
    id: 163,
    name: 'Joule–Thomson coefficient',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermodynamic', 'fluid'] as [string, string],
    status: 'established' as const,
    context:
      'The enthalpy differential dh = c_p dT + (v − T (∂v/∂T)_p) dP is a hypothesis. It gives μ_JT c_p = T (∂v/∂T)_p − v, and the ideal-gas bracket v = R T/P vanishes. Not a measured inversion curve. Joule–Thomson',
    formula_latex: '\\mu_{JT} c_p = T (\\partial v/\\partial T)_p - v',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-163) — established textbook relation, PhysJS.JouleThomson.joule_thomson_eq',
    known_issues: [],
    references: ['The enthalpy differential is a hypothesis of PhysJS.JouleThomson.joule_thomson_eq.'],
    dependencies: [],
    dimensional_signature: '[L M^-1 T^2 Theta]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateJouleThomson', 'PhysJS.JouleThomson.joule_thomson_eq')} Type standard. The edge value is the general coefficient μ_JT = (T (∂v/∂T)_p − v)/c_p. The ideal-gas bracket v = R T/P vanishes, so μ_JT = 0 for that gas. Not a measured inversion curve.`,
  },
  {
    id: 164,
    name: 'Planck spectrum',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['quantum', 'thermal'] as [string, string],
    status: 'established' as const,
    context:
      'The Bose factor 1/(exp(x) − 1) = Σ_{n≥1} exp(−n x) is proved. The mode density 8 π ν²/c³, two polarizations, is a hypothesis. Their product is u (exp(hν/kT) − 1) c³ = 8 π h ν³. The frequency integral is be-165. Planck',
    formula_latex: 'u (\\exp(h\\nu/k_B T) - 1) c^3 = 8 \\pi h \\nu^3',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-164) — established textbook relation, PhysJS.PlanckSpectrum.planck_eq',
    known_issues: [],
    references: ['The mode density, two polarizations, is a hypothesis of PhysJS.PlanckSpectrum.planck_eq.'],
    dependencies: [],
    dimensional_signature: '[L^-1 M T^-1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluatePlanckSpectrum', 'PhysJS.PlanckSpectrum.planck_eq')} Type cross-domain. The 8π mode density is a hypothesis. One polarization is not this density. The frequency integral is be-165.`,
  },
  {
    id: 165,
    name: 'Stefan–Boltzmann constant',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermal', 'quantum'] as [string, string],
    status: 'established' as const,
    context:
      '∫_0^∞ x³/(exp(x) − 1) dx = π⁴/15 from Σ n^{−4} = π⁴/90 and Γ(4) = 6. The hemisphere integrals give the factor c/4. With h = 2 π ℏ, σ = π² k_B⁴/(60 ℏ³ c²) = 2 π⁵ k_B⁴/(15 h³ c²). The mode density 8π is the hypothesis of be-164. Not a radiometer measurement. Stefan–Boltzmann',
    formula_latex: '\\sigma = \\pi^2 k_B^4 / (60 \\hbar^3 c^2)',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-165) — established textbook relation, PhysJS.StefanBoltzmann.stefan_boltzmann_eq',
    known_issues: [],
    references: ['The zeta value and the hemisphere factor are the steps of PhysJS.StefanBoltzmann.stefan_boltzmann_eq.'],
    dependencies: [],
    dimensional_signature: '[M T^-3 Theta^-4]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateStefanBoltzmann', 'PhysJS.StefanBoltzmann.stefan_boltzmann_eq')} Type cross-domain. The value is the exact quotient, not a rounded display of the same constant. The mode density 8π is the hypothesis of be-164. Not a radiometer measurement.`,
  },
  {
    id: 166,
    name: 'Wien displacement',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['quantum', 'radiation'] as [string, string],
    status: 'established' as const,
    context:
      'spectral(x) = x⁵/(exp(x) − 1) has derivative zero for x > 0 exactly when 5 − x = 5 exp(−x). That equation has a unique positive root and the root lies in (4, 5). The decimal is not evaluated. x = 0 is an extraneous root. The displacement constant is b k_B x = h c. Wien',
    formula_latex: 'b k_B x = h c',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-166) — established textbook relation, PhysJS.WienDisplacement.wien_eq',
    known_issues: [],
    references: ['x is an input. PhysJS.WienDisplacement.wien_eq does not evaluate the decimal.'],
    dependencies: [],
    dimensional_signature: '[L Theta]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateWienDisplacement', 'PhysJS.WienDisplacement.wien_eq')} Type cross-domain. x is an input constrained to (4, 5). The proof places the unique positive root of 5 − x = 5 exp(−x) in that interval and does not evaluate the decimal. x = 0 is an extraneous root. Supplying an x in (4, 5) states the algebra b k_B x = h c; it does not certify that the supplied x is the root.`,
  },
  {
    id: 167,
    name: 'Sackur–Tetrode entropy',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['quantum', 'statistical'] as [string, string],
    status: 'established' as const,
    context:
      'n_Q = λ_T^{−3} uses the thermal de Broglie wavelength, be-12. Stirling ln N! = N ln N − N is a hypothesis, and U = (3/2) N k_B T is equipartition. They give S = N k_B (ln(n_Q/n) + 5/2). Not a second proof of be-12 and not the Stirling series. Sackur–Tetrode',
    formula_latex: 'S = N k_B (\\ln(n_Q/n) + 5/2)',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-167) — established textbook relation, PhysJS.SackurTetrode.sackur_tetrode',
    known_issues: [],
    references: ['n_Q uses PhysJS.ThermalDeBroglie.wavelength_eq, be-12, and is an input of this row.'],
    dependencies: [],
    dimensional_signature: '[entropy]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateSackurTetrode', 'PhysJS.SackurTetrode.sackur_tetrode')} Type cross-domain. Derived from be-12 for n_Q, which is an input and is not re-derived here. Stirling is ln N! = N ln N − N, not the series. Not a second proof of be-12.`,
  },
  {
    id: 168,
    name: 'Saha ionization constant',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['plasma', 'quantum'] as [string, string],
    status: 'established' as const,
    context:
      'The thermal factor is the thermal de Broglie wavelength, so K = (2 π m k_B T/h²)^{3/2} exp(−I/(k_B T)). The electron weight 2 and the internal partition functions are not in this statement. Not a second proof of be-12. Saha',
    formula_latex: 'K = (2\\pi m k_B T/h^2)^{3/2} \\exp(-I/(k_B T))',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-168) — established textbook relation, PhysJS.Saha.saha_eq',
    known_issues: [],
    references: ['The thermal factor is PhysJS.ThermalDeBroglie.wavelength_eq, be-12.'],
    dependencies: [],
    dimensional_signature: '[L^-3]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateSaha', 'PhysJS.Saha.saha_eq')} Type cross-domain. Derived from be-12. The electron spin weight 2 and the internal partition functions are not in this statement. Multiplying by 2 is a different number. Not a second proof of be-12.`,
  },
  {
    id: 169,
    name: 'Richardson–Dushman current',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['quantum', 'emission'] as [string, string],
    status: 'established' as const,
    context:
      '∫_a^∞ exp(−c x) dx = exp(−c a)/c is proved. The current is the hypothesis 4 π m e/h³ times one factor k_B T from each tail, so J h³ exp(φ/(k_B T)) = 4 π m e k_B² T². Here e is the elementary charge. The Boltzmann tail replaces Fermi–Dirac and the reflection coefficient is 1. Richardson–Dushman',
    formula_latex: 'J h^3 \\exp(\\varphi/(k_B T)) = 4 \\pi m e k_B^2 T^2',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-169) — established textbook relation, PhysJS.RichardsonDushman.richardson_eq',
    known_issues: [],
    references: ['The phase-space prefactor is a hypothesis of PhysJS.RichardsonDushman.richardson_eq. e is the elementary charge.'],
    dependencies: [],
    dimensional_signature: '[L^-2 I]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateRichardsonDushman', 'PhysJS.RichardsonDushman.richardson_eq')} Type cross-domain. The Boltzmann tail replaces Fermi–Dirac. The reflection coefficient is 1. The prefactor 4 π m e/h³ is a hypothesis. e is the elementary charge.`,
  },
  {
    id: 170,
    name: 'Onsager reciprocity',
    category: 'D',
    category_name: 'Field Unification Bridges',
    bridges: ['thermodynamic', 'transport'] as [string, string],
    status: 'established' as const,
    context:
      'The mixed partials of Φ = ½ L11 X1² + L12 X1 X2 + ½ L22 X2² are both L12, so L12 = L21. thermoelectric_instance applies the Kelvin–Peltier relation, be-73, and does not re-prove Π = S T. An antisymmetric cross term produces no entropy. The magnetic case L12(B) = L21(−B) is not this row. Onsager',
    formula_latex: 'L_{12} = L_{21}',
    source_part: 'III' as const,
    source_section: 'Thermal catalog (be-170) — established textbook relation, PhysJS.OnsagerReciprocity.onsager_eq',
    known_issues: [],
    references: ['thermoelectric_instance applies PhysJS.KelvinRelation.peltier_eq, be-73.'],
    dependencies: [],
    dimensional_signature: '[1]',
    tractability_class: 'closed-form' as const,
    notes: `${proved('evaluateOnsagerReciprocity', 'PhysJS.OnsagerReciprocity.onsager_eq')} Type cross-domain. Zero magnetic field: the magnetic case L12(B) = L21(−B) is not this row. The thermoelectric instance is be-73 and does not re-prove Π = S T. An antisymmetric cross term produces no entropy and is not this equality.`,
  },
];
