#!/usr/bin/env node
/**
 * Generates the SYNTHETIC `upt probe study` controls in this directory.
 * Nothing here is a measurement. `node tests/fixtures/probe-study/generate.mjs`
 * rewrites the files; `tests/composition/probe/study-fixtures.test.ts` checks
 * that the committed files are exactly this script's output.
 *
 * The pendulum period is the exact finite-amplitude period
 * T = 2π√(L/g) / AGM(1, cos(θ₀/2)) plus seeded Gaussian noise, so the
 * small-angle law T ∝ √(L/g) holds on small amplitudes and fails at large ones.
 * The `.csv` files are the same studies rendered as CSV; the replication CSV
 * is a separate acquisition (its own seed and provenance).
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SIGMA_S = 0.002;
const G = 9.81;
const SCRIPT = 'tests/fixtures/probe-study/generate.mjs';

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function gaussian(rand) {
  const u = 1 - rand();
  const v = rand();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function agm(a, b) {
  for (let i = 0; i < 60 && Math.abs(a - b) > 1e-16 * a; i++) [a, b] = [(a + b) / 2, Math.sqrt(a * b)];
  return a;
}

export function exactPeriod(length, gravity, amplitude) {
  return (2 * Math.PI * Math.sqrt(length / gravity)) / agm(1, Math.cos(amplitude / 2));
}

const sig = (x) => Number(x.toPrecision(6));

function pendulumRows(prefix, role, seed, specs, source) {
  const rand = mulberry32(seed);
  return specs.map(([length, amplitude], i) => {
    const t = exactPeriod(length, G, amplitude) + SIGMA_S * gaussian(rand);
    const row = {
      id: `${prefix}${i + 1}`,
      role,
      values: {
        length: i % 4 === 1 ? `${sig(length * 100)} cm` : length,
        gravity: G,
        amplitude: i % 4 === 2 ? `${sig((amplitude * 180) / Math.PI)} deg` : amplitude,
      },
      observed: `${sig(t)} s`,
    };
    return source ? { ...row, source } : row;
  });
}

const EXPLORATORY = [
  [0.4, 0.05], [0.6, 0.03], [0.8, 0.07], [1.0, 0.04], [1.2, 0.06], [1.4, 0.08],
  [1.6, 0.05], [1.8, 0.03], [2.0, 0.07], [2.2, 0.04], [0.5, 0.06], [1.5, 0.05],
];
const REPLICATION = [[0.55, 0.05], [1.1, 0.04], [1.7, 0.06], [2.1, 0.05]];
const HOLDOUT_LENGTHS = [0.45, 0.95, 1.35, 1.95, 2.35];
const SMALL = [0.04, 0.07, 0.05, 0.06, 0.04];
const LARGE = [0.6, 0.75, 0.9, 1.05, 1.2];

const SERIES =
  '2*pi*sqrt(length/gravity)*(1 + amplitude^2/16 + 11*amplitude^4/3072 + 173*amplitude^6/737280)';

function pendulumStudy(holdoutAmplitudes, gapId, summary) {
  return {
    description:
      `SYNTHETIC control, not measured data. ${summary} Generated by ${SCRIPT}; the generating ` +
      'law is known, so a recovery here tests the method, not nature.',
    gap: { id: gapId, kind: 'unexplained-observation', summary },
    provenance: {
      synthetic: true,
      source: `${SCRIPT} (seed 1)`,
      acquisition:
        'SYNTHETIC: T = 2π√(L/g)/AGM(1, cos(θ₀/2)) with seeded Gaussian noise σ = 2 ms; holdout seed 3, ' +
        'replication seed 2. Not a measurement.',
      calibration: 'none: synthetic rows have no instrument',
    },
    target: { name: 'period', unit: 's', sigma: '2 ms' },
    governing: [
      { name: 'length', unit: 'm' },
      { name: 'gravity', unit: 'm/s^2' },
      { name: 'amplitude', unit: 'rad' },
    ],
    baselines: [{ name: 'finite-amplitude series (to θ⁶)', formula: SERIES }],
    criterion: { alpha: 0.001 },
    design: {
      variables: {
        length: { min: 0.4, max: 2.4, steps: 6 },
        gravity: { min: G, max: G, steps: 1 },
        amplitude: { min: 0.02, max: 1.2, steps: 12 },
      },
    },
    observations: [
      ...pendulumRows('e', 'exploratory', 1, EXPLORATORY),
      ...pendulumRows('h', 'holdout', 3, HOLDOUT_LENGTHS.map((l, i) => [l, holdoutAmplitudes[i]])),
      ...pendulumRows('r', 'replication', 2, REPLICATION, `${SCRIPT} (seed 2, independent draw)`),
    ],
  };
}

function noiseStudy() {
  const rand = mulberry32(4);
  const lengths = [0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 0.5, 1.5, 0.45, 0.95, 1.35, 1.95, 2.35];
  const rows = lengths.map((length, i) => ({
    id: i < 12 ? `e${i + 1}` : `h${i - 11}`,
    role: i < 12 ? 'exploratory' : 'holdout',
    values: { length, gravity: G },
    observed: `${sig(0.5 + 4.5 * rand())} s`,
  }));
  return {
    description:
      `SYNTHETIC negative control, not measured data. Periods drawn uniformly in [0.5, 5] s, ` +
      `independent of the inputs, by ${SCRIPT} (seed 4). The search must not explain them.`,
    gap: { id: 'fg-study-pure-noise', kind: 'unexplained-observation', summary: 'periods with no law in length or gravity' },
    provenance: {
      synthetic: true,
      source: `${SCRIPT} (seed 4)`,
      acquisition: 'SYNTHETIC: uniform random periods, independent of every input. Not a measurement.',
      calibration: 'none: synthetic rows have no instrument',
    },
    target: { name: 'period', unit: 's', sigma: '50 ms' },
    governing: [
      { name: 'length', unit: 'm' },
      { name: 'gravity', unit: 'm/s^2' },
    ],
    baselines: [{ name: 'small-angle law 2π√(L/g)', formula: '2*pi*sqrt(length/gravity)' }],
    observations: rows,
  };
}

// Exploratory amplitudes span 0.05–1.2 rad, so the finite-amplitude correction is visible in the fit data.
const WIDE_EXPLORATORY = [
  [0.4, 0.05], [0.6, 0.2], [0.8, 0.35], [1.0, 0.5], [1.2, 0.65], [1.4, 0.8], [1.6, 0.95],
  [1.8, 1.1], [2.0, 1.2], [2.2, 0.1], [0.5, 0.9], [1.5, 0.3], [0.7, 1.15], [1.9, 0.6],
];
const WIDE_HOLDOUT = [[0.45, 0.4], [0.95, 1.0], [1.35, 0.75], [1.95, 0.25], [2.35, 1.05]];
const WIDE_REPLICATION = [[0.55, 0.45], [1.1, 0.85], [1.7, 1.15], [2.1, 0.15]];
const REPLICATION_SOURCE = `${SCRIPT} (seed 6, independent draw)`;

function largeAmplitudeStudy() {
  return {
    description:
      'SYNTHETIC control, not measured data. Exploratory and holdout amplitudes both span 0.05–1.2 rad, and the file ' +
      `declares the correction family (1 + c₁θ² + c₂θ⁴). Generated by ${SCRIPT}; the generating law is known and the ` +
      'family was declared knowing it, so a recovery here tests the method, not nature.',
    gap: { id: 'fg-study-pendulum-large-amplitude', kind: 'unexplained-observation', summary: 'pendulum period across amplitudes' },
    provenance: {
      synthetic: true,
      source: `${SCRIPT} (seed 5)`,
      acquisition: 'SYNTHETIC: T = 2π√(L/g)/AGM(1, cos(θ₀/2)) with seeded Gaussian noise σ = 2 ms; holdout seed 7. Not a measurement.',
      calibration: 'none: synthetic rows have no instrument',
    },
    target: { name: 'period', unit: 's', sigma: '2 ms' },
    governing: [
      { name: 'length', unit: 'm' },
      { name: 'gravity', unit: 'm/s^2' },
      { name: 'amplitude', unit: 'rad' },
    ],
    baselines: [{ name: 'small-angle law 2π√(L/g)', formula: '2*pi*sqrt(length/gravity)' }],
    criterion: { alpha: 0.001 },
    correction: { input: 'amplitude', powers: [2, 4] },
    observations: [
      ...pendulumRows('e', 'exploratory', 5, WIDE_EXPLORATORY),
      ...pendulumRows('h', 'holdout', 7, WIDE_HOLDOUT),
    ],
  };
}

function largeAmplitudeReplication() {
  return {
    description: `SYNTHETIC replication file, not measured data: an independent seeded draw by ${SCRIPT} (seed 6).`,
    provenance: {
      synthetic: true,
      source: REPLICATION_SOURCE,
      acquisition: 'SYNTHETIC: same generating law as the study, seed 6. Not a measurement.',
    },
    target: { name: 'period', unit: 's', sigma: '2 ms' },
    governing: [
      { name: 'length', unit: 'cm' },
      { name: 'gravity', unit: 'm/s^2' },
      { name: 'amplitude', unit: 'deg' },
    ],
    // Bare numbers are read in the declared cm and deg; cells that carry a unit keep it.
    observations: pendulumRows('r', 'replication', 6, WIDE_REPLICATION).map((r) => ({
      ...r,
      values: {
        ...r.values,
        length: typeof r.values.length === 'number' ? sig(r.values.length * 100) : r.values.length,
        amplitude: typeof r.values.amplitude === 'number' ? sig((r.values.amplitude * 180) / Math.PI) : r.values.amplitude,
      },
    })),
  };
}

const SIGMA_L = 0.01;
const INPUT_SIGMA_EXPLORATORY = [0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 0.5, 1.5];
const INPUT_SIGMA_HOLDOUT = [0.45, 0.95, 1.35, 1.95, 2.35];

/** Small-angle rows whose recorded length is off the true one by N(0, σ_L); every 4th row is recorded at σ_L/2. */
export function inputSigmaRows(prefix, role, seed, lengths = INPUT_SIGMA_EXPLORATORY) {
  const rand = mulberry32(seed);
  return lengths.map((length, i) => {
    const sL = i % 4 === 3 ? SIGMA_L / 2 : SIGMA_L;
    const recorded = length + sL * gaussian(rand);
    const t = exactPeriod(length, G, 0) + SIGMA_S * gaussian(rand);
    return {
      id: `${prefix}${i + 1}`,
      role,
      values: { length: sig(recorded), gravity: G },
      observed: `${sig(t)} s`,
      ...(i % 4 === 3 ? { inputSigma: { length: `${sig((sL * 1000))} mm` } } : {}),
    };
  });
}

function inputSigmaStudy() {
  return {
    description:
      'SYNTHETIC control, not measured data. The period is exactly 2π√(L/g) plus σ = 2 ms, but each recorded length ' +
      `is off the true length by Gaussian noise σ_L = 1 cm (5 mm on every 4th row). Generated by ${SCRIPT} (seed 8); ` +
      'the input σ was declared knowing it.',
    gap: { id: 'fg-study-pendulum-input-sigma', kind: 'unexplained-observation', summary: 'small-angle pendulum with uncertain lengths' },
    provenance: {
      synthetic: true,
      source: `${SCRIPT} (seed 8)`,
      acquisition: 'SYNTHETIC: recorded length = true length + N(0, σ_L); T = 2π√(L_true/g) + N(0, 2 ms); holdout seed 9. Not a measurement.',
      calibration: 'none: synthetic rows have no instrument',
    },
    target: { name: 'period', unit: 's', sigma: '2 ms' },
    governing: [
      { name: 'length', unit: 'm', sigma: '1 cm' },
      { name: 'gravity', unit: 'm/s^2' },
    ],
    baselines: [{ name: 'small-angle law 2π√(L/g)', formula: '2*pi*sqrt(length/gravity)' }],
    observations: [
      ...inputSigmaRows('e', 'exploratory', 8, INPUT_SIGMA_EXPLORATORY),
      ...inputSigmaRows('h', 'holdout', 9, INPUT_SIGMA_HOLDOUT),
    ],
  };
}

export const NOISE_AMPLITUDE_SEED = 29;
const NOISE_AMPLITUDES = [0.1, 0.25, 0.4, 0.55, 0.7, 0.85, 1.0, 1.2];
const NOISE_HOLDOUT_AMPLITUDES = [0.15, 0.5, 0.8, 1.1];

/** Periods 2 s + N(0, 0.1 s), independent of every input, at one fixed length. */
export function noiseAmplitudeRows(seed, amplitudes = NOISE_AMPLITUDES, holdout = NOISE_HOLDOUT_AMPLITUDES) {
  const rand = mulberry32(seed);
  return [...amplitudes, ...holdout].map((amplitude, i) => ({
    id: i < amplitudes.length ? `e${i + 1}` : `h${i - amplitudes.length + 1}`,
    role: i < amplitudes.length ? 'exploratory' : 'holdout',
    values: { length: 1, gravity: G, amplitude },
    observed: `${sig(2 + 0.1 * gaussian(rand))} s`,
  }));
}

function noiseAmplitudeStudy() {
  return {
    description:
      'SYNTHETIC negative control, not measured data. Periods are 2 s + Gaussian noise (sd 0.1 s), independent of every ' +
      'input, at one fixed length; the declared σ = 50 ms understates the noise ×2, so a constant is rejected. The ' +
      `declared family (4 powers of amplitude) is the only way to fit. Generated by ${SCRIPT} (seed ${NOISE_AMPLITUDE_SEED}); ` +
      'the seed was chosen so that admitting every declared term WOULD make the fit pass (so the guard can fail).',
    gap: { id: 'fg-study-noise-amplitude', kind: 'unexplained-observation', summary: 'periods with no law in amplitude' },
    provenance: {
      synthetic: true,
      source: `${SCRIPT} (seed ${NOISE_AMPLITUDE_SEED})`,
      acquisition: 'SYNTHETIC: 2 s + N(0, 0.1 s), independent of every input. Not a measurement.',
      calibration: 'none: synthetic rows have no instrument',
    },
    target: { name: 'period', unit: 's', sigma: '50 ms' },
    governing: [
      { name: 'length', unit: 'm' },
      { name: 'gravity', unit: 'm/s^2' },
      { name: 'amplitude', unit: 'rad' },
    ],
    correction: { input: 'amplitude', powers: [2, 4, 6, 8] },
    observations: noiseAmplitudeRows(NOISE_AMPLITUDE_SEED),
  };
}

const PHYSICAL_SIGMA_S = 0.005;

/**
 * A solid sphere of radius r on a massless rod, its centre at L from the pivot: I = mL²(1 + (2/5)(r/L)²)
 * (parallel-axis theorem), and I θ'' = −mgL sin θ, so T = 2π√(L/g)·√(1 + (2/5)(r/L)²) / AGM(1, cos(θ₀/2)).
 */
export function physicalPeriod(length, gravity, amplitude, bobRatio) {
  return exactPeriod(length, gravity, amplitude) * Math.sqrt(1 + 0.4 * bobRatio ** 2);
}

// Both corrections are visible in the fit rows (up to 6% in amplitude, 2.4% in r/L, against σ = 5 ms on ~2 s),
// while the cross term the additive families omit stays below σ.
const PHYSICAL_EXPLORATORY = [
  [0.4, 0.05, 0.0], [0.6, 0.3, 0.35], [0.8, 0.6, 0.1], [1.0, 0.9, 0.25], [1.2, 1.0, 0.0], [1.4, 0.15, 0.3],
  [1.6, 0.45, 0.2], [1.8, 0.75, 0.05], [2.0, 0.95, 0.15], [2.2, 0.2, 0.35], [0.5, 0.85, 0.3], [1.5, 0.55, 0.0],
  [0.7, 0.1, 0.2], [1.9, 0.4, 0.3], [1.1, 0.7, 0.35], [2.1, 0.65, 0.1],
];
const PHYSICAL_HOLDOUT = [[0.45, 0.5, 0.2], [0.95, 0.8, 0.3], [1.35, 0.25, 0.15], [1.95, 0.95, 0.05], [2.35, 0.35, 0.25]];

function physicalRows(prefix, role, seed, specs) {
  const rand = mulberry32(seed);
  return specs.map(([length, amplitude, bobRatio], i) => ({
    id: `${prefix}${i + 1}`,
    role,
    values: { length, gravity: G, amplitude, bob_ratio: bobRatio },
    observed: `${sig(physicalPeriod(length, G, amplitude, bobRatio) + PHYSICAL_SIGMA_S * gaussian(rand))} s`,
  }));
}

function physicalPendulumStudy() {
  return {
    description:
      'SYNTHETIC control, not measured data. A solid sphere of radius r on a massless rod, its centre at L from the ' +
      'pivot, so T = 2π√(L/g)·√(1 + (2/5)(r/L)²)/AGM(1, cos(θ₀/2)). The file declares two correction families, in ' +
      `amplitude and in bob_ratio = r/L. Generated by ${SCRIPT} (seed 10); the generating law is known and both ` +
      'families were declared knowing it, so a recovery here tests the method, not nature.',
    gap: { id: 'fg-study-physical-pendulum', kind: 'unexplained-observation', summary: 'physical pendulum period across amplitudes and bob sizes' },
    provenance: {
      synthetic: true,
      source: `${SCRIPT} (seed 10)`,
      acquisition:
        'SYNTHETIC: T = 2π√(L/g)·√(1 + (2/5)(r/L)²)/AGM(1, cos(θ₀/2)) with seeded Gaussian noise σ = 5 ms; holdout ' +
        'seed 11. Not a measurement.',
      calibration: 'none: synthetic rows have no instrument',
    },
    target: { name: 'period', unit: 's', sigma: '5 ms' },
    governing: [
      { name: 'length', unit: 'm' },
      { name: 'gravity', unit: 'm/s^2' },
      { name: 'amplitude', unit: 'rad' },
      { name: 'bob_ratio', unit: '' },
    ],
    baselines: [{ name: 'small-angle law 2π√(L/g)', formula: '2*pi*sqrt(length/gravity)' }],
    criterion: { alpha: 0.001 },
    correction: [
      { input: 'amplitude', powers: [2, 4] },
      { input: 'bob_ratio', powers: [2, 4] },
    ],
    observations: [
      ...physicalRows('e', 'exploratory', 10, PHYSICAL_EXPLORATORY),
      ...physicalRows('h', 'holdout', 11, PHYSICAL_HOLDOUT),
    ],
  };
}

function render(study) {
  const { observations, ...head } = study;
  const top = JSON.stringify(head, null, 2).replace(/\n}$/, '');
  const rows = observations.map((r) => `    ${JSON.stringify(r)}`).join(',\n');
  return `${top},\n  "observations": [\n${rows}\n  ]\n}\n`;
}

const csvCell = (v) => {
  const s = String(v);
  return /[",]/.test(s) || s !== s.trim() ? `"${s.replace(/"/g, '""')}"` : s;
};
/** A declaration value: text when reading it back as text is unambiguous, else JSON. */
const declText = (v) => {
  if (typeof v !== 'string') return JSON.stringify(v);
  try {
    JSON.parse(v);
    return JSON.stringify(v);
  } catch {
    return v;
  }
};

/** The same study as CSV: declarations above the header, one row per observation. */
function renderCsv(study) {
  const { observations, target, governing, ...head } = study;
  const lines = [];
  const declare = (key, value) => {
    if (value !== null && typeof value === 'object' && !Array.isArray(value) && !['correction', 'design', 'criterion'].includes(key)) {
      for (const [k, v] of Object.entries(value)) declare(`${key}.${k}`, v);
    } else {
      lines.push(`# ${key}: ${declText(value)}`);
    }
  };
  for (const [k, v] of Object.entries(head)) declare(k, v);
  lines.push(`# target: ${target.name}`);
  if (target.sigma !== undefined) declare('target.sigma', target.sigma);
  for (const g of governing) if (g.sigma !== undefined) declare(`governing.${g.name}.sigma`, g.sigma);
  const inputSigma = governing.filter((g) => observations.some((o) => o.inputSigma?.[g.name] !== undefined));
  const rowCols = ['id', 'role', 'source', 'sigma', 'note'].filter((c) => observations.some((o) => o[c] !== undefined));
  lines.push([
    ...rowCols,
    ...governing.map((g) => `${g.name}[${g.unit}]`),
    `${target.name}[${target.unit}]`,
    ...inputSigma.map((g) => `sigma(${g.name})`),
  ].map(csvCell).join(','));
  for (const o of observations) {
    lines.push([
      ...rowCols.map((c) => o[c] ?? ''),
      ...governing.map((g) => o.values[g.name]),
      o.observed,
      ...inputSigma.map((g) => o.inputSigma?.[g.name] ?? ''),
    ].map(csvCell).join(','));
  }
  return `${lines.join('\n')}\n`;
}

/** File name → exact file text. */
export function buildFixtures() {
  return {
    'pendulum-small-angle.synthetic.json': render(
      pendulumStudy(SMALL, 'fg-study-pendulum-small-angle', 'Small-angle pendulum; the holdout stays small-angle.'),
    ),
    'pendulum-regime-change.synthetic.json': render(
      pendulumStudy(LARGE, 'fg-study-pendulum-regime-change', 'Small-angle exploratory rows; the holdout is large-amplitude (0.6–1.2 rad), a change of regime.'),
    ),
    'pure-noise.synthetic.json': render(noiseStudy()),
    'pendulum-large-amplitude.synthetic.json': render(largeAmplitudeStudy()),
    'pendulum-large-amplitude.synthetic.csv': renderCsv(largeAmplitudeStudy()),
    'pendulum-large-amplitude.replication.synthetic.csv': renderCsv(largeAmplitudeReplication()),
    'pendulum-input-sigma.synthetic.json': render(inputSigmaStudy()),
    'noise-amplitude.synthetic.json': render(noiseAmplitudeStudy()),
    'pendulum-physical.synthetic.json': render(physicalPendulumStudy()),
  };
}

export { renderCsv };

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const dir = dirname(fileURLToPath(import.meta.url));
  for (const [name, text] of Object.entries(buildFixtures())) writeFileSync(join(dir, name), text);
}
