#!/usr/bin/env node
/**
 * Generates the SYNTHETIC `upt probe study` controls in this directory.
 * Nothing here is a measurement. `node tests/fixtures/probe-study/generate.mjs`
 * rewrites the files; `tests/composition/probe/study-fixtures.test.ts` checks
 * that the committed files are exactly this script's output.
 *
 * The pendulum period is the exact finite-amplitude period
 * T = 2π√(L/g) / AGM(1, cos(θ₀/2)) plus seeded Gaussian noise, so the
 * small-angle law T ∝ √(L/g) holds on small amplitudes and fails at large ones.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SIGMA_S = 0.002;
const G = 9.81;
const SCRIPT = 'tests/fixtures/probe-study/generate.mjs';

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function gaussian(rand) {
  const u = 1 - rand();
  const v = rand();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function agm(a, b) {
  for (let i = 0; i < 60 && Math.abs(a - b) > 1e-16 * a; i++) [a, b] = [(a + b) / 2, Math.sqrt(a * b)];
  return a;
}

export function exactPeriod(length, gravity, amplitude) {
  return (2 * Math.PI * Math.sqrt(length / gravity)) / agm(1, Math.cos(amplitude / 2));
}

const sig = (x) => Number(x.toPrecision(6));

function pendulumRows(prefix, role, seed, specs, source) {
  const rand = mulberry32(seed);
  return specs.map(([length, amplitude], i) => {
    const t = exactPeriod(length, G, amplitude) + SIGMA_S * gaussian(rand);
    const row = {
      id: `${prefix}${i + 1}`,
      role,
      values: {
        length: i % 4 === 1 ? `${sig(length * 100)} cm` : length,
        gravity: G,
        amplitude: i % 4 === 2 ? `${sig((amplitude * 180) / Math.PI)} deg` : amplitude,
      },
      observed: `${sig(t)} s`,
    };
    return source ? { ...row, source } : row;
  });
}

const EXPLORATORY = [
  [0.4, 0.05], [0.6, 0.03], [0.8, 0.07], [1.0, 0.04], [1.2, 0.06], [1.4, 0.08],
  [1.6, 0.05], [1.8, 0.03], [2.0, 0.07], [2.2, 0.04], [0.5, 0.06], [1.5, 0.05],
];
const REPLICATION = [[0.55, 0.05], [1.1, 0.04], [1.7, 0.06], [2.1, 0.05]];
const HOLDOUT_LENGTHS = [0.45, 0.95, 1.35, 1.95, 2.35];
const SMALL = [0.04, 0.07, 0.05, 0.06, 0.04];
const LARGE = [0.6, 0.75, 0.9, 1.05, 1.2];

const SERIES =
  '2*pi*sqrt(length/gravity)*(1 + amplitude^2/16 + 11*amplitude^4/3072 + 173*amplitude^6/737280)';

function pendulumStudy(holdoutAmplitudes, gapId, summary) {
  return {
    description:
      `SYNTHETIC control, not measured data. ${summary} Generated by ${SCRIPT}; the generating ` +
      'law is known, so a recovery here tests the method, not nature.',
    gap: { id: gapId, kind: 'unexplained-observation', summary },
    provenance: {
      synthetic: true,
      source: `${SCRIPT} (seed 1)`,
      acquisition:
        'SYNTHETIC: T = 2π√(L/g)/AGM(1, cos(θ₀/2)) with seeded Gaussian noise σ = 2 ms; holdout seed 3, ' +
        'replication seed 2. Not a measurement.',
      calibration: 'none: synthetic rows have no instrument',
    },
    target: { name: 'period', unit: 's', sigma: '2 ms' },
    governing: [
      { name: 'length', unit: 'm' },
      { name: 'gravity', unit: 'm/s^2' },
      { name: 'amplitude', unit: 'rad' },
    ],
    baselines: [{ name: 'finite-amplitude series (to θ⁶)', formula: SERIES }],
    criterion: { alpha: 0.001 },
    design: {
      variables: {
        length: { min: 0.4, max: 2.4, steps: 6 },
        gravity: { min: G, max: G, steps: 1 },
        amplitude: { min: 0.02, max: 1.2, steps: 12 },
      },
    },
    observations: [
      ...pendulumRows('e', 'exploratory', 1, EXPLORATORY),
      ...pendulumRows('h', 'holdout', 3, HOLDOUT_LENGTHS.map((l, i) => [l, holdoutAmplitudes[i]])),
      ...pendulumRows('r', 'replication', 2, REPLICATION, `${SCRIPT} (seed 2, independent draw)`),
    ],
  };
}

function noiseStudy() {
  const rand = mulberry32(4);
  const lengths = [0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 0.5, 1.5, 0.45, 0.95, 1.35, 1.95, 2.35];
  const rows = lengths.map((length, i) => ({
    id: i < 12 ? `e${i + 1}` : `h${i - 11}`,
    role: i < 12 ? 'exploratory' : 'holdout',
    values: { length, gravity: G },
    observed: `${sig(0.5 + 4.5 * rand())} s`,
  }));
  return {
    description:
      `SYNTHETIC negative control, not measured data. Periods drawn uniformly in [0.5, 5] s, ` +
      `independent of the inputs, by ${SCRIPT} (seed 4). The search must not explain them.`,
    gap: { id: 'fg-study-pure-noise', kind: 'unexplained-observation', summary: 'periods with no law in length or gravity' },
    provenance: {
      synthetic: true,
      source: `${SCRIPT} (seed 4)`,
      acquisition: 'SYNTHETIC: uniform random periods, independent of every input. Not a measurement.',
      calibration: 'none: synthetic rows have no instrument',
    },
    target: { name: 'period', unit: 's', sigma: '50 ms' },
    governing: [
      { name: 'length', unit: 'm' },
      { name: 'gravity', unit: 'm/s^2' },
    ],
    baselines: [{ name: 'small-angle law 2π√(L/g)', formula: '2*pi*sqrt(length/gravity)' }],
    observations: rows,
  };
}

function render(study) {
  const { observations, ...head } = study;
  const top = JSON.stringify(head, null, 2).replace(/\n}$/, '');
  const rows = observations.map((r) => `    ${JSON.stringify(r)}`).join(',\n');
  return `${top},\n  "observations": [\n${rows}\n  ]\n}\n`;
}

/** File name → exact file text. */
export function buildFixtures() {
  return {
    'pendulum-small-angle.synthetic.json': render(
      pendulumStudy(SMALL, 'fg-study-pendulum-small-angle', 'Small-angle pendulum; the holdout stays small-angle.'),
    ),
    'pendulum-regime-change.synthetic.json': render(
      pendulumStudy(LARGE, 'fg-study-pendulum-regime-change', 'Small-angle exploratory rows; the holdout is large-amplitude (0.6–1.2 rad), a change of regime.'),
    ),
    'pure-noise.synthetic.json': render(noiseStudy()),
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const dir = dirname(fileURLToPath(import.meta.url));
  for (const [name, text] of Object.entries(buildFixtures())) writeFileSync(join(dir, name), text);
}
