/**
 * Generate docs/CLI.md, the README command tables, and the command and flag
 * tables of cli/README.md from the CLI registry.
 *
 * `bun scripts/cli-reference.ts` rewrites all three.
 * `bun scripts/cli-reference.ts --check` exits 1 when any is stale.
 * The `docs-fresh` job runs `--check`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { FlagSpec } from '../src/cli/args.js';
import { listCommandNames, resolveCommand, type Command, type CommandGroup } from '../src/cli/command.js';
import { BUILTIN_VERBS, GLOBAL_FLAGS, flagHeading } from '../src/cli/flag-help.js';
import '../src/cli/commands/index.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const GROUP_ORDER: readonly CommandGroup[] = ['evaluate', 'explore', 'discovery', 'data', 'utilities'];

const GROUP_TITLE: Readonly<Record<CommandGroup, string>> = {
  evaluate: 'Evaluate and check',
  explore: 'Explore bridges and the atlas',
  discovery: 'Discovery and probes',
  data: 'Data and confrontation',
  utilities: 'Utilities',
};

function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function commands(): Command[] {
  const out: Command[] = [];
  for (const name of listCommandNames()) {
    const command = resolveCommand(name);
    if (command === undefined || command.name !== name) continue;
    out.push(command);
  }
  return out;
}

function requireMeta(command: Command): { summary: string; example: string; group: CommandGroup } {
  if (command.summary === undefined || command.summary.trim() === '') {
    throw new Error(`${command.name}: missing summary`);
  }
  if (command.example === undefined || !command.example.startsWith('upt ')) {
    throw new Error(`${command.name}: example must be an upt invocation`);
  }
  if (command.group === undefined) throw new Error(`${command.name}: missing group`);
  for (const flag of command.flags) {
    if (flag.description === undefined || flag.description.trim() === '') {
      throw new Error(`${command.name} ${flag.name}: missing description`);
    }
  }
  return { summary: command.summary, example: command.example, group: command.group };
}

function synopsis(command: Command): string {
  const line = command.help.split('\n')[0] ?? '';
  return line.trim();
}

function flagTable(flags: readonly FlagSpec[]): string {
  if (flags.length === 0) return 'This command takes no flags.\n';
  const rows = flags.map((flag) => {
    const value =
      flag.valueStyle === 'none' ? 'no' : flag.valueStyle === 'next' ? 'next token' : flag.valueStyle === 'attached' ? '`=` value' : '`=` or next token';
    const repeat = flag.repeatable ? ', repeatable' : '';
    return `| \`${cell(flagHeading(flag))}\` | ${value}${repeat} | ${cell(flag.defaultValue ?? '')} | ${cell(flag.description ?? '')} |`;
  });
  return ['| Flag | Value | Default | Description |', '|---|---|---|---|', ...rows].join('\n');
}

/** The reference page. Every command, every flag, one example. */
export function renderCliReference(list: readonly Command[] = commands()): string {
  const lines: string[] = [];
  lines.push('# `upt` command reference');
  lines.push('');
  lines.push('Generated from the command registry by `scripts/cli-reference.ts`. Do not edit this file.');
  lines.push('`bun scripts/cli-reference.ts` rewrites it. `bun scripts/cli-reference.ts --check` fails when it is stale.');
  lines.push('');
  lines.push('A bare `e` in a formula is the elementary charge. `E` is energy. Euler\'s number is `exp(x)`, for example `exp(1)`. The name `euler` is refused.');
  lines.push('');
  lines.push('## Global options');
  lines.push('');
  lines.push('Accepted before the command name. `--json` may also follow the command name on any command that lists it below.');
  lines.push('');
  lines.push(flagTable(GLOBAL_FLAGS));
  lines.push('');
  lines.push('`upt <command> --help` prints that command and exits 0. An unknown flag exits 2 and names the flag. `upt version` prints one semver line and takes no arguments.');
  lines.push('');

  const byGroup = new Map<CommandGroup, Command[]>();
  for (const group of GROUP_ORDER) byGroup.set(group, []);
  for (const command of list) {
    const meta = requireMeta(command);
    byGroup.get(meta.group)!.push(command);
  }
  for (const group of GROUP_ORDER) {
    lines.push(`## ${GROUP_TITLE[group]}`);
    lines.push('');
    const groupCommands = byGroup.get(group)!;
    if (group === 'utilities') {
      for (const verb of BUILTIN_VERBS) {
        lines.push(`### \`${verb.name}\``);
        lines.push('');
        lines.push(verb.summary);
        lines.push('');
        lines.push('```');
        lines.push(verb.example);
        lines.push('```');
        lines.push('');
      }
    }
    for (const command of groupCommands) {
      const meta = requireMeta(command);
      const alias = command.aliases.length === 0 ? '' : ` Aliases: ${command.aliases.map((a) => `\`${a}\``).join(', ')}.`;
      lines.push(`### \`${command.name}\``);
      lines.push('');
      lines.push(meta.summary + alias);
      lines.push('');
      lines.push('```');
      lines.push(synopsis(command));
      lines.push('```');
      lines.push('');
      if (command.subcommands !== undefined && command.subcommands.length > 0) {
        lines.push('| Subcommand | What it does |');
        lines.push('|---|---|');
        for (const sub of command.subcommands) {
          lines.push(`| \`${cell(sub.name)}\` | ${cell(sub.summary)} |`);
        }
        lines.push('');
      }
      lines.push(flagTable(command.flags));
      lines.push('');
      lines.push('```');
      lines.push(meta.example);
      lines.push('```');
      lines.push('');
    }
  }
  return lines.join('\n');
}

function commandRows(list: readonly Command[]): string {
  const byGroup = new Map<CommandGroup, string[]>();
  for (const group of GROUP_ORDER) byGroup.set(group, []);
  for (const command of list) {
    const meta = requireMeta(command);
    const alias = command.aliases.length === 0 ? '' : ` (${command.aliases.map((a) => `\`${a}\``).join(', ')})`;
    byGroup.get(meta.group)!.push(`| \`${command.name}\`${alias} | ${cell(meta.summary)} |`);
  }
  const parts: string[] = [];
  const registered = list.length;
  const total = registered + BUILTIN_VERBS.length;
  parts.push(`${total} commands: ${registered} registered, plus \`help\` and \`version\`.`);
  parts.push('');
  for (const group of GROUP_ORDER) {
    parts.push(`**${GROUP_TITLE[group]}**`);
    parts.push('');
    parts.push('| Command | What it does |');
    parts.push('|---|---|');
    const rows = byGroup.get(group)!;
    if (group === 'utilities') {
      for (const verb of BUILTIN_VERBS) {
        parts.push(`| \`${verb.name}\` | ${cell(verb.summary)} |`);
      }
    }
    parts.push(...rows);
    parts.push('');
  }
  return parts.join('\n').replace(/\n$/, '');
}

function globalRows(): string {
  const rows = GLOBAL_FLAGS.map((flag) => {
    return `| \`${cell(flag.name)}\` | ${cell(flag.defaultValue ?? '')} | ${cell(flag.description ?? '')} |`;
  });
  return ['| Option | Default | What it does |', '|---|---|---|', ...rows].join('\n');
}

function replaceSpan(text: string, name: string, body: string, file = 'README.md'): string {
  const start = `<!-- cli-reference:${name} -->`;
  const end = `<!-- /cli-reference:${name} -->`;
  const i = text.indexOf(start);
  const j = text.indexOf(end);
  if (i < 0 || j < i) throw new Error(`${file} is missing ${start} … ${end}`);
  return text.slice(0, i + start.length) + `\n${body}\n` + text.slice(j);
}

/** Rewrite the marked README spans. The markers must already be in the file. */
export function stampReadme(readme: string, list: readonly Command[] = commands()): string {
  let next = replaceSpan(readme, 'commands', commandRows(list));
  next = replaceSpan(next, 'globals', globalRows());
  return next;
}

/**
 * Every flag a registered command parses, grouped by flag name: the commands
 * that take it and its description. A flag whose description differs between
 * commands lists each command's own sentence, so no sentence is invented.
 */
function flagRows(list: readonly Command[]): string {
  const byFlag = new Map<string, { command: string; description: string }[]>();
  for (const command of list) {
    for (const flag of command.flags) {
      const rows = byFlag.get(flag.name) ?? [];
      rows.push({ command: command.name, description: flag.description ?? '' });
      byFlag.set(flag.name, rows);
    }
  }
  const lines = ['| Flag | Commands | What it does |', '|---|---|---|'];
  for (const [name, rows] of [...byFlag].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
    const commandsCell = rows.map((r) => `\`${r.command}\``).join(', ');
    const descriptions = [...new Set(rows.map((r) => r.description))];
    const effect =
      descriptions.length === 1
        ? cell(descriptions[0]!)
        : rows.map((r) => `${r.command}: ${cell(r.description)}`).join(' ');
    lines.push(`| \`${cell(name)}\` | ${commandsCell} | ${effect} |`);
  }
  return lines.join('\n');
}

/** Rewrite the marked spans of cli/README.md: the command tables and the flag table. */
export function stampCliReadme(readme: string, list: readonly Command[] = commands()): string {
  let next = replaceSpan(readme, 'commands', commandRows(list), 'cli/README.md');
  next = replaceSpan(next, 'globals', globalRows(), 'cli/README.md');
  next = replaceSpan(next, 'flags', flagRows(list), 'cli/README.md');
  return next;
}

function main(): void {
  const check = process.argv.includes('--check');
  const cliPath = join(root, 'docs/CLI.md');
  const readmePath = join(root, 'README.md');
  const cliReadmePath = join(root, 'cli/README.md');
  const nextCli = renderCliReference();
  const readme = readFileSync(readmePath, 'utf8');
  const nextReadme = stampReadme(readme);
  const cliReadme = readFileSync(cliReadmePath, 'utf8');
  const nextCliReadme = stampCliReadme(cliReadme);
  let currentCli = '';
  try {
    currentCli = readFileSync(cliPath, 'utf8');
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code !== 'ENOENT') throw err;
  }
  const cliStale = currentCli !== nextCli;
  const readmeStale = readme !== nextReadme;
  const cliReadmeStale = cliReadme !== nextCliReadme;
  if (!cliStale && !readmeStale && !cliReadmeStale) {
    console.log('cli-reference: docs/CLI.md, the README spans and the cli/README.md spans match the registry.');
    return;
  }
  if (check) {
    console.error('cli-reference: docs/CLI.md, README.md or cli/README.md is stale. Run `bun scripts/cli-reference.ts` and commit the result.');
    process.exit(1);
  }
  if (cliStale) writeFileSync(cliPath, nextCli);
  if (readmeStale) writeFileSync(readmePath, nextReadme);
  if (cliReadmeStale) writeFileSync(cliReadmePath, nextCliReadme);
  console.log('cli-reference: rewrote the stale file(s).');
}

if (import.meta.main) main();
